### ISSUE TITLE
Help content bugs

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1004]
### Build number

608

### Bug description

- Liquor Store description contains the wrong products: 
![grafik](https://user-images.githubusercontent.com/17579552/161105959-67406c02-7ff8-4867-9162-2f4d6ae6bc22.png)
- "Headquarter" should be named "Headquarters" (there's no singular for that word)
- Warehouse is missing 
- Expensive Jewelry is listed twice in Sellable Products 
![grafik](https://user-images.githubusercontent.com/17579552/161106523-96a00b42-a6ae-4c47-9576-3c80e301d100.png)
- Expensive Gifts: Product name in the text is not bold (all other products have their own name displayed bold). Same for the furniture "Stack of shopping baskets" and "Rounded shelf".
![grafik](https://user-images.githubusercontent.com/17579552/161106954-0242b322-9e3d-4cb1-9525-5516d392a161.png)
- Stack of Shopping Baskets: The description tells they can be bought in most wholesale stores, while actually they have to be bought in the appliance store.
- Wine shelf and Cigar shelf description are still missing

**Comment by jhovgaard** [comment]
Fixed in build 724
