### ISSUE TITLE
Shopping Basket Reads $0 When Put In Handtruck

### ISSUE THREAD

**Issue by AwesomeGuy1052** [hovgaardgames/bigambitions#1009]
### Build number

606

### Bug description

Shopping baskets full of FreshFood (I am assuming any item but have not tested) reads $0 and are presumably 'empty' when placed in a handtruck. However, everything is still in the basket when removed from the handtruck.

### Steps to reproduce the bug

I filled my baskets full of FreshFood (reads: 4x $8) and when I put the baskets in a handtruck they read $0, however, when removed from the handtruck they go back to reading the correct numbers exactly like they were before putting them in the handtruck.

Screenshots attached below

### Savegame file

[Beta1_B606.txt](https://github.com/hovgaardgames/bigambitions/files/8396044/Beta1_B606.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/87638254/161227322-c8cffd93-f1d4-4dc1-9e45-3a9dac67784c.png)
![image](https://user-images.githubusercontent.com/87638254/161227333-e2dc1a85-72dd-44cb-817d-82f0112468d8.png)

**Comment by AwesomeGuy1052** [comment]
Just found out too that when you go to checkout, you must remove each basket and checkout 1 by 1. Not sure whether it is meant to be like that or not but thought I would comment here just in case.
![image](https://user-images.githubusercontent.com/87638254/161229020-348a942a-f0f9-4d72-ae56-16597b2a28f9.png)

**Comment by jokoho48** [comment]
Fixed in Build 724. you should not be able to put Shopping Baskets into Handtrucks
