### ISSUE TITLE
Menu's dissapear

### ISSUE THREAD

**Issue by Decimes** [hovgaardgames/bigambitions#1010]
### Build number

610

### Bug description

I wanted to recruit a driver. But when I click Hire Candidate nothing happens. When I go back to the main screen all menu's have dissapeared. And can not do anything anymore. 

Extra info:
If I do not go back to main screen right away, but click MyEmployees;
(The driver didnt get hired)
Sorting the employees by "Hours" only shows the employees with 0 hours.
Sorting by "Task" makes them all dissapear.

### Steps to reproduce the bug

Guess trying to recruit 10 drivers of 15-30 within 1 day.
Save games: 4 is before trying to hire a driver. 4B is right after trying to Hire Candidate.

### Savegame file

[Beta1-4.txt](https://github.com/hovgaardgames/bigambitions/files/8402208/Beta1-4.txt)
[Beta1-4B.txt](https://github.com/hovgaardgames/bigambitions/files/8402209/Beta1-4B.txt)

**Comment by David-Goru** [comment]
Fixed in build 611
