### ISSUE TITLE
When grabbing & packing a cash register, the assigned employees are not removed

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1013]
### Build number

613

### Bug description

When you grab and pack an existing cash register, it is removed from the BizMan schedule, but the assigned employees are still kept. You won't be able to assign the employees to a new cash register.

### Savegame file

[IRegisteredARegisteredRegister.json.txt](https://github.com/hovgaardgames/bigambitions/files/8403164/IRegisteredARegisteredRegister.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161396342-5baa3ebd-39ef-4b0f-8833-2d633754d73c.mp4

**Comment by David-Goru** [comment]
Fixed in build 709
