### ISSUE TITLE
"Empty fridge" causes need to pay for items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1014]
### Build number

613

### Bug description

If you use the "Empty fridge" button, you can't leave your apartment with the resulting paper bag because you would have to pay for it first.

### Savegame file

[FridgeGlitch.json.txt](https://github.com/hovgaardgames/bigambitions/files/8403203/FridgeGlitch.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161396746-8d022958-d114-4464-bb2f-10d6f837086f.mp4

**Comment by David-Goru** [comment]
Fixed in build 709
