### ISSUE TITLE
Fridge box can be placed in paper bag

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1015]
### Build number

613

### Bug description

When a fridge is placed in a box on the hand truck, and you're carrying a paper bag, then you can move the fridge from the hand truck's cargo dialog into the paper bag.

(This is not limited to the fridge and the hand truck, you can generally put anything from a cargo dialog into the paper bag, even from your car's cargo dialog)

### Steps to reproduce the bug

1. Remove items from fridge and place the paper bag on the floor
2. Grab the fridge and place it on the hand truck
3. Take the paper bag in your hands
4. Open the hand truck's cargo dialog and click the fridge

### Savegame file

[FridgeGlitch.json.txt](https://github.com/hovgaardgames/bigambitions/files/8403211/FridgeGlitch.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161396972-7d0bb7ac-2235-4673-9090-5b3872ce1296.mp4

**Comment by David-Goru** [comment]
Fixed in build 729
