### ISSUE TITLE
Unable to complete verification of import mission.

### ISSUE THREAD

**Issue by Goinnutz** [hovgaardgames/bigambitions#1016]
### Build number

613

### Bug description

Unable to complete verification of products on import mission. Have restarted the game and left the warehouse and gone back in multiple times to try and fix the issue.

### Steps to reproduce the bug

I was just following along with the missions.

### Savegame file

[SaveGame.txt](https://github.com/hovgaardgames/bigambitions/files/8404099/SaveGame.txt)

### Screenshots or videos

![277255064_1649124195449737_8925901973617992122_n](https://user-images.githubusercontent.com/83568292/161419667-ac7ba67c-c2d6-4008-944f-a83efdd29b71.jpg)

**Comment by David-Goru** [comment]
Fixed in build 708
