### ISSUE TITLE
EconoView: Business Type "Empty" for Warehouses

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1017]
### Build number

613

### Bug description

For Warehouses, the EconoView details will show "Empty" as category.

### Savegame file

[FridgeGlitch.json.txt](https://github.com/hovgaardgames/bigambitions/files/8404526/FridgeGlitch.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/161428821-ee145ce2-3c83-48ea-9182-cff5c11119b8.png)

**Comment by David-Goru** [comment]
Fixed in build 709
