### ISSUE TITLE
Car can get stuck on tree with fence

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1019]
### Build number

615

### Bug description

It is possible to drive over the fence around trees next to the park.
While I could only make it with the van, obviously it's also possible with smaller cars which will then get stuck:
https://community.bigambitionsgame.com/t/car-stuck-on-fenced-tree/1069

Secret hint for devs: “Increase height of street prop colliders”

### Savegame file

[StuckyVan.json.txt](https://github.com/hovgaardgames/bigambitions/files/8455617/StuckyVan.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/162541792-6ddcc432-2876-48e5-9d58-45202fde270c.mp4

**Comment by jokoho48** [comment]
Fixed in Build 731.
