### ISSUE TITLE
Glitchy floor when looking through building 28 Second Avenue

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1024]
### Build number

728

### Bug description

When the camera phases through the building on the corner of 2nd avenue & 8th street (when building obstructs the players vision of their character), the ground of the building glitches.

### Steps to reproduce the bug

Stand/Walk near the building on the corner of 2nd avenue & 8th street
Angle the camera so that it must look through the building to see the player
Floor of the building should start flashing

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8601787/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166208687-328bca5e-8e60-45ad-9aaa-7298550de451.mp4

**Comment by GrayySheep** [comment]
Turns out a lot of buildings do this. If help is needed/wanted finding all the buildings that do this, dm me on discord GraySheep#0174

**Comment by jhovgaard** [comment]
Fixed in build 731. I believe I got all the buildings, but if you see others (after Build 731) please let me know :)
