### ISSUE TITLE
Trees Obstructing Road

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1025]
### Build number

728

### Bug description

Trees on the road on the corner of 2nd Avenue & 7th Street obstructing the road, blocking player vehicle. AI vehicles drive through the trees as if they aren't there.

### Steps to reproduce the bug

Unknown.
Trees randomly appeared after time I believe.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8601890/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166210817-07312d53-469c-40b4-8b62-bf32d1d4f91c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 730
