### ISSUE TITLE
Parked vehicles spawning inside each other

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1026]
### Build number

728

### Bug description

Parked vehicles on the side of the road are spawning inside each other.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8601951/1st.play.txt)

### Screenshots or videos

![Big Ambitions 2_05_2022 9_11_45 pm](https://user-images.githubusercontent.com/104757675/166212424-abc18f43-72a9-4d38-a588-8335608efb7b.png)

**Comment by jhovgaard** [comment]
Fixed in build 730
