### ISSUE TITLE
Map scroll freezing

### ISSUE THREAD

**Issue by clausenoe** [hovgaardgames/bigambitions#1029]
### Build number

729

### Bug description

When scrolling around map with keyboards, the scrolling will freeze when getting the park gets to the center of the map
![image_2022-05-02_161013215](https://user-images.githubusercontent.com/104775288/166248250-df8c4298-80d0-42a5-a5bc-e3ba0e794c0b.png)

### Steps to reproduce the bug

Open map, scroll with ASDW towards the park and it will reproduce.

**Comment by clausenoe** [comment]
https://youtu.be/Ys1MV_vGerk

**Comment by David-Goru** [comment]
Fixed in build 731
