### ISSUE TITLE
Roof gap in drive-in wholesale store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#103]
Build 49

Between wall and roof of the drive-in wholesale store there's a gap.
It's especially visible in the building outline but can also be seen in normal display.
![grafik](https://user-images.githubusercontent.com/17579552/120249359-e47b0c00-c27a-11eb-980c-53079c2afd95.png)
![grafik](https://user-images.githubusercontent.com/17579552/120249369-f2309180-c27a-11eb-8296-f34c7b187f01.png)

**Comment by David-Goru** [comment]
Fixed in the past
