### ISSUE TITLE
Random movement stop

### ISSUE THREAD

**Issue by xreec** [hovgaardgames/bigambitions#1030]
### Build number

729

### Bug description

While moving in city or map overview the movement sometimes stop, in the map overview its bad around the park.

### Steps to reproduce the bug

Goto map overview and use arrow up until movement stops(if not try around the park) if i start moving the mouse while holding the arrow up key the movement will begin again.

**Comment by jhovgaard** [comment]
Looks like you reported this at the same time :) Closing this.
https://github.com/hovgaardgames/bigambitions/issues/1030
