### ISSUE TITLE
Job board item overlay shown permanently

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1033]
### Build number

729

### Bug description

If you enter El Gato right away after starting a game, the job boards will permanently show the item overlay, instead of just on mouseover (like every other item).
As the objective to get a job is not yet shown, I think this shouldn't be the case.

### Savegame file

[EliGator.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606136/EliGator.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166329911-ae54bafa-0dd9-41ee-aecc-62ddea75e0e3.png)

**Comment by jhovgaard** [comment]
Let's add a check and only show the overlay, if the job objective hasn't been completed.

**Comment by David-Goru** [comment]
Fixed in build 731
