### ISSUE TITLE
El Gato: Queue stuck, player stuck after I finish my shift

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1034]
### Build number

729

### Bug description

I have just finished my first shift at El Gato, and immediately (before leaving the building) try to buy food, but both queues are stuck.
Additionally, even after leaving the queue, I still can't move anymore. Mouse has no effect, WASD just in a very small circle.

### Savegame file

[ElStucko.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606172/ElStucko.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166330678-6572eb16-9daf-4409-9dcc-a33a40421af1.png)

**Comment by David-Goru** [comment]
Fixed in build 731
