### ISSUE TITLE
Destination marker showing wrong direction if destination is far away

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1035]
### Build number

729

### Bug description

When I start walking at the appliance store, the destination marker shows to the "bottom left", although the destination building is at the "bottom right".
The closer I get, the more the destination marker turns into the correct direction.

### Savegame file

[VoogleMapsLies.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606240/VoogleMapsLies.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/166333478-b57befeb-fe64-4625-a171-787078084d9f.mp4

**Comment by jhovgaard** [comment]
@jokoho48 Thoughts on this, can we fix?

**Comment by jokoho48** [comment]
I have an idea what it could be. let me investigate

**Comment by jokoho48** [comment]
Fixed in Build 731.
