### ISSUE TITLE
Pink post at side entrance from sidewalk to drive-in wholesales

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1036]
### Build number

729

### Bug description

At the "side entrance" from the sidewalk to the drive-in wholesales, there's a pink post.

### Savegame file

[IDontLikePink.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606311/IDontLikePink.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166334904-a7eef1e4-2300-49df-899e-ade05f491dfc.png)

**Comment by jokoho48** [comment]
Fixed in Build 731.
