### ISSUE TITLE
Bank loan limit: Bank sets limit to $40,000 but doesn't count in interest of new loan

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1037]
### Build number

729

### Bug description

When you ask for another loan at the bank, it will set the limit to $40,000 - including the interest of old loans but not new ones.
In my case, the old loans were $20,000, including interest $23,673.
I was able to take a new loan of $16,000 but not $17,000 - obviously because $17,000 + $23,673 > $40,000. However, after taking the $16,000 loan, I still end up higher than $40,000 due to the new interest.

I think if interest is included in the limit, then it should be done for the interest of the new loan as well.

### Savegame file

[BankWeirdos.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606449/BankWeirdos.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166339031-e1ae30df-73b9-4dc7-a5a9-c1c04b33ad47.png)

**Comment by David-Goru** [comment]
Fixed in build 731
