### ISSUE TITLE
Autosaves stop saving at midnight(?)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1038]
### Build number

729

### Bug description

It's 00:54 now. Day 9.
I got autosaves from 23:24, 23:36 and 23:53, but nothing afterwards anymore.
Might it be possible that autosaving gets broken once the "real" time reaches a new day?

### Savegame file
[BankWeirdos.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606458/BankWeirdos.json.txt)

[Player.zip](https://github.com/hovgaardgames/bigambitions/files/8606466/Player.zip)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166339371-829d3873-0cdd-4b27-9e28-b44497c94a96.png)

**Comment by jhovgaard** [comment]
Closing until Daniel reopens.

**Comment by Gerwanese** [comment]
Just loaded my savegame from last night, played several days, no autosave happening at all.
[Beta2-Walkthrough.json.txt](https://github.com/hovgaardgames/bigambitions/files/8614397/Beta2-Walkthrough.json.txt)

[Player.log](https://github.com/hovgaardgames/bigambitions/files/8614400/Player.-.Kopie.log)

**Comment by David-Goru** [comment]
Closing as it may be related to Daniel's infinite list of savegames
