### ISSUE TITLE
Pizza oven can't be bought at AJ Pederson

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1039]
### Build number

729

### Bug description

The pizza oven at AJ Pederson shows "Pizza" for $9,60 and asks for a shopping basket.

### Savegame file

[BankWeirdos.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606484/BankWeirdos.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166340188-f2a9dc9d-3db4-41c1-b96a-091f678adabc.png)

**Comment by David-Goru** [comment]
Fixed in build 731
