### ISSUE TITLE
Forklift graphics issues

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#104]
Build 49

Just one bug for the issues with the forklift (I can separate them if needed):

Video 1:
- Shadow is very ugly to say the least... blurry and sometimes part of it is disappearing for a short moment
- Forklift can drive into drive-in door and get partly through it

Video 2:
- When driving the forklift, everything seems to be shivering; it wasn't like this in previous versions

**Comment by Gerwanese** [comment]
Video 1:
https://user-images.githubusercontent.com/17579552/121549832-7d91eb80-ca0e-11eb-8031-4c2b2581a384.mp4

Video 2:
https://user-images.githubusercontent.com/17579552/121549847-808cdc00-ca0e-11eb-9ff2-1342c503d295.mp4

**Comment by jokoho48** [comment]
Fixed along time ago
