### ISSUE TITLE
Adding more of already paid products into car will show them as already paid

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1040]
### Build number

729

### Bug description

At the drive-in wholesales, I already had 1x paperbag, 1x sodacan, 1x french fries and 1x salad paid and still in the car.
Then I entered the drive-in again and added 2x burger, 1x hotdog and 1x french fries. As you can see, it now shows 2x french fries as already paid.

At checkout, I still have to pay for them - so it's just a display error. Paid and unpaid items of the same type would have to be displayed separately.

### Savegame file

[WholesalesTheft.json.txt](https://github.com/hovgaardgames/bigambitions/files/8606541/WholesalesTheft.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166341703-6cff5954-d022-4b0c-a1b9-56f223cb66f3.png)

**Comment by David-Goru** [comment]
Fixed in build 731
