### ISSUE TITLE
Character order in "Load game" appears random

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1041]
### Build number

729

### Bug description

When loading a savegame, I got lots of characters with the same name (due to the old saves), and also a few others (one without name containing the very old saves, plus just different names).
They appear to be unordered - it's not alphabetically and not chronologically.
So in order to find my most recent character, I have to check through all of them until I find the right one.

What I expect:
The characters should be sorted...
a) pure chronologically (characters with most recend savegames on top)
or
b) first alphabetically (character names) and then (if name is the same) chronologically

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166342543-57697743-1c0f-485f-affb-61728590cafe.png)

**Comment by jhovgaard** [comment]
Let's go with solution A

**Comment by David-Goru** [comment]
Fixed in build 731
