### ISSUE TITLE
Voogle Maps Freezes when scrolling over 2nd Avenue/ Park Area

### ISSUE THREAD

**Issue by dbrowndevops** [hovgaardgames/bigambitions#1042]
### Build number

Build 728

### Bug description

When using Voogle Maps, the screen freezes over the Park Area near 2nd Avenue 

### Steps to reproduce the bug

1. Open Voggle Maps
2. Using WASD keys to scroll, attemp to move over the area. 
3.  The screen will Freeze. 

### Savegame file

[NewGeorgetteTesterMapBugSave.txt](https://github.com/hovgaardgames/bigambitions/files/8608008/NewGeorgetteTesterMapBugSave.txt)

### Screenshots or videos

![20220502203541_1](https://user-images.githubusercontent.com/54598754/166399619-31641deb-01e5-400e-a66a-8be92ae05ea6.jpg)

**Comment by jokoho48** [comment]
duplicate: https://github.com/hovgaardgames/bigambitions/issues/1029
