### ISSUE TITLE
Cars become ghosts and drive in the wrong direction 

### ISSUE THREAD

**Issue by dbrowndevops** [hovgaardgames/bigambitions#1043]
### Build number

728

### Bug description

Cars near 2nd Avenue become ghosts and drive down the wrong way on the street. 

### Steps to reproduce the bug

Drive in the wrong direction near 2nd Avenue. 

### Savegame file

[NewGeorgetteTesterMapGhostBugSave.txt](https://github.com/hovgaardgames/bigambitions/files/8608118/NewGeorgetteTesterMapGhostBugSave.txt)

### Screenshots or videos

![20220502210926_1](https://user-images.githubusercontent.com/54598754/166400692-94711e1d-4a5f-449f-805c-e6f65447a370.jpg)
![20220502210951_1](https://user-images.githubusercontent.com/54598754/166400693-84f053b3-9f15-40e4-a495-9b749a68d86d.jpg)
![20220502211146_1](https://user-images.githubusercontent.com/54598754/166400694-137904ea-c463-450f-9256-b2ca17daed89.jpg)

**Comment by jhovgaard** [comment]
Fixed in build 730
