### ISSUE TITLE
All lights on traffic lights active

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1044]
### Build number

730

### Bug description

All traffic lights on the intersections of 4th avenue & 5th street, as well as 4th avenue & 6th street are on (as shown in linked image).

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8608427/1st.play.txt)

### Screenshots or videos

![Big Ambitions 3_05_2022 5_45_02 pm](https://user-images.githubusercontent.com/104757675/166409615-e6fcb47a-454a-43d9-8612-accfc4ee7029.png)
![Big Ambitions 3_05_2022 5_41_17 pm](https://user-images.githubusercontent.com/104757675/166409628-421ceee1-ba5a-4f37-98c1-c6c45992548c.png)

**Comment by jhovgaard** [comment]
Fixed in build 730
