### ISSUE TITLE
Player moves when moving an object with WASD

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1045]
### Build number

730

### Bug description

When moving around an object with WASD, player starts moving also.

### Steps to reproduce the bug

Unknown.
I believe it's random when placing an object.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8608545/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166411880-a9bb533c-184c-4de8-9a52-7fe7d4ad4536.mp4

**Comment by jokoho48** [comment]
Fixed in build 730
