### ISSUE TITLE
Warehouse open but no employees

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1046]
### Build number

730

### Bug description

Every time after sleeping, a red box appears with text saying my warehouse is open but there are no employees assigned to the warehouse.

### Steps to reproduce the bug

Unknown

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8609301/1st.play.txt)

### Screenshots or videos

![Big Ambitions 3_05_2022 8_24_08 pm](https://user-images.githubusercontent.com/104757675/166426061-66966c0b-289c-4246-ba03-57c4215bfc82.png)

**Comment by GrayySheep** [comment]
Happens every hour not only after/during sleeping

**Comment by David-Goru** [comment]
Fixed in build 731
