### ISSUE TITLE
Pressing the 2nd & 4th computer (from the left) at Mr Scotts doesn't give anything

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1047]
### Build number

730

### Bug description

When clicking the 2nd & 4th computer from the left in Mr Scotts office supply store I didn't receive a box with a computer.

### Steps to reproduce the bug

Try buying the computers 2nd & 4th from the left inside Mr Scotts office supply store.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8609668/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166433623-72f01e1e-4acf-40dc-afea-7c1f3f072ea7.mp4

**Comment by jokoho48** [comment]
Fixed in build 731
