### ISSUE TITLE
Getting stuck when trying to get Officedesk1

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1048]
### Build number

730

### Bug description

When trying to get an Officedesk1 from below the desks, auto pathing gets stuck when walking between the desks.

Likely solved by adding more space between desks.

### Steps to reproduce the bug

Go below or above the row of Officedesk1's
Click the top or middle desk

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8609692/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166434231-63f69305-0ef3-4471-84a0-360731000262.mp4

**Comment by jokoho48** [comment]
Fixed in build 731
