### ISSUE TITLE
Parked Vehicle on road on 4th street

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1049]
### Build number

730

### Bug description

Driving down 4th street there is a car parked on the road near the 4th street nd 2nd avenue intersection.

### Steps to reproduce the bug

Drive to the point in below image on 4th street

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8613925/1st.play.txt)

### Screenshots or videos

![Big Ambitions 4_05_2022 7_59_32 am](https://user-images.githubusercontent.com/104757675/166556723-74248d32-9f28-45d4-bb73-b2c965377eb6.png)

https://user-images.githubusercontent.com/104757675/166556883-4d693616-edda-4388-8f06-f859a15eb7dd.mp4

**Comment by GrayySheep** [comment]
Silver vehicle at top of intersection in video is the same

**Comment by GrayySheep** [comment]
Build 731**

**Comment by David-Goru** [comment]
Fixed in build 733
