### ISSUE TITLE
Traffic lights on 1st avenue always on

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1050]
### Build number

730

### Bug description

Two traffic lights on first avenue always have all the lights on

### Steps to reproduce the bug

Drive to intersection shown in below image.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8613988/1st.play.txt)

### Screenshots or videos

![Big Ambitions 4_05_2022 8_07_33 am](https://user-images.githubusercontent.com/104757675/166557952-76c67f45-3d09-4fbf-80ce-557d2ed3054f.png)
![Big Ambitions 4_05_2022 8_07_14 am](https://user-images.githubusercontent.com/104757675/166557960-85797a09-2c33-495e-8cbe-f3d0d9ad4981.png)

**Comment by GrayySheep** [comment]
Build 731**

**Comment by GrayySheep** [comment]
Same issue at intersection of 1st avenue and 7th street

**Comment by GrayySheep** [comment]
And at the intersection of 2nd avenue & 6th street *Build 732*

**Comment by jokoho48** [comment]
Fixed in Build 863.
