### ISSUE TITLE
Loading savegames from beta 1 will move them to a new character each and update the timestamp.

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1051]
### Build number

731

### Bug description

Every time you load a beta 1 savegame and go back to the menu (without saving), a new character will be created and the savegame will get a new timestamp shown.
Even if you load 5 savegames from a single old character, it will end up with 5 new, separate characters.

If you just load a pure beta 2 savegame and go back to main menu, the savegame will be kept in the correct character and also the timestamp will stay the old, but the character will move to the top of the list although it might not be the most recent savegame.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/166562716-13c12385-5a1c-400c-bd06-2d6c8e759b26.mp4

**Comment by David-Goru** [comment]
Closing as it may be related to Daniel's infinite list of savegames
