### ISSUE TITLE
Parked car can get spawned inside construction site in front of 3 Third Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1052]
### Build number

731

### Bug description

In front of 3 Third Avenue is a construction site and you can't park your car there, however generated parked cars can spawn in there.

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166565572-846bfb9b-f3fd-4c39-8d5b-3cf811d941ef.png)

**Comment by David-Goru** [comment]
Fixed in build 734
