### ISSUE TITLE
Restaurant message "is out of burgers" disappears the moment I enter the store with boxes of burgers on hand truck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1053]
### Build number

731

### Bug description

The moment I entered the fast food restaurant with a hand truck full of burgers, the message "is out of burgers" disappeared, although the grill was still empty and not yet refilled.

### Savegame file

[Burgerless.json.txt](https://github.com/hovgaardgames/bigambitions/files/8614529/Burgerless.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166573397-3c209f1b-0e0b-43d4-b92d-d930c12dc7b4.png)

**Comment by jhovgaard** [comment]
The solution for this is quite a lot of work. We'll revise this once we have implemented employees physically refilling shelves.

**Comment by David-Goru** [comment]
Fixed in build 897
