### ISSUE TITLE
Hype message for cheap gift still shown on day 20, but green indicator in MarketInsider gone

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1054]
### Build number

731

### Bug description

On day 20, the green indicator for the hype of CheapGift is gone in MarketInsider, but the message about a strong demand is still there.

### Savegame file

[BuyOrNoBuy.json.txt](https://github.com/hovgaardgames/bigambitions/files/8614568/BuyOrNoBuy.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166575050-c9d6d13e-dc63-4b8d-9136-6a5e56d9cda2.png)

**Comment by jhovgaard** [comment]
This is intended :) Hype events are not permanent, instead, they have a limited duration, unknown to the player.
