### ISSUE TITLE
Fence of forest park at the roundabout / 4th Avenue can be walked into

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1055]
### Build number

731

### Bug description

It's possible to walk into the fence around the large forest park, at the corner of 4th Avenue and the roundabout.

### Savegame file

[KeepMePosted.json.txt](https://github.com/hovgaardgames/bigambitions/files/8614588/KeepMePosted.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166578138-89630f35-33e6-4a59-a607-615909b8afa5.png)

**Comment by jokoho48** [comment]
Fixed in Build 864
