### ISSUE TITLE
Impression of "looking into the window" broken due to what seems to be a changing picture

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1057]
### Build number

731

### Bug description

Building: 3 Fourth Street (might be related to the high windows)

When walking away from the building, you can see the window picture moving upwards and something else coming in from the bottom.

### Savegame file

[WindowPeeking.json.txt](https://github.com/hovgaardgames/bigambitions/files/8615899/WindowPeeking.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/166584214-eb259960-2820-47ff-89f7-680e47ded4b4.mp4

**Comment by David-Goru** [comment]
Fixed in build 734
