### ISSUE TITLE
Car Acrobatics possible at the elevated part of 2nd Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1058]
### Build number

731

### Bug description

If you go up onto the elevated part of 2nd Avenue and drive into the guardrail, the car does funny things and eventually even turns onto its side. You don't need high speed for that.

### Savegame file

[CarCircus.json.txt](https://github.com/hovgaardgames/bigambitions/files/8616755/CarCircus.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/166584593-f1eab0fe-8435-4f23-a7b8-0d7d86655170.mp4

**Comment by jhovgaard** [comment]
Fixed in build 733
