### ISSUE TITLE
Car can drive through outer railguard on circular road around Central Station, leaving the car stuck at the edge and effectively unusable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1059]
### Build number

731

### Bug description

While you can't drive through the railguard of the elevated access road to Central Station, you can do that on the circular road around the station, I managed to get my car stuck just on the edge where I can't get it away anymore (unless I get another car and push it down maybe...).

### Savegame file

[CarSuicide.json.txt](https://github.com/hovgaardgames/bigambitions/files/8616767/CarSuicide.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/166585242-1266bf58-46cc-4981-8588-84eb94dd26c9.png)

**Comment by Gerwanese** [comment]
Just adding here, as it can probably be fixed in one go:
The inner railguard can also be driven through.
![grafik](https://user-images.githubusercontent.com/17579552/166585676-54e45720-cdd5-4b63-b315-5f4a70518c06.png)

**Comment by David-Goru** [comment]
Fixed in build 733
