### ISSUE TITLE
Floor texture bug at 3rd Street No. 3, 5, 7

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#106]
Build 49

Buildings 3, 5 and 7 in 3rd Street have flickering floor textures.
The corner building (doesn't have any overlay, but would be No. 1) as a colored floor at the corner part which is not flickering but permanent.
![grafik](https://user-images.githubusercontent.com/17579552/120250396-40935f80-c27e-11eb-9e44-a5e51d1f5cea.png)

https://user-images.githubusercontent.com/17579552/120250429-63257880-c27e-11eb-996d-7a8c0766a993.mp4

**Comment by David-Goru** [comment]
Fixed in the past
