### ISSUE TITLE
No confirmation anymore when overwriting savegame

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1061]
### Build number

731

### Bug description

I saved the game, entering a savegame name that I already used a day ago. The old savegame was overwritten without any confirmation.
My expectation would be that the confirmation dialog is always shown when entering an old savegame name, while when pressing CTRL+S the most recent save is overwritten automatically.

**Comment by David-Goru** [comment]
Fixed in build 733
