### ISSUE TITLE
Hand Truck Spawner is Inactive

### ISSUE THREAD

**Issue by dbrowndevops** [hovgaardgames/bigambitions#1062]
### Build number

731

### Bug description

Hand Truck Couldn't Spawn in Gift Shop. Development Console Automatically Opened with a NullReferenceException: Object reference not set to an instance of an object. 
Corountine couldn't be started becase the the game object 'HandTruckSpawner' is inactive. 

### Steps to reproduce the bug

Create a Gift Shop walk out and back in and the Developer Console Automatically opens. 

### Savegame file

[HandTruckCouldn'tSpawnPlayer.txt](https://github.com/hovgaardgames/bigambitions/files/8617357/HandTruckCouldn.tSpawnPlayer.txt)
[New Georgette Tester Save GameBUG.txt](https://github.com/hovgaardgames/bigambitions/files/8617360/New.Georgette.Tester.Save.GameBUG.txt)

### Screenshots or videos

![20220503184322_1](https://user-images.githubusercontent.com/54598754/166609496-c6020397-466c-4711-be50-def00e6eeead.jpg)
![20220503184332_1](https://user-images.githubusercontent.com/54598754/166609500-6b6f0f62-d846-4c74-9559-0e0a0eb0596d.jpg)

**Comment by David-Goru** [comment]
Fixed in build 733
