### ISSUE TITLE
Employees aren't automatically assigned to business

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1063]
### Build number

732

### Bug description

When hiring employees they don't display in the business's schedule. Instead you have to go into the MyEmployees tab and assign them to a business.

### Steps to reproduce the bug

Call Anderson Recruitment Corp. and search for employees for a business. Hire an employee. Look under the businesses schedule tab (Employee is not there).

Go to MyEmployees tab. Find the newly hired employee. MyEmployees tab shows they are assigned to a business until you click on them.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8618043/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166627226-f1f3bc72-7c65-4a86-ad1e-03c9eb0ab149.mp4

**Comment by David-Goru** [comment]
Fixed in build 733
