### ISSUE TITLE
Packing then replacing a drinks fridge fully restocks it.

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1064]
### Build number

732

### Bug description

If you pack a drinks fridge into a box, place it down, pick it back up, then place it again, it is refilled with soda for free.

### Steps to reproduce the bug

Pack a drinks fridge, place it down, pick it back up, then place it again.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8619062/1st.play.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/104757675/166654338-8e29e948-eea5-4650-a48f-d9b5cf15e10e.mp4

**Comment by David-Goru** [comment]
Fixed in build 733
