### ISSUE TITLE
Can't deliver soda to coffee shop using warehouse and truck

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1065]
### Build number

732

### Bug description

You can't (where I believe you should be able to) deliver soda to your coffee shops using logistics manager even though you can sell soda at coffee shop.

### Steps to reproduce the bug

Use logistics manager to try deliver soda to coffee shop.

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8619113/1st.play.txt)

### Screenshots or videos

![Big Ambitions 4_05_2022 9_20_59 pm](https://user-images.githubusercontent.com/104757675/166655112-2f214a8f-2fc8-4080-a548-3eec9a570cd6.png)

**Comment by David-Goru** [comment]
Fixed in build 733
