### ISSUE TITLE
Information stuck on screen

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1066]
### Build number

732

### Bug description

Randomly after sleeping a bunch of information like my money +-, sick employees, day summary, etc. gets stuck on screen.

### Steps to reproduce the bug

Unknown

### Savegame file

[1st play.txt](https://github.com/hovgaardgames/bigambitions/files/8619161/1st.play.txt)

### Screenshots or videos

![Big Ambitions 4_05_2022 9_29_35 pm](https://user-images.githubusercontent.com/104757675/166656516-c768f891-5d2f-446c-9903-bcb44d1359d6.png)

https://user-images.githubusercontent.com/104757675/166657051-7470bbc2-1e6e-44a6-9619-0fcabac6c8f6.mp4

**Comment by GrayySheep** [comment]
Started happening around day 194/195

**Comment by GrayySheep** [comment]
Attempted opening BizMan after sleeping. Game crashed. After restarting game no longer happening

**Comment by David-Goru** [comment]
Restarting the game seems to fix it, yes. Probably it was due to an unrelated error that break the game (https://github.com/hovgaardgames/bigambitions/issues/1067 should be related too). If that happens again, please attach the Player.log

Closing for now
