### ISSUE TITLE
Saved games not appearing

### ISSUE THREAD

**Issue by GrayySheep** [hovgaardgames/bigambitions#1068]
### Build number

733

### Bug description

After closing game then reopening it, saved games are not visible and cannot continue previous save.

Saved games are still in SaveGames folder.

### Steps to reproduce the bug

I believe just close game & reopen.

### Savegame file

[Recover #2.txt](https://github.com/hovgaardgames/bigambitions/files/8629830/Recover.2.txt)

Most recent save game before closing game.

### Screenshots or videos

![Big Ambitions 5_05_2022 8_43_53 pm](https://user-images.githubusercontent.com/104757675/166891182-c8e7c0c0-468d-4517-b672-0bee52733419.png)
![Big Ambitions 5_05_2022 8_43_44 pm](https://user-images.githubusercontent.com/104757675/166891192-084f9746-250a-47e9-9d44-2af69e041259.png)

**Comment by David-Goru** [comment]
Deleting the Recover #2 savegame should let you load the games again

**Comment by GrayySheep** [comment]
Ok yeah that worked
