### ISSUE TITLE
Still on Beta 1 Build 614

### ISSUE THREAD

**Issue by Decimes** [hovgaardgames/bigambitions#1069]
### Build number

614

### Bug description

Hi,

Not as much a bug but was just wondering and couldn't find a answer or a alternative (email) to post this.
I am still on Beta 1 - Build 614. Is this correct as being the latest version we should be testing? Or am I doing something wrong and do I need to do something? I was wondering because I see bug reports here from people trying out Beta 2 and build 7xx.

So sorry to bother you in what must be busy times for you. Normally when starting the game it would automatically go to newer versions.  Therefor most likely nothing is wrong and I just have to wait a bit longer, which I gladly will. Just wanted to check if I didn't need to do something more myself.

Keep up the good work!!

**Comment by David-Goru** [comment]
Hi! Beta 2 hasn't been released still. Bug reports are from some early testers

**Comment by Decimes** [comment]
Thanks David!!

Sorry to take up some of your time. Good to know, I was starting to doubt myself.

Have a good day!
