### ISSUE TITLE
Dev Console Opens Automatically When Starting NEW Game

### ISSUE THREAD

**Issue by dbrowndevops** [hovgaardgames/bigambitions#1070]
### Build number

733

### Bug description

Dev Console Opens Automatically When Starting the Game with the following error: "CityBuildingController with Duplicated Address: 10 6th Street"

### Steps to reproduce the bug

Start a new game. 

### Savegame file
[New Susie #1 Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8635586/New.Susie.1.Save.Game.txt)

_No response_

### Screenshots or videos

![20220505133345_1](https://user-images.githubusercontent.com/54598754/167012914-56471a77-8e2e-49bd-b908-b63375acb3d4.jpg)

**Comment by jokoho48** [comment]
Already Fixed in Build 734.
