### ISSUE TITLE
Tutorial obejctive: Buy soda cans

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#1075]
https://forum.bigambitionsgame.com/t/box-of-soda-cans-objective/1135

>Small thing here.
>
>If you’ve gotten ahead of the objective list when you get to the “Soda” section, it still requires you to purchase a new case of Soda, even if you have a few cases in your storage shelves.

**Comment by David-Goru** [comment]
Fixed in build 738
