### ISSUE TITLE
Storing a stack of storageshelves on a storage shelf

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#1078]
https://forum.bigambitionsgame.com/t/storing-a-stack-of-storageshelves-on-a-storage-shelf/1151
![image](https://user-images.githubusercontent.com/1388347/167392763-2742e12b-766a-43cc-9428-c186ccffacf4.png)

**Comment by David-Goru** [comment]
Fixed in build 740
