### ISSUE TITLE
Illegal parking becomes legal if you enter the car again

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1083]
### Build number

740

### Bug description

If you park your car somewhere illegally and then enter it again, the parking spot becomes legal.

### Savegame file

[LegalIllegalScheissegal.json.txt](https://github.com/hovgaardgames/bigambitions/files/8673651/LegalIllegalScheissegal.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/167953741-25607d79-36ea-4060-88fb-bd1f837d3e1c.mp4

**Comment by David-Goru** [comment]
Fixed in build 742
