### ISSUE TITLE
Moving any Furniture after first entering the Starter Apartment causes Softlock.

### ISSUE THREAD

**Issue by Captaindub242** [hovgaardgames/bigambitions#1084]
### Build number

742

### Bug description

Hello. Picking up and moving any object in the starting apartment after entering (before sleeping), causes a softlock that makes it so you are unable to select any object or progress the game. In console this creates a Null Reference Point error that repeats what i can assume is every game tick. I was also able to cause this softlock twice before entering the apartment, however I have been unable to consistently replicate that specific instance of the bug.

### Steps to reproduce the bug

- Enter starter apartment
- right click to move furniture
- place furniture
- soft-locked.

### Savegame file

[New test Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8684088/New.test.Save.Game.txt)

### Screenshots or videos

https://www.veed.io/view/186e4d78-8072-4dc8-8d92-00f2dc441708

Video is unlisted. Was too large to embed directly.

**Comment by David-Goru** [comment]
Fixed in build 745
