### ISSUE TITLE
Cannot Use Hand Cart

### ISSUE THREAD

**Issue by ashoudy** [hovgaardgames/bigambitions#1085]
### Build number

744

### Bug description

I started a new save game for the latest build, the first thing I noticed is if  I pick up the fridge and replace it I cannot access it again without reloading, if I leave my apartment after doing this I cannot click on any buildings.  I also cannot use the handcart, I click on it once and my character goes to it but doesn't use it like before. I cannot click it a second time after this and it also makes buildings unselectable.  I was able to replicate this behavior on my other computer which was a fresh install of the game and a new save. I did submit a bug report in-game as well.

### Steps to reproduce the bug

Start a new game, buy the fridge and place it then pick it up.  Try and use a handcart in any store.

**Comment by David-Goru** [comment]
Fixed in build 745
