### ISSUE TITLE
Hand truck (including content) becomes unusable when leaving the building

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1087]
### Build number

748

### Bug description

If you leave the building with a hand truck, the hand truck will become invisible. The player still shows the "holding position" and the cargo dialog is shown, but you can't park the hand truck.
If you enter a building again, it becomes visible.

If items are loaded onto the hand truck, it happens as well. The items show in the cargo dialog but are invisible.

You can enter the car this way, but nothing will be loaded (effectively losing your items). If you park the car again, the player will get out still showing the "holding hand truck position" but this time without cargo dialog. You can pick up new items, proving that the hand truck and its previously loaded items are lost.

Taking single boxes out of a building works, so the issue is only with the hand truck.

### Savegame file

[HandTruckMagic.json.txt](https://github.com/hovgaardgames/bigambitions/files/8695445/HandTruckMagic.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/168484516-d87e9c09-fb28-478f-a5b4-d31b1d7e583c.mp4

**Comment by David-Goru** [comment]
Fixed in build 749
