### ISSUE TITLE
Destination marker not updated when renaming business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1089]
### Build number

748

### Bug description

When renaming a business that has a destination marker already set, the marker is not updated and will continue showing the old name.
The same appears to be true for "Upcoming Tasks", see https://forum.bigambitionsgame.com/t/shop-names-dont-update-on-alerts-navigation/1178

### Savegame file

[UnchangedDestiny.json.txt](https://github.com/hovgaardgames/bigambitions/files/8695558/UnchangedDestiny.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/168485866-95f94613-6d6e-44a2-a4df-ff99ecc03b97.mp4

**Comment by David-Goru** [comment]
Fixed in build 750
