### ISSUE TITLE
No rent paid (or at least shown) for business after takeover

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1090]
### Build number

748

### Bug description

If you buy a business from a competitor, the rent will be $0.00 in BizMan. This won't change even after multiple days.

### Savegame file

[FreeRent.json.txt](https://github.com/hovgaardgames/bigambitions/files/8695573/FreeRent.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/168486189-80c1d9f0-c377-46df-86c0-115708627fa6.mp4

**Comment by David-Goru** [comment]
Fixed in build 750
