### ISSUE TITLE
Sleeping possible in illegally parked car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1091]
### Build number

748

### Bug description

Previously, the bug marking an illegally parked car legal by parking and entering it has been fixed:
https://github.com/hovgaardgames/bigambitions/issues/1083

However, even though it's now correctly shown as "illegal" after entering the car again, you can still sleep in the car and won't get a parking ticket during your sleeping time.

### Savegame file

[SoooSleepy.json.txt](https://github.com/hovgaardgames/bigambitions/files/8695583/SoooSleepy.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/168486415-5ccb89e1-8019-4f3c-ae0d-9eb944ad6f37.mp4

**Comment by David-Goru** [comment]
Fixed in build 750
