### ISSUE TITLE
Take over new store issues

### ISSUE THREAD

**Issue by Odybvik** [hovgaardgames/bigambitions#1094]
### Build number

749

### Bug description

Bought/take over a clothing store that was already in operation. But you can not put in new things. When you try to place, it will not settle on the floor. I have to go to the menu to get it fixed. By pressing Esc. I got saved and went to menu. Then there was a cleaning station in the back room, but if I try to move it, it's the same problem.

The ShoppingBasket is in the Logistics manager meny for delevery. 

### Steps to reproduce the bug

Try to set a new item i the store. The same if you try move somthing already in the store. Se screenshot. The store "Just jeans". Bought it for 1,7 million.

### Savegame file

Save game sendt from the game.

### Screenshots or videos

![22 mai 2022 10-07-20](https://user-images.githubusercontent.com/106010330/169687886-bcba8887-6b6a-4067-8bcf-b518bb0c4cd2.png)
![22 mai 2022 10-06-29](https://user-images.githubusercontent.com/106010330/169687901-ae449fa3-c91c-4a43-b79e-9980f80d8f95.png)
![22 mai 2022 09-36-43](https://user-images.githubusercontent.com/106010330/169687908-3fd826a4-83bf-4b34-a7d8-cf1587d8a9f6.png)

**Comment by David-Goru** [comment]
Fixed in build 751

The "The ShoppingBasket is in the Logistics manager menu for delevery" error will be fixed in build 754
