### ISSUE TITLE
after i new mintuer i always need to relaod

### ISSUE THREAD

**Issue by sorenvalen** [hovgaardgames/bigambitions#1095]
### Build number

754

### Bug description

after some time buildings become unenterable or interactable in the game

### Steps to reproduce the bug

yes but it does take some time palying though the save

### Savegame file

[New soren Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8839549/New.soren.Save.Game.txt)

### Screenshots or videos

i am really bad at showing off bug on youtube it better if you see it for yourself it should happened every new minute if you paly normally i did have steam overlay on i dont know if it a issue with that but i it a steam default setting that the only setting that i know it same specific some game work better to turn it of
[New soren Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8839551/New.soren.Save.Game.txt)
f

**Comment by David-Goru** [comment]
Fixed in build 869
