### ISSUE TITLE
879: Not able to take out large loan

### ISSUE THREAD

**Issue by Chh2tx** [hovgaardgames/bigambitions#1097]
### Build number

879

### Bug description

Tried to take out a $40,000 loan with Jensen Capital, advised the bank cannot handle a loan amount of more than $40,000 per client and to seek out a larger bank. I have no other loan with this bank currently (previously paid off old one), only a $30000 loan from Vantandar Bank.

Appears it's either a) 'remembering' the loan I paid off in not issuing new ones b) declining the loan for reasons other than what's stated aka DTI ratio, or c) the loan cap is global and not per bank?

B and/or C can somewhat make sense given lending isn't infinite due to debt to income ratios, but the decline reason isn't clear if that's the case.

### Steps to reproduce the bug

Had an intial loan with Jensen Capitalas part of turtorial. Paid it off early.

Later opened a loan of $30,000 with Vantander bank to open a new store.

Tried to take out a $40,000 loan with Jensen Capital, and denied saying they can't loan more than $40,000 and to try other banks despite not having any other loans with this bank.

### Savegame file

[gamesave.txt](https://github.com/hovgaardgames/bigambitions/files/8881813/gamesave.txt)

**Comment by David-Goru** [comment]
Fixed in beta 4
