### ISSUE TITLE
Backwards Large Building Sign

### ISSUE THREAD

**Issue by Chh2tx** [hovgaardgames/bigambitions#1098]
### Build number

881

### Bug description

Low Priority, visual bug: Large Sign at corner of First and Broadway displays backwards.

### Steps to reproduce the bug

Drive to 1st and Broadway and observe.

### Screenshots or videos

![backwardsign](https://user-images.githubusercontent.com/47042057/173214898-25a74b27-c998-42ef-b310-9f1dbdf26172.PNG)

**Comment by David-Goru** [comment]
Fixed in build 892
