### ISSUE TITLE
Translation dosent work on text marketing

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#1100]
### Build number

882

### Bug description

Text error

### Screenshots or videos

![image](https://user-images.githubusercontent.com/58218237/173436081-860e9722-abc8-4126-be08-761b05900109.png)
![image](https://user-images.githubusercontent.com/58218237/173436110-42711bbf-e5e8-45ec-9900-f4e83599b976.png)

**Comment by David-Goru** [comment]
Fixed in build 884
