### ISSUE TITLE
[Linux] Text placeholders are visible

### ISSUE THREAD

**Issue by BeeBee1234567891** [hovgaardgames/bigambitions#1101]
### Build number

Unknown. Steam reports the build ID as 8926496

### Bug description

The game displays text placeholders instead of what they're supposed to show

### Steps to reproduce the bug

Install game from Steam
Run Linux version

### Savegame file

N/A

### Screenshots or videos

![image](https://user-images.githubusercontent.com/33805937/173456416-f149326c-3a72-4e8d-a998-5c2fd9396225.png)
![image](https://user-images.githubusercontent.com/33805937/173456552-e4ca4e44-1988-466c-8b4d-3083c4a94d5c.png)

**Comment by David-Goru** [comment]
Fixed in build 890
