### ISSUE TITLE
Shop Capacity is capped at the lowest item in the store

### ISSUE THREAD

**Issue by Enzo-Tech** [hovgaardgames/bigambitions#1103]
### Build number

886

### Bug description

Hi Jonas/Team

On my save game, the clothing store maximum capacity seems to be directly linked to the lowest item in the store. eg. I had a store with a 15 capacity and 8 clothing rails. I had 1 of each type of clothing in the store. Because of this, my max capacity was capped at 10. 

However, if I remove everything apart from 1 type of clothing from the rails, the capacity is increased. In my screenshots (which i've labelled) i've show how it changes the maximum capacity when changing the items in the store. 

### Steps to reproduce the bug

I think the above is quite thorough, but if you make a shop with 2 rails of different clothing, the capacity per hour will be 10. If you have 2 of the same single type of clothing, the capacity will be 20 (obviously unless the building capacity itself is 15)

### Savegame file

![New Elliott Armitage Save Game](https://user-images.githubusercontent.com/107579619/173900935-1d6873ea-5be1-4c39-be99-8d1d4ad5f649.jpg)

### Screenshots or videos

![1 of every clothing type](https://user-images.githubusercontent.com/107579619/173902563-1cf91d32-5532-4fd9-9141-7b5201e25f33.PNG)

![still capped despite have 3 rails of same outfit](https://user-images.githubusercontent.com/107579619/173902577-cbcb7b56-abe1-4501-9aff-6b4c1decaeaa.PNG)

![only 1 type of rail and now building capacity is the limiting factor](https://user-images.githubusercontent.com/107579619/173902593-bc6f17b6-55d0-4295-b14b-6fe5dc0f99d6.PNG)

**Comment by jhovgaard** [comment]
Hi there,

This is actually by design. The product type with the lowest capacity, will be the overall limit, as we want players to evenly distribute their product shelves.

There has been a lot of conversation on this on our forums, but it's a complex matter. If you have a better suggestion on how to put the system together, I recommend submitting it on the feature suggestions section here:
