### ISSUE TITLE
Translation error

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#1106]
### Build number

888

### Bug description

Translation error in game 

### Screenshots or videos

![Capture1](https://user-images.githubusercontent.com/58218237/174296269-2f938cf7-50e7-4a9e-a281-df697e0c3582.PNG)
![Capture](https://user-images.githubusercontent.com/58218237/174296272-9377a4c8-4d54-4ef9-b3fe-084367bb54b7.PNG)

**Comment by David-Goru** [comment]
Fixed in build 889
