### ISSUE TITLE
Cash register can only be picked up by right-clicking the lower area of it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1110]
### Build number

891

### Bug description

When you try to pick up a cash register using right click, only a click on the lower area of it (the "buttons" of the cash register) works. If you click on the upper area (where the display is), it doesn't work.

### Savegame file

[Build891-PickupLine.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/8933942/Build891-PickupLine.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/174447221-103368e0-1650-4a59-a39b-b080f83734c5.mp4

**Comment by David-Goru** [comment]
Fixed in build 892
