### ISSUE TITLE
Ilegal illogical parking

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#1111]
### Build number

891

### Bug description

the parking space is not very logical

### Screenshots or videos

https://user-images.githubusercontent.com/58218237/174448376-b2397f13-89a4-422a-bfdf-c6bb0c3ccc94.mp4

![image](https://user-images.githubusercontent.com/58218237/174448439-9b3780a8-cec8-4c56-91c4-928044c729e4.png)

**Comment by Gerwanese** [comment]
Same issue as bug #142, but different location.
I guess we should do a complete check of parking zones.

**Comment by David-Goru** [comment]
Fixed in build 1012
