### ISSUE TITLE
Opening settings while holding a box for placement will break item and further placement

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1114]
### Build number

891

### Bug description

When holding a box for placement (in my case the fridge) and then opening the menu via ESC, opening the settings and closing them via ESC, the item in your hands will be broken. You can't do anything with it except selling it for $0.
Even after selling it, if you pick up anything else (I emptied the existing fridge), the new item in your hands can't be placed as well.

### Savegame file

[FunkyNumbers.json.txt](https://github.com/hovgaardgames/bigambitions/files/8943174/FunkyNumbers.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/174666286-5ac5690e-62b6-4fed-95c8-261c78aca554.mp4

**Comment by David-Goru** [comment]
Fixed in build 892
