### ISSUE TITLE
No reaction when clicking on a bench while holding a paper bag

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1116]
### Build number

891

### Bug description

If you click on a bench while holding a paper bag. there's no reaction.
If sleeping is not allowed with the paper bag, there should at least be a warning message about that, as players currently don't understand it and think it's a bug with benches in general.

### Savegame file

[Build891-RestUnderPaperBag.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/8944635/Build891-RestUnderPaperBag.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/174688948-5b43b5c0-e76f-4b00-9e42-3f8daef335a7.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1014
