### ISSUE TITLE
After paying in the drive-in wholesales, car cargo will show 0/6

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1118]
### Build number

891

### Bug description

After you pay in the drive-in wholesales, the car's cargo will immediately change to "0/6".
If I park the car inside the building and enter it again, for a short moment I'll see "4/6" before it changes to "0/6" again.
Outdoors it will be fixed once I park and enter the car again.

### Savegame file

[Build891-CarGo.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/8944772/Build891-CarGo.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/174691529-f6d5558d-75e4-4f9f-ad97-213a0ace42d8.mp4

**Comment by David-Goru** [comment]
Fixed in build 892
