### ISSUE TITLE
sometimes impossible to enter a building

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#1119]
### Build number

891

### Bug description

difficulty getting to 4 3rd avenue
as soon as I have a handtruck in my hands

### Steps to reproduce the bug

grab handtruck and enter inside 

### Screenshots or videos

https://user-images.githubusercontent.com/58218237/174700236-d5ad3dc4-164e-49c9-9d71-046359c7f8d6.mp4

**Comment by David-Goru** [comment]
Fixed in build 892
