### ISSUE TITLE
Double "entrance" overlay for Drive-In Wholesales when in car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1122]
### Build number

894

### Bug description

When inside the car, the drive-in wholesales shows two entrance overlays - the big one for the car and a smaller one for walking entrance. The latter one shouldn't be shown.
Ideally, disable all "walking" entrance overlays when inside a car, so they also don't show up when driving by houses.

### Savegame file

[Build891-CarGo.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9033848/Build891-CarGo.hsg.txt)

### Screenshots or videos

![2022-07-03 01_22_05-Big Ambitions](https://user-images.githubusercontent.com/17579552/177018851-88b92320-6f67-4abc-b8e8-facc5acb29f8.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 1014
