### ISSUE TITLE
Fast Food Restaurant: When moving grills, dirt gets still generated at their old locations

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1124]
### Build number

894

### Bug description

If you move the positions of grills (possibly also other items) of a restaurant after they have been in use already, even after moving the dirt will still get generated at the old location.

### Savegame file

[Build894-FastFood.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9033877/Build894-FastFood.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/177020256-426fe0fb-9ede-4282-ba91-e2be8f7af333.mp4

**Comment by jokoho48** [comment]
Fixed in Beta 4
