### ISSUE TITLE
Objective "Assign to cash register" fulfilled with wrong assignment

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1127]
### Build number

894

### Bug description

The objective "Assign the employee to the cash register" is fulfilled even if you assign the employee to a cleaning station instead.
This can result in new players not detecting the wrong assignment.

### Savegame file

[Build894-AssignWrongWorkplace.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9033934/Build894-AssignWrongWorkplace.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/177021097-663cbd01-e151-4738-a3b2-cc4634849cfd.mp4

**Comment by David-Goru** [comment]
Fixed in build 1014
