### ISSUE TITLE
Industrial Fryer doesn't get restocked automatically

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1128]
### Build number

895

### Bug description

The Industrial Fryer doesn't get restocked automatically although I still got 1200 fries on the shelves. All other containers get properly reloaded it seems.

### Savegame file

[Build894-FastFoodSlowRestock.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9042093/Build894-FastFoodSlowRestock.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/177218448-f73569ac-7912-4c31-ad74-20ccc8da05ac.mp4

**Comment by David-Goru** [comment]
Fixed in build 1013
