### ISSUE TITLE
Pizza Oven missing in help system

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1129]
### Build number

895

### Bug description

The Pizza Oven is missing in the help system. There's no entry in the furniture category, and when I click on the pizza oven in pizza's description, nothing will happen.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/177219454-3330b9b0-df99-49f4-a91b-05f24b860722.mp4

**Comment by David-Goru** [comment]
Fixed in build 1014
