### ISSUE TITLE
Illegally legal parking at 5th Str / 3rd ½ Ave

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1130]
### Build number

895

### Bug description

Cars can park at the crossing of 5th Street / 3rd ½ Avenue, along the side of 5th Street.

### Savegame file

[Build895-ParkiePark.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9042285/Build895-ParkiePark.hsg.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/177224109-85de4b1a-be96-4aec-8a17-a33c87e12b06.png)

**Comment by David-Goru** [comment]
Fixed in build 1012
