### ISSUE TITLE
Ordering food at a restaurant while holding a hand truck results in holding a paper bag with the hand truck's items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1131]
### Build number

895

### Bug description

I went into a restaurant with a hand truck carrying 2 boxes of cheap gift. Then I ordered a salad.
Now I'm holding a paperbag with 2 boxes of cheap gifts, while the salad (which I paid for) and the hand truck (which I stole) seem to be gone.

### Savegame file

[Build895-MergeConflict.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9042331/Build895-MergeConflict.hsg.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/177225438-11266814-66d3-43ba-9ef8-5a415ca043b0.png)

**Comment by Gerwanese** [comment]
After taking one box of cheap gifts from the paper bag and carrying it over to my shop next door, when I came back to the restaurant I could pick up the hand truck with the remaining box of cheap gifts, so the issue was temporary.

**Comment by David-Goru** [comment]
Fixed in build 1014
