### ISSUE TITLE
"Next delivery" not updated in purchasing agent screen after failed delivery

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1134]
### Build number

897

### Bug description

After an import delivery was cancelled due to insufficient funds, the "next delivery" date wasn't updated.
Only after closing and opening the screen a second time, the correct day appeared.

### Steps to reproduce the bug

1. Set up a regularly scheduled delivery (mine was "every 3 days")
2. Make sure you don't have enough money for the next delivery
3. After getting the message about the failed delivery, open the purchasing agent screen

### Savegame file

[Build897-TooBrokeToUpdateDay.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9079455/Build897-TooBrokeToUpdateDay.hsg.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/178153842-da3b753d-46c7-4d18-86c4-5fa917f71d2c.png)

**Comment by David-Goru** [comment]
Fixed in build 1014
