### ISSUE TITLE
Missing localization when import order is below minimum amount

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1135]
### Build number

897

### Bug description

If your import order is below the minimum required amount, the resulting error message is missing localization.

### Savegame file

[Build897-RichyRich.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9116677/Build897-RichyRich.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179121149-b357aa28-d6b9-44fc-af0c-ecbdf5abbba2.mp4

**Comment by David-Goru** [comment]
Fixed in build 1010
