### ISSUE TITLE
Wrong button label for selecting business type when starting a new business (COMMON_SEELCT)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1153]
### Build number

1006

### Bug description

https://feedback.hovgaard.com/report/a0006074-d44c-462e-a268-d9d8242eaa8c

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/179354849-6f3eb74b-198f-4bad-a04e-b7a95032df17.png)

**Comment by David-Goru** [comment]
Fixed in build 1009
