### ISSUE TITLE
Can't completely stop the car anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#116]
Build 49

I can temporarily stop the car using the handbrake but immediately after releasing it the car will start rolling again.
In the video I do nothing except for pressing and releasing Ctrl, the whole rolling happens by itself.

https://user-images.githubusercontent.com/17579552/120253720-6a518400-c288-11eb-8d29-f51e874cd8f5.mp4

**Comment by jhovgaard** [comment]
Will be fixed once we switch away from the temporary car controller.

**Comment by jokoho48** [comment]
fixed in the mean while
