### ISSUE TITLE
Opening self-owned, not self-used office or retail building will show Overview tab instead of Real Estate

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1163]
### Build number

1006

### Bug description

https://feedback.hovgaard.com/report/7f1cb677-913e-4db2-9aa3-1245311f0939

Might be the same as or at least related to #1160

### Steps to reproduce the bug

Examples:
34 1st Avenue (retail, empty)
4 5th Street (office, Joko Tech)

**Comment by jhovgaard** [comment]
Fixed in build 1009
