### ISSUE TITLE
"Owned building" icons have higher priority in Voogle Maps than own businesses / rented apartments

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1165]
### Build number

1006

### Bug description

https://feedback.hovgaard.com/report/093df726-d5a6-44f1-8c80-092e597e96c9

Suggestion: Show the regular business/apartment icon with a key, and have an additional "side icon" (just like the key) indicating it's self-owned.

**Comment by David-Goru** [comment]
Fixed in build 1009

I followed your suggestion
