### ISSUE TITLE
Some texts in phone apps unreadable due to missing contrast to background

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1171]
### Build number

1006

### Bug description

https://feedback.hovgaard.com/report/af36e8c4-a7b3-4913-bf1b-01405dc81cc7

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/179359551-a5d71e7f-47bf-4601-b5ba-8ca4a0433658.png)

**Comment by jhovgaard** [comment]
Fixed in build 1009

We need to do this manually on every label, so if you experience more, please report those too :)
