### ISSUE TITLE
"Sell" and "Discard" buttons not working for Jerry Can and all other items

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1173]
### Build number

1006

### Bug description

https://feedback.hovgaard.com/report/ae7ca5bb-d7a1-4fe8-8438-22f0f6b67aab

**Comment by Gerwanese** [comment]
This does not only affect the Jerry Can, but generally all items - Selling and Discarding doesn't work anymore.

**Comment by David-Goru** [comment]
Fixed in build 1009
