### ISSUE TITLE
Entering Drive-In wholesales not possible anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1182]
### Build number

1008

### Bug description

https://feedback.hovgaard.com/report/76bd2322-d2be-4e0f-a191-66c74615fe50

Doesn't work by car and by foot.

**Comment by Gerwanese** [comment]
It's specifically the drive-in wholesales that's completely broken. Neither shortcut E nor clicking manually does work, neither by foot nor driving.

**Comment by David-Goru** [comment]
Fixed in build 1009
