### ISSUE TITLE
Player is stuck. After pausing and reporting the bug that "E" shortcut is not working, even after unpausing I cannot move anymore.

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1183]
### Build number

1008

### Bug description

https://feedback.hovgaard.com/report/5e3c451d-0cf0-4f5b-bc4f-08df0b9ac08b

**Comment by Gerwanese** [comment]
This is actually game breaking, as even savegame doesn't load anymore
[Player.log](https://github.com/hovgaardgames/bigambitions/files/9128359/Player.log)
.

**Comment by Gerwanese** [comment]
This might be just the same issue as #1182, but I leave it open in case I'm wrong and it's two different bugs.
The moment you click on the drive-in building in order to enter it, you're stuck.

**Comment by David-Goru** [comment]
Fixed in build 1009
