### ISSUE TITLE
It is possible to drive into the truck at the "world border" at Murray Hill harbor

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1189]
### Build number

1009

### Bug description

https://feedback.hovgaard.com/report/934bf210-26b5-4aa2-9a4d-07e92f10345f

**Comment by Gerwanese** [comment]
At the right angle, you can even break through the barrier:

https://user-images.githubusercontent.com/17579552/179616944-c5ef88f9-96d6-4915-a6d3-cb8f7747a52d.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1011
