### ISSUE TITLE
The building with the globe in front is "-1 STREETNAME_UNDEFINED"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1191]
### Build number

1009

### Bug description

https://feedback.hovgaard.com/report/b63f3016-01af-4764-ab94-f204f5e86439

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/179620275-9b0cf0e4-d140-459d-b4e0-58366acb1a79.png)

**Comment by jhovgaard** [comment]
Fixed in build 1011
