### ISSUE TITLE
Floating surroundings in front of building with world globe

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1192]
### Build number

1009

### Bug description

Depending on the viewing angle, you can sometimes see that there should be some kind of elevated terrace but it's just sometimes shown and not physically there.
Additionally, when you drive there and leave the car, the car UI will disappear but you're still in the car.

https://feedback.hovgaard.com/report/ff2e477d-f7d1-434f-bfb7-501ebf4c3159

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179620835-2b1aa66a-acf9-4643-b035-4a4b37ddcc70.mp4

**Comment by Gerwanese** [comment]
Issue with leaving the car reported separately as #1195 because it's not limited to this building.

**Comment by jokoho48** [comment]
Fixed in Build 1011
