### ISSUE TITLE
"Park Vehicle" button not always correctly updating between active/inactive

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1193]
### Build number

1009

### Bug description

Sometimes after you enter the car it's still shown active, while sometimes after coming to a standstill it's still shown inactive.
The first thing (staying active) seems to happen especially when I immediately start driving a circle after entering the car (turning left, although that probably doesn't matter).

https://feedback.hovgaard.com/report/080e4e6f-61d5-4420-97bd-ad8c9d1bc193

**Comment by jhovgaard** [comment]
I can't reproduce this. Maybe caused by cascading errors from yesterdays build. Please test in Build 1011 @Gerwanese
