### ISSUE TITLE
Getting out of the car at the gas station leaves you inside and outside at the same time

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1195]
### Build number

1009

### Bug description

Same happens at the building with the world globe if you drive into it. So must be depending on the "ground type".

https://feedback.hovgaard.com/report/47b64128-3643-46e4-85c1-e3b3de2b021d

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179623755-5649a305-bdf2-416f-9cf8-2d947ade1a92.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1010
