### ISSUE TITLE
Imports arrive at 0:00 but Import Agent screen still shows 12:00

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1197]
### Build number

1009

### Bug description

https://feedback.hovgaard.com/report/a62c8e17-0a71-4bd5-a5ea-6351b6bd5970

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/179625203-018f0937-1444-4a3c-84da-ec6b6840647f.png)

**Comment by David-Goru** [comment]
Fixed in build 1010
