### ISSUE TITLE
"Dragging cursor" in BizMan schedule changes to normal while dragging

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1199]
### Build number

1009

### Bug description

Once you start dragging, it changes back to normal cursor. If you move the employee over another draggable item (moving over another employee or a time slot), the draggable cursor shows again.

https://feedback.hovgaard.com/report/4fa63f86-b858-4a85-ae55-acbc3f8817a4

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179627091-f1696991-e299-475e-8a68-1170ca527a07.mp4

**Comment by David-Goru** [comment]
Fixed in build 1011
