### ISSUE TITLE
Valencia chair and ottoman can be attached to desk without working properly

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1203]
### Build number

1009

### Bug description

The ottoman will just be attached without fulfilling the "chair" requirement (which makes the connection pretty useless).
The Valencia chair behaves similar, but when attaching it to the table it will be marked red as illegal. It's still possible to attach it though. Once attached, you can pick up the whole table-chair combination but can't place it anymore because it will always be seen as illegal.

https://feedback.hovgaard.com/report/8e446c07-0351-4160-b461-0d7f96b1cf87

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179629775-5b87b61a-03fc-4d24-9ff9-cf7a912de045.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1011
