### ISSUE TITLE
Subway not working anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1209]
### Build number

1009

### Bug description

After entering the station, I will get Voogle Maps but clicking any station doesn't do anything at all.
Might be related to the fix for taking the subway while the game is paused, because the game is always temporarily paused while the map is open - so you only have to stop the subway ride if game was paused already before opening the map (or alternatively, automatically unpause the game for the subway ride).

https://feedback.hovgaard.com/report/da374d66-d16f-4b32-8aee-1bc2275244a3

**Comment by jokoho48** [comment]
Fixed in Build 1010
