### ISSUE TITLE
Broken "sidewalk" visible through IKA walls (+weird door in the wall)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1212]
### Build number

1009

### Bug description

https://feedback.hovgaard.com/report/ecd002cb-10f3-4def-a4c9-d7456241b6c6

**Comment by jokoho48** [comment]
low Prio as this issue is as old as the Border Buildings were there.

**Comment by David-Goru** [comment]
Fixed in beta 9
