### ISSUE TITLE
Could not enter HQ, now stuck between HQ and Outdoors it seems

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1214]
### Build number

1009

### Bug description

Maybe it's related to the HQ being closed, as I entered it earlier already without problems.
I clicked to enter it while holding a box, but nothing happened. I noticed that afterwards I was walking slowly outdoors (just as usually indoors).
I could place the box back into the car's trunk but can't enter the car anymore.

https://feedback.hovgaard.com/report/d5522fba-599b-4e78-90fd-c213fee0d0ac

**Comment by Gerwanese** [comment]
It's not the opening times, even later on it didn't work.

**Comment by Gerwanese** [comment]
Probably something more broken:
![grafik](https://user-images.githubusercontent.com/17579552/179636975-3cf1e7fc-3c56-423f-9936-33b7e6852279.png)

**Comment by David-Goru** [comment]
This was due to a cascade error that happened when trying to enter the drive-in
