### ISSUE TITLE
Reloading savegame while in car starts with hospitalization, leaves me in weird state

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1215]
### Build number

1009

### Bug description

I'm somewhat in the car, but moving with arrow keys shows weird effects.
I was sleeping a lot in the car before saving, so I shouldn't even have ended in hospital.
The savegame I loaded is attached here.

https://feedback.hovgaard.com/report/23de14f9-6fa4-4a27-acb6-be9a4165a256

### Savegame file

[Repo.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9136400/Repo.hsg.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/179637446-13bc4f70-1bec-456f-8374-720a445b34d5.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1010
