### ISSUE TITLE
Tax issues

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1216]
### Build number

1009

### Bug description

- Paying the tax is due 0:00 on the last day, although it says within the day
- Extended period is due 24:00 of the last day (end of day), as expected
- When not paying the tax, you don't get any info what they took instead; I'm not even sure they're taking anything at all. IF they do, there should be a message telling me what it was; ideally it should somewhat be reflected in EconoView shop data (if they take products from the shop, it should be shown as a resource minus)

https://feedback.hovgaard.com/report/ec34bdc3-c2fa-45ce-9f77-ec54b4e9a0c1

**Comment by David-Goru** [comment]
Fixed in build 1011
