### ISSUE TITLE
Does not save the game or with can read the saved files MAC OS

### ISSUE THREAD

**Issue by LeonardoAppItalia** [hovgaardgames/bigambitions#1218]
### Build number

can see a build number, submit a homepage screenshot

### Bug description

does not save the game or with can read the saved files.
in the game it seems that it saves correctly, but after in the main menu there is no saved file and the continue button does not work either

### Steps to reproduce the bug

save game

### Savegame file

[1331550.txt](https://github.com/hovgaardgames/bigambitions/files/9143287/1331550.txt)
[1648860.txt](https://github.com/hovgaardgames/bigambitions/files/9143288/1648860.txt)

### Screenshots or videos

![20220719190713_1](https://user-images.githubusercontent.com/101968381/179809441-88d50c34-c7e0-48ca-b585-a7acc818bd7b.jpg)
![20220719190713_1](https://user-images.githubusercontent.com/101968381/179810933-32eba2af-7606-4071-aa57-36c10ef4f514.jpg)

**Comment by Gerwanese** [comment]
@LeonardoAppItalia Can you tell us the specification of your Mac? Is it a M1 or Intel?

**Comment by Rastavibs** [comment]
Hello @LeonardoAppItalia, 
I had the same problem on my side on a Mac M1, I have a solution without keeping your backups:
> Uninstall Big Ambitions
> Go to the folder /Users/(your_user_account)/Library/Application Support/com.HovgaardGames.BigAmbitions/SavesGames
> Empty the content (Maybe at this step you can try to copy the backup folder(s) to paste them again later)
> Launch the game and enjoy ;)

**Comment by LeonardoAppItalia** [comment]
> Player.log

my mac is m1, in the directory "Application support" I don't have a directory "Hovgaard Game" but "com.HovgaardGames.BigAmbitions". in the directory i can's see a Player.log file

**Comment by LeonardoAppItalia** [comment]
> Hello @LeonardoAppItalia, I had the same problem on my side on a Mac M1, I have a solution without keeping your backups:
> 
> > Uninstall Big Ambitions
> > Go to the folder /Users/(your_user_account)/Library/Application Support/com.HovgaardGames.BigAmbitions/SavesGames
> > Empty the content (Maybe at this step you can try to copy the backup folder(s) to paste them again later)
> > Launch the game and enjoy ;)

TY Bro, to worked for me. i think the problem came when from demo version i upgraded to beta version
