### ISSUE TITLE
Boxes still displayed on hand truck after "autoloading" them to shelves by selecting item type on shelves

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#1220]
### Build number

896

### Bug description

When coming into a store with boxes on a handtruck, then selecting those items in the combobox of an empty shelf, the items will automatically be loaded on the shelf but the box still stays on the hand truck.
In the end, one box can still be placed somewhere on the floor (although without usable content).

https://discord.com/channels/176778356069629952/752566908179578931/999308927189663815

**Comment by David-Goru** [comment]
Fixed in build 1012
