### ISSUE TITLE
Total of Real estate income on Econoview same as Businesses income

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1221]
### Build number

1013

### Bug description

Total of Real estate income on Econoview same as Businesses income

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180283294-d76094a0-4471-41cc-9728-4156e162f2f7.png)

**Comment by David-Goru** [comment]
Fixed in build 1014
