### ISSUE TITLE
Wages of lawyers and programmers are not in touch with the hour price you can ask!

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1222]
### Build number

1013

### Bug description

Employing lawyers or programmers cost x2 or x3 as much as you can ask for the hours... It's a losing business

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180283489-67752109-be12-4645-a232-e7e3bf3938d9.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180283513-7514f6a7-25a6-4c1c-a772-d363ae7123d7.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180283568-6208f8da-d375-45b2-bd51-3084fb7192f2.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180283607-8d85656c-ba37-43e9-9432-bd1c4957a2f6.png)

**Comment by David-Goru** [comment]
Fixed in build 1028
