### ISSUE TITLE
When buying a BIMA 320 the colour you buy isn't the one you end up with sometimes

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1223]
### Build number

1013

### Bug description

When buying a BIMA 320 the colour you buy isn't the one you end up with sometimes

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180286662-6c81f610-98a4-4606-9ba2-9f28b6aec302.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180286694-97cd7361-0a25-45d9-b292-8b180d5b0ddd.png)

**Comment by jokoho48** [comment]
Fixed in Build 1014
