### ISSUE TITLE
EconoView doesn't give a day detail when you click on real estate

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1226]
### Build number

1013

### Bug description

When you click a real estate building it doesn't give you a detailed like earned in rent yesterday xxx amount. Also no 'open in bizzman' to adjust rent prices or set the building for sale. 2nd screenshot how it is for retail business. 

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180296152-dc13657b-e18d-42a2-b92e-08eaa1b7acb4.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180296309-9287a786-6933-4909-91c0-5a9f2c18b97d.png)

**Comment by David-Goru** [comment]
Fixed in build 1014

Clicking on the address will now open BizMan Real Estate Settings. Not having a detailed view (like for businesses) is on purpose, as the only info is the daily rent.
