### ISSUE TITLE
When buying a previously owned warehouse it deleted the vehicles inside of it and can't re-add the vehicle back

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1227]
### Build number

1013

### Bug description

I had 2 trucks in this warehouse and when I purchased the building it ereased the trucks. First time you entered it was also completly empty but a re-enter put the shelves back. Also appears that I can't add a new truck in the slot as apperently it still recognizes it?

EDIT:Actually the truck also dissappeared in my not owned warehouse? This might be an additional or different bug and not related to the purchase of the building? 

### Steps to reproduce the bug

Own a warehouse, put vehicles in the slots and purchase it. 

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180324840-b2a94ef2-5efa-41e6-80de-028f6dd5d28a.png)

**Comment by David-Goru** [comment]
It was probably due to a cascade error. Shouldn't happen again on build 1014
