### ISSUE TITLE
Bank loan max is 800k but interest get calculated in that amount so only can take +/- 660k

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1228]
### Build number

1015

### Bug description

Bank loan max is 800k but interest get calculated in that amount so only can take +/- 660k

### Steps to reproduce the bug

![afbeelding](https://user-images.githubusercontent.com/9866863/180609454-15a9992a-5cce-4971-b157-83703681f7c3.png)

**Comment by David-Goru** [comment]
Fixed in build 1020
