### ISSUE TITLE
No localisation when you want to a already assigned driver to another driver slot

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1229]
### Build number

1015

### Bug description

No localisation when you want to a already assigned driver to another driver slot

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180612300-f8285f7b-dcdd-4190-a7fa-5003c65edfca.png)

**Comment by David-Goru** [comment]
Fixed in build 1019
