### ISSUE TITLE
Marketinsider - real estate - m2 metres of the total building isn't mentioned?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1232]
### Build number

1015

### Bug description

Marketinside - real estate - m2 metres of the total building isn't mentioned?

I mean in the end, it's one of the key factors how much total m2 of a building you can rent out. Something key like that should be shown in the overview really. 

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180612841-b3557733-a446-4626-a7fe-c30f700e1bc0.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180612905-65c3efe7-63cb-4c37-9310-2d2cbe7bd415.png)

**Comment by David-Goru** [comment]
It's displayed in the "Type and size" column

**Comment by rpgforyou** [comment]
Fixed build 1029 or so.
