### ISSUE TITLE
Truck parked like a moron, but apperently I can sleep and skip through time? 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1233]
### Build number

1015

### Bug description

Truck parked like a moron, but apperently I can sleep and skip through time? 

### Steps to reproduce the bug

Park like an idiot in front of your warehouse entry point. 

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180621042-0bd66146-a4bd-4119-b796-4ed736e058f1.png)

**Comment by jokoho48** [comment]
cant reproduce
