### ISSUE TITLE
Can drive through barriers into the water, chance of falling through the world and be forever forgotten!!!

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1235]
### Build number

1015

### Bug description

Can drive through barriers into the water, chance of falling through the world and be forever forgotten!!!

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180622871-d7759963-d3b4-4665-a00e-1d85b242d5a2.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180622880-7281a308-2dfb-4311-8bc1-477401dccea4.png)

**Comment by jokoho48** [comment]
Fixed in Build 1020
