### ISSUE TITLE
Don't get a new TAX bill, the 60 day period isn't correct.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1236]
### Build number

1015

### Bug description

377-436 was first taxed period.
So now it should have been 437-496 but I didn't receive any new taxation from IRS ... and I'm on day 506 ...

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180623125-14bf4239-a316-4b4a-b07f-200313a0e461.png)

**Comment by David-Goru** [comment]
Fixed in build 1018
