### ISSUE TITLE
3 - 7th street = is a residential building with the layout of commercial

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1238]
### Build number

1015

### Bug description

3 - 7th street = is a residential building with the layout of commercial

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180641875-fad51fdb-4660-452c-bdf8-d97a118662f3.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180641879-e310db4d-ce7d-489a-9cab-8a4e79627bd7.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180641899-225ca97b-5b55-46f8-a5b4-138cc1efbcf4.png)

**Comment by David-Goru** [comment]
Fixed in build 1019
