### ISSUE TITLE
Luxconcept store: customers are complaining of items that aren't present

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1239]
### Build number

1015

### Bug description

Customers are complaining of items that aren't present. They come for coffee tables, chairs, office chairs ... it's simply not a choice in that store so ... might need to adjust that looks bit weird. :)

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180642198-bacd13b0-ec43-47d0-8501-b42fb4272512.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642164-b56767ad-26ac-4f38-a48d-f77030a5fdd8.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642172-8a98c118-7328-4438-9236-229a410a2b52.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642177-57902bb1-0fb3-495c-a76a-02c80e5c0d9f.png)

**Comment by David-Goru** [comment]
Fixed in beta 5
