### ISSUE TITLE
BizMan overview, can't sort on status Open/closed or xx%

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1240]
### Build number

1015

### Bug description

BizMan overview, can't sort on status Open/closed or xx%

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180642388-a6f39412-9ee6-45d0-ac22-b814b1b4d29e.png)

**Comment by David-Goru** [comment]
Fixed in build 1019
