### ISSUE TITLE
BizMan sorting on satisfaction takes - value higher as 50 % value?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1241]
### Build number

1015

### Bug description

My retail store that doesn't have any business in it with satisfaction - is one place higher then satisfaction of 50 %? 

### Screenshots or videos
![afbeelding](https://user-images.githubusercontent.com/9866863/180642580-848d1aa0-2e6a-412d-86fe-6535aa7c7793.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642522-8a49e837-8ac2-4eb8-a117-b19735cba2fa.png)

**Comment by David-Goru** [comment]
Can't reproduce
![imagen](https://user-images.githubusercontent.com/50799541/180947340-394005f9-4a86-486e-8271-6a6c4f5b0d17.png)
