### ISSUE TITLE
Hospital bugs an QOL

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1242]
### Build number

1015

### Bug description

- Building is not clickable on the map. 
- There is also no filter on it for the map like for example with the IRS building. 
- You pay $ 2K in hospital fee's, could be more interactive through the cellphone system like it's done with IRS? Like a doctors bill, cause I can imagine in the beginning this might come as a shock you're suddently 2K down and if you didn't see the -2K drop or checked your econoview you complete missed out the 'WHY'... In future could even be enhanced further like if you have a hard crash with your car an ambulance could come and bring you down to the hospital with a higher bill. ;)

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180642686-e63d9086-da8f-4d2a-9767-372a36a466de.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642719-a061203d-4bfd-475b-80cc-7da32413f7b5.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180642745-4be41d1d-cbf8-4b40-bfd1-5484313c217a.png)

**Comment by David-Goru** [comment]
Fixed in build 1580

Building is clickable, added a Hospital filter to City Map. The rest is for a bigger update :P
