### ISSUE TITLE
NY autotow service : 'spelling' mistake when you call him when you aren't in a car.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1243]
### Build number

1015

### Bug description

Please, seat on the vehicle? Very weird sentence... needs some rewriting.

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180642969-d5d34675-a8fd-4b87-9907-c4f5cd661ccf.png)

**Comment by David-Goru** [comment]
Fixed in build 1019
