### ISSUE TITLE
Gasstation repair your human body?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1244]
### Build number

1015

### Bug description

Uhm? I can repair myself? When clicked on it doesn't do anything, but it's weird it shows up and even indicates a price...

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180643095-7c67ccf9-3127-40e9-9b20-e140a43cc475.png)

**Comment by jokoho48** [comment]
Fixed in Build 1018
