### ISSUE TITLE
Gasstation Bizzman business type not defined and description is same as ika

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1246]
### Build number

1015

### Bug description

Gasstation Bizzman business type not defined and description is same as ika. (No furniture to be seen. ;) )

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180644610-62d21803-a4cf-4aa1-af43-427a4e6cc6df.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
