### ISSUE TITLE
New furniture not mentioned in the help menu

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1247]
### Build number

1015

### Bug description

New furniture not mentioned in the help menu

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180645825-49938bd6-66c5-4d80-a0d7-e6548b9bf5fd.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180645848-39e50070-66f5-45bc-ac16-c133665c0362.png)

**Comment by David-Goru** [comment]
Fixed in build 1019

Added office chair 2. The Valencia chair doesn't work as a chair for the workstation (is just visual)
