### ISSUE TITLE
IRS lied, company tax is not 10 % it is more +/- 25 %

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1249]
### Build number

1015

### Bug description

IRS lied, company tax is not 10 % it is 25 %

12.955.010,00
+2.369.444,00
-1.121.000,00
=14.203.454,00
+/- x 25 %
= 3.550.863,50 / so close to 25 % not 10 %

Also why does it deduct my cars it repo'ed before the actual tax calculation? I know these seizures happend cause I didn't pay my earlier tax claim in time. But the deductible expenses should deduct from my tax total! Not from the base where it calculates the tax on. How is it fair to lose 1M in vehicle value to receive a 250K in tax reduction?

ALSO
The timing is off? 377-436 was my first tax period, now the second one I receive is 481-540? What happend to 437-480?

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180663355-50939d2c-2cba-4eac-9d32-b731b2ba8caf.png)

**Comment by David-Goru** [comment]
Fixed in build 1019

We have added more details regarding where tax percentage is used (in this case, tax deductible expenses and businesses revenues)
