### ISSUE TITLE
my front porch has kidnapped me (13,2nd avenue)

### ISSUE THREAD

**Issue by Endryxffs** [hovgaardgames/bigambitions#1250]
### Build number

1015

### Bug description

I just wanted to get out of my flat after skipping a days sleeping in it, and uhm, my porch is simply refusing to let me leave, I can see the street but I'm basically bugged in the building 

### Steps to reproduce the bug

Get in the flat at that adress, sleep a bit, be kidnapped 

### Screenshots or videos

![Buggybug](https://user-images.githubusercontent.com/109922335/180664487-04c50dfb-6071-4947-be9e-d3fb7cb80ec0.png)

**Comment by jokoho48** [comment]
Fixed in Build 1018
