### ISSUE TITLE
Passed out when working on the register, brought to hospital but can't unassign nor save/exit game

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1251]
### Build number

1016

### Bug description

Passed out when working on the register, brought towards the hospital but can't unassign nor save/exit game. (Or atleast it doesn't show the confirmed it's saved dialog.)

UPDATE: It did not save when clicked on the button. #RIP progress

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180781583-f81201e7-6df6-4402-bb87-844dc90c96fb.png)

**Comment by jokoho48** [comment]
Fixed in Build 1018
