### ISSUE TITLE
MyEmployees : Sorting on Task or current Business is not alphabetical

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1252]
### Build number

1018

### Bug description

MyEmployees : Sorting on Task or current Business is not alphabetical
Has to do with the not assigned or no task, that doesn't get sorted correctly from A > Z or Z > A.

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/180968705-846c1a59-5830-4316-949f-4c6c9d6050b9.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/180968857-c3884a82-1bab-45c8-b9f9-a110a5705878.png)

**Comment by David-Goru** [comment]
That's on purpose, so employees without assigned task are either at the end or at the start of the list, so it's easier to find all the employees without task assigned without scrolling. Same with no business
