### ISSUE TITLE
Where do the trucks go for repairs?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1254]
### Build number

1023

### Bug description

Where do the trucks go for repairs, like the car shop don't work. You don't receive easily damage with the truck, but you do expierence like the steering wheel is pulling to a side cause of the damage. And well you can't fix it anywhere? Or can you?

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/181295109-fe5949d8-87a0-4b9e-aabc-8bb3872e2dea.png)
Denied service :(

**Comment by David-Goru** [comment]
Fixed in beta 6
