### ISSUE TITLE
1 9 th street has 0 m2 and - occupancy

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1255]
### Build number

1024

### Bug description

1 9 th street has 0 m2 and - occupancy see pictures

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/181297046-43943b1c-5d81-4103-8660-1de106785aae.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/181297067-0d033b61-8e46-4f67-abb2-08087ecf9b1a.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/181297103-c79d7d34-e805-4b78-9ee6-efad961c4912.png)

**Comment by jhovgaard** [comment]
Fixed in build 1025 (removed all unused addresses).
