### ISSUE TITLE
When changing business type it wipes the complete shedule of opening hours and assigned employees

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1257]
### Build number

1025

### Bug description

When changing business type it wipes the complete shedule of opening hours and assigned employees

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/181512263-682c7ebb-6c9c-46e5-9248-bd71973e9fbd.png)

**Comment by David-Goru** [comment]
Fixed in build 1028
