### ISSUE TITLE
Incorrect Prices for Deliveries of Fresh Food, Frozen Food, and Bottle of Wine

### ISSUE THREAD

**Issue by SlipMage** [hovgaardgames/bigambitions#1261]
### Build number

1031

### Bug description

The prices are wrong for Fresh Food, Frozen Food, and Bottle of Wine past the first box, eg 2-8. 

For example the total prices for 8 boxes of Fresh food shows 900 in game but should be 904 since 113 * 8 = 904 from the NY Distro Inc, same applies for Metro Wholesale just 138 * 8 = 1104 but displays 1100. This applies for Frozen food and Bottle of Wine as well. Frozen food shows 396 which should be 400 and Bottle of Wine shows 1044 and should be 1048.

Not sure if it's just a display bug or a math bug but thought I'd let you guys know.

The rest of the Goods are correct as is, it is just these three that I have found to be incorrect.

### Screenshots or videos

![babugreport1](https://user-images.githubusercontent.com/203756/182040152-648c9b7b-300e-430a-9d1b-4b0702b9a16a.png)
![babugreport2](https://user-images.githubusercontent.com/203756/182040154-e1a3d648-6b82-425c-b094-3a941ae23fc0.png)

**Comment by David-Goru** [comment]
Fixed in build 1033

That's due to some prices having decimals. We'll be displaying the whole price for the items:
![imagen](https://user-images.githubusercontent.com/50799541/182116807-06fbd193-8993-4991-9fc4-a7eae4970451.png)
