### ISSUE TITLE
Closest gas station? Not really ...

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1263]
### Build number

1032

### Bug description

Was on Broadway called Autotow. 

First avenue was like 2 blocks up, so very close.
Yet i brought me all the way up to the station at 5th avenue?

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/182131525-89e6027b-6d9e-47a9-92d1-5a17732d9ae1.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/182131622-f4a80485-15c2-48d1-8c31-7508d503241d.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/182131716-4663221a-daea-464e-b31d-4563042869f3.png)

**Comment by jokoho48** [comment]
Fixed in Build 1038.
