### ISSUE TITLE
Calling NY AutoTOW services when you are inside of the drive in Wholesaler NY Distro INC

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1265]
### Build number

1035

### Bug description

Calling NY AutoTOW services when you are inside of the drive in Wholesaler NY Distro INC

![afbeelding](https://user-images.githubusercontent.com/9866863/182871210-7a7c5edc-be32-4bd2-8738-466741700572.png)

I get teleported to the closest gas-station,  I repair or fill up the car. Park it on the street and go to sleep. But it comes up with this.
![afbeelding](https://user-images.githubusercontent.com/9866863/182871449-ac21039a-8ee4-46f6-b621-b8ec7b33f23d.png)

Once you get out of the vehicle you can't cross roads anymore and are just stuck on the pavement/zebracrossings.
![afbeelding](https://user-images.githubusercontent.com/9866863/182872156-299dcef5-63f0-4680-be2c-26bedd7d9a05.png)

So then you save game, go back to menu and reload the save game and you end up at the wholesaler not at the gas station where I saved initially.

![afbeelding](https://user-images.githubusercontent.com/9866863/182872522-fc25165f-1b5b-4f7e-8485-11bde15cdf4f.png)

So when I go back to my vehicles parked at the gasstation, they aren't marked on Voogle as mine.
![afbeelding](https://user-images.githubusercontent.com/9866863/182872884-21517f48-0a79-48be-a6c0-f45a21b4b404.png)

And when I go there, I can't interact with the vehicle.
![afbeelding](https://user-images.githubusercontent.com/9866863/182873067-4a0427ea-9369-49fc-ba61-e5a195c2c155.png)

**Comment by jokoho48** [comment]
Fixed in Build 1038.
