### ISSUE TITLE
Interior designer allows moving/placing of objects

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1267]
### Build number

1037

### Bug description

Interior designer allows moving/placing of objects

### Steps to reproduce the bug

Go into any of your own stores.

Grab a box in your hands click interior designer and will come with following message:
![afbeelding](https://user-images.githubusercontent.com/9866863/183512576-9f27cb01-0c97-4ffd-974a-f1e704975d18.png)

All good so far...

Now place that item, but don't actually place it. Then click interior designer and boom you are allowed to place/move items while you are on the interior designer. 
![afbeelding](https://user-images.githubusercontent.com/9866863/183513148-050e52a2-19f7-4215-b58e-85db55fd1ba2.png)

When you normally click the interior designer you can't pick up any items or move them around.

**Comment by David-Goru** [comment]
Fixed in build 1148
