### ISSUE TITLE
Price satisfaction not in line with customer feedback

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1268]
### Build number

1037

### Bug description

Price satisfaction not in line with customer feedback.
They are saying all my items are way overpriced and they are not gone buy it. Yet my sales are through the roof and the price satisfaction is at 99 % for this store? 

uhmm... what?

These customers count I get, do not represent the income I get from this store... like not at all. 
![afbeelding](https://user-images.githubusercontent.com/9866863/183524353-92869e3b-a59e-4cab-9d21-d076777477fe.png)

### Screenshots or videos

![afbeelding](https://user-images.githubusercontent.com/9866863/183522883-8f430816-9223-45f6-9a0f-510b597e1c98.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/183522916-1078eb83-d77e-47e1-85ef-d816035b0406.png)

**Comment by David-Goru** [comment]
Can you attach a savegame please?

**Comment by rpgforyou** [comment]
Send an ingame bug report with it, should received it. :)

**Comment by David-Goru** [comment]
Hello! Savegame received. You're selling most of the stuff, so I wouldn't say this is a bug.

For more info: in that big shop, you're selling almost 8000 items per day. Most of the items have good prices. Expensive clothing (and some soda cans IIRC) are more expensive than they should, so _some_ customers are not buying them, thus the customers complaints. But those complaints are more or less the 1% missing on your pricing satisfaction :P

**Comment by rpgforyou** [comment]
This is definably not working as it should! 

I sent you another save game(spare you the drive/walk) of me being in a smaller store, where the price satisfaction is 100 %! and they complain on the prices on all the products I sell?

![afbeelding](https://user-images.githubusercontent.com/9866863/183873809-4626782c-a383-480e-8460-6cf9dbcec9f9.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/183873920-ddc47dc8-661f-4141-bc88-829a380ee681.png)

**Comment by David-Goru** [comment]
Fixed in build 1042
