### ISSUE TITLE
Missing Localisation for custom color picker 'Add button' for store logo

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1270]
### Build number

1037

### Bug description

Missing Localisation for custom color picker 'Add button' for store logo
![afbeelding](https://user-images.githubusercontent.com/9866863/183639724-3af62e6f-0b97-49e6-9ca3-5e014e78b841.png)

**Comment by David-Goru** [comment]
Fixed in build 1141
