### ISSUE TITLE
Help system and all whats wrong/incomplete with it. 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1271]
### Build number

1037

### 1# General
**1.1** Happiness doesn't mention how to get increased happiness. Lots of people wonder or ask how you increase happiness so this should be covered!

### **2# Business Types**
**2.1** Florist item list isn't like under eachother but next to eachother.
![afbeelding](https://user-images.githubusercontent.com/9866863/183643178-abbf5308-0247-469d-ac29-c784202c58eb.png)

**2.2** Clothing store, has all 8 types of clothing, but they aren't linked to their 'item page' mainly because they don't have an item page ...

**2.3** Headquarters,

It requires a desktop workstation yet it isn't mentioned like it's mentioned for web devs and Law firm:
![afbeelding](https://user-images.githubusercontent.com/9866863/183644210-45bf4d38-d327-4f31-956f-e7b69247da0d.png)

![afbeelding](https://user-images.githubusercontent.com/9866863/183644044-412ba98d-235f-48bb-8cc9-891fa1088202.png)

### **3# Sellable Products**

**3.1** Cheap Gift
- This product is imported by JetCargo Imports but also by United Ocean Import.

**3.2** Expensive Gift
- Metro Wholesale doesn't sell these.
- This product is no longer imported by JetCargo Imports but only by United Ocean Import.

**3.3** Cheap Jewelry
- Metro Wholesale doesn't sell these.
- This product is imported by JetCargo Imports but also by United Ocean Import.

**3.4** Expensive Jewelry
- This product is no longer imported by JetCargo Imports but only by United Ocean Import.

**3.5** Hotdog
- Metro Wholesale also sells these.

**3.6** Cigar
- This product is no longer imported by JetCargo Imports but only by United Ocean Import.

**3.7** Bottle of Wine
- This product is no longer imported by JetCargo Imports but only by United Ocean Import.

**3.8** Cheap Flower
- This product is imported by JetCargo Imports but also by United Ocean Import.
- The spacing between the blue linkes item/store/importer isn't spaced like the other items.
![afbeelding](https://user-images.githubusercontent.com/9866863/183647402-c08e0eff-8b65-4e05-b2df-920b00e3051c.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/183647422-ee698609-f6bc-4dd4-bcc6-34e33979c9fa.png)

**3.9** Expensive Flower
- This product is no longer imported by JetCargo Imports but only by United Ocean Import.
- The spacing between the blue linkes item/store/importer isn't spaced like the other items.
![afbeelding](https://user-images.githubusercontent.com/9866863/183647402-c08e0eff-8b65-4e05-b2df-920b00e3051c.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/183647422-ee698609-f6bc-4dd4-bcc6-34e33979c9fa.png)

**3.10** No mention of the cheap/expensive modern/classic clothing items at all!

### 4# Furniture

**4.1** Rounded Shelf

- Cheap flower & Expensive flower can now also be used on the shelf.

**4.2** Cash Register

- Why Employee station is in italic I have no idea, but it reads annoying, underline it if you feel like it.
![afbeelding](https://user-images.githubusercontent.com/9866863/183648148-27cc0db4-9b1c-4143-97af-c0696282bca7.png)

**4.3** Clothing rack

- It links to all 8 types of clothing, but these don't have an item page.

**4.4** Checkout Counter
- Why Employee station is in italic I have no idea, but it reads annoying, underline it if you feel like it.
- Register has 20 c/h, Checkout counter is 30c/h. How is this a 33% increase per hour to a cash register? Seems like a 50 % compared to a cash register. You're doing the math in the other direction =wrongly.

**4.5** Cleaning Station
- Why Employee station is in italic I have no idea, but it reads annoying, underline it if you feel like it.

**4.6** Chair
- Stump Mesh Office Chair isn't mentioned unless you mean office chair type 2 by that?
- Stump Mesh Office chair is also not purchasable at Scott's store, but at Luxconcept store. This isn't mentioned as a location though.

### 5# Employees tab

Should be expanded with the different professions/jobs.

Why? Well for example drivers with low % skill can't drive a truck but this is mentioned nowhere? For the purchase agent the skill level will increase their negotiation position in pricing, this is somewhat logic but should be mentioned also.

**Comment by David-Goru** [comment]
Fixed in build 1141

Regarding the use of italic, we'll keep them for now. The "employee station" text will probably be linked in the future, and underline will make it even harder to read.

Thank you very much for this report! It really made it easier to do those small fixes
