### ISSUE TITLE
Random store prices aren't using decimals but prices aren't rounded so... wrong impression is given.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1272]
### Build number

1037

### Bug description

Random store prices aren't using decimals but prices aren't rounded so... wrong impression.

3 + 3 + 3 = 9 not 10 ... so some decimal prices aren't shown I assume. :)

![afbeelding](https://user-images.githubusercontent.com/9866863/183652714-0aa5b15c-7a8c-4c26-9672-09b46b9f1a5d.png)

**Comment by jokoho48** [comment]
Fixed in Build 1247
