### ISSUE TITLE
Press ALT and it shows me icons from my store I have been into and they are interactable

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1275]
### Build number

1040

### Bug description

Press ALT and it shows me icons from my store I have been into and they are interactable, they shouldn't be there.

![afbeelding](https://user-images.githubusercontent.com/9866863/184159052-c79e2b27-383e-4da8-aad8-41ddcff6bfa3.png)

**Comment by David-Goru** [comment]
Fixed in beta 6
