### ISSUE TITLE
Price when sending a purchase offer to a building not for sale displays wrong value

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1276]
### Build number

1040

### Bug description

Price when sending a purchase offer to a building not for sale displays wrong value:

When you go to marketinsider you have always 3 buildings for sale mostly.
![afbeelding](https://user-images.githubusercontent.com/9866863/184167124-b60f9431-035a-4c96-ac72-182eacf31872.png)

Now when I want to purchase a building outside of those that are marked as for sale.

![afbeelding](https://user-images.githubusercontent.com/9866863/184167298-d4f3c7cc-b603-457b-96d0-cdc0a131fa9a.png)

I put in 0, sent offer it gets declined and I cancel it. 

![afbeelding](https://user-images.githubusercontent.com/9866863/184167396-690e0c36-e284-46b4-afe7-30011a438e63.png)

It then suddently shows me 29m as the price instead of the 22m?

That price was the price of 1 of the 3 buildings offered for sale on the Hell's Kitchen district? Not sure if this helps to narrow down the issue.

![afbeelding](https://user-images.githubusercontent.com/9866863/184167890-91626dad-83c1-4819-b0a7-b2597795b411.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
