### ISSUE TITLE
Price/m2 formatting when more then a million is cut off @ Real Estate Market Insider

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1277]
### Build number

1040

### Bug description

Price/m2 formatting when more then a million is cut off
![afbeelding](https://user-images.githubusercontent.com/9866863/184532932-e74d0f72-0fa0-4dd3-9d67-6f905e2e9a75.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
