### ISSUE TITLE
Rent management could use a seperate description and not string: bizman_insight_promotion_description

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1278]
### Build number

1040

### Bug description

Rent management could use a seperate description and not string: bizman_insight_promotion_description:

Promotion indicates how many customers your business attracts.
There is no such promotion for rent, and calling renters customers well ... although not wrong it doesn't sound the greatest.

Something like:
"Adjusting rent price could impact your earnings but also the % of occupancy of your building."
![afbeelding](https://user-images.githubusercontent.com/9866863/184533059-1ab1d6e1-5a8b-4198-9d10-b7e50f1a5538.png)

And a small 'quick' QOL: (Like the % potential gain when sold)
Add some colour indication like < 33 % red, <50 % orange < 75 % yellow =< 100 % green
![afbeelding](https://user-images.githubusercontent.com/9866863/184533158-732b3d88-b6ae-4539-85f6-64a125c389c1.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
