### ISSUE TITLE
Store descriptions

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1279]
### Build number

1040

### Bug description

Since we are coming to a more refined stage with next beta, including some confirmed businesses. Might aswell fix the description messages to make it all polished. Low prio but might aswell when you have some time over. 

This overview might help you guys idk ... (I know the description aren't linked and depended on the building I pressed before.)

IRS: 
![afbeelding](https://user-images.githubusercontent.com/9866863/184534560-9491063d-d94f-435b-8c10-050beb2ac39a.png)

Luxconcept:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535162-fdc210ca-c06d-4e98-83d5-3dbfb39358f7.png)

Manhattan Luxury Cars:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535202-b7455ad9-a796-4a44-9f60-4b75477e77b2.png)

Blue Stone Imports:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535222-74e07ccd-7c53-43ab-8eac-09ba8a95c932.png)

United Ocean Imports:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535229-6bf678b5-54ce-41cd-9b9e-ce9e00dfbac2.png)

The Green Salad:
![afbeelding](https://user-images.githubusercontent.com/9866863/184534617-1aa3c481-96d3-4ac3-9b0f-ad1b152b4f6e.png)

Philip Web Design:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535485-b1fc2306-0057-400f-bc3b-7e827b0a816b.png)

Roasted Inc:
![afbeelding](https://user-images.githubusercontent.com/9866863/184534665-99d987ee-0deb-44da-abae-55cf110cf91b.png)

Just Jeans:
![afbeelding](https://user-images.githubusercontent.com/9866863/184534677-996ca6d3-735a-4bd9-ab38-48480dc5bb30.png)

Discount Market:
![afbeelding](https://user-images.githubusercontent.com/9866863/184534682-778bfe06-e878-4a57-81bc-fa47c6392c21.png)

Dreams of New York:
![afbeelding](https://user-images.githubusercontent.com/9866863/184534987-03e39145-5916-409d-a95a-8295f7e288cb.png)

Five Cups
![afbeelding](https://user-images.githubusercontent.com/9866863/184534717-4000ce72-86d1-4739-854d-906a6e3bdb03.png)

Andy's Diamonds
![afbeelding](https://user-images.githubusercontent.com/9866863/184534742-2abf9760-09a4-41da-b879-0982e384aab5.png)

Manhattan Gas
![afbeelding](https://user-images.githubusercontent.com/9866863/184534759-799b0c00-6481-4377-8061-a92f53920164.png)

Hortensia
![afbeelding](https://user-images.githubusercontent.com/9866863/184534781-1a5f17c7-fa45-4d92-ad2f-13f94f60e626.png)

Questionable Contracts Inc
![afbeelding](https://user-images.githubusercontent.com/9866863/184534802-ae9e0f78-2aad-420d-aa33-a4fa89fa15e8.png)

The Busy Goat:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535045-a891bc6d-9b61-4ca4-9aa9-3b1d0267a684.png)

Joe's Hotdog:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535084-87aaec33-4523-4bca-a7f4-54fb4070a880.png)

365 Tobacoo:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535138-113f7677-4af5-4c76-8407-3acf1cb5a290.png)

AZ Wines:
![afbeelding](https://user-images.githubusercontent.com/9866863/184535308-56c5253f-cc3e-470e-98ee-51156e16833c.png)

Wine & Cigars by James
![afbeelding](https://user-images.githubusercontent.com/9866863/184535335-f229b3a3-b025-4daa-8ab8-dd097b0548d8.png)

Bylgawi:
![afbeelding](https://user-images.githubusercontent.com/9866863/184554691-5e33744f-1fdb-4213-a13a-c2091d7619b4.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
