### ISSUE TITLE
Murray Hill has 0 competitors businesses, all buildings are empty or available. 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1280]
### Build number

1040

### Bug description

Murray Hill has 0 competitors businesses, all buildings are empty or available. Apparently this differs from use case to use case, but in general the competitors are very low in some sections of the city.

![afbeelding](https://user-images.githubusercontent.com/9866863/184535876-6b517446-8ecc-443e-be44-82c87d778e51.png)

**Comment by David-Goru** [comment]
Seems like its working fine in Beta 6
