### ISSUE TITLE
Import Price Index has 0 impact on purchasing prices

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1282]
### Build number

1040

### Bug description

Had 0 impact, in fact I have never seen my purchasing price on my purchasing agents change at all? 
![afbeelding](https://user-images.githubusercontent.com/9866863/184536136-3d52d0a6-a353-4d57-bf71-e221ddf27ecb.png)

**Comment by David-Goru** [comment]
Fixed in build 1247
