### ISSUE TITLE
You can assign multiple employees on the same desk in the headquarters

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1284]
### Build number

1040

### Bug description

You can assign multiple employees on the same desk in HQ. Probably some checks are ignored because of the fixed schedule for HQ buildings.

https://user-images.githubusercontent.com/9866863/184541423-f0870d53-5ab9-43f9-88a7-de62d0c86fad.mp4

**Comment by David-Goru** [comment]
Fixed in build 1041
