### ISSUE TITLE
The boat turned into a titanic ... Water everywhere in the Casino Boat. 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1288]
### Build number

1144

### Bug description

Video of me running around in it. 
https://www.youtube.com/watch?v=0bQU9b0-jg0

![afbeelding](https://user-images.githubusercontent.com/9866863/185705846-089441bf-d4a7-49e7-93cf-507faef96119.png)
I sent also ingame bug report with my savegame.

**Comment by jokoho48** [comment]
Fixed in Build 1445
