### ISSUE TITLE
Can't order Pallet shelves from AJ Pederson & Son

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1290]
### Build number

1144

### Bug description

Some of the items are also lower priced than in the store, not sure if intentional.
![afbeelding](https://user-images.githubusercontent.com/9866863/185709231-7b513492-d9c9-45c4-8815-7fc1ef7054a7.png)

**Comment by David-Goru** [comment]
Fixed in build 1445
