### ISSUE TITLE
Groundplane too high on importers & warehouses

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1291]
### Build number

1144

### Bug description

Groundplane too high on importers & warehouses

https://user-images.githubusercontent.com/9866863/185811815-27a32e02-bcf0-4e2f-b052-79f36572346d.mp4

https://user-images.githubusercontent.com/9866863/185717455-9125ec0a-a417-4498-98f5-8d3ae6e6eb7f.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1445
