### ISSUE TITLE
Placing a bet before 5AM doesn't give your bet back when you get forced back ashore. 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1292]
### Build number

1144

### Bug description

Placing a bet before 5AM doesn't give your bet back when you get forced back ashore. 
I put a 9 million black jack bet, didn't draw a card, time went to 5 am and I got forced back with the boat. But I didn't get my 9 milllion back. 

https://user-images.githubusercontent.com/9866863/185718917-00ff8108-8de2-42b6-a253-a8a7bbebbdaa.mp4

As you can see, I didn't get my bet placement back.

![afbeelding](https://user-images.githubusercontent.com/9866863/185718964-582aaa11-aed2-47cc-929d-8e37ca66beb8.png)

**Comment by David-Goru** [comment]
Fixed in build 1445
