### ISSUE TITLE
Roulette wrong payout when color/any and number/any bet has been placed

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1293]
### Build number

1144

### Bug description

A roulette bet on any color with any number is a 1/1 payout ratio. So doubles your bet if you win.

![afbeelding](https://user-images.githubusercontent.com/9866863/185719559-b48e64e1-c174-4287-9cb6-00e475832882.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/185719584-5060ada2-1433-414e-a817-00ec00ec1b77.png)

I should have got 19.999.998 so I got robbed for 2.499.998 haha.

![afbeelding](https://user-images.githubusercontent.com/9866863/185719646-8ec07021-9e6a-4d13-9ed9-658c534b0efc.png)

**Comment by David-Goru** [comment]
This is by design. This roulette is a simplified version of the American Roulette. It doesn't have 0s (green) slots, and bank always wins!
