### ISSUE TITLE
Opening the Casino Boat ticket dialog and wait outside it's boarding hours still allows you to board the boat.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1294]
### Build number

1144

### Bug description

Opening the Casino Boat ticket dialog and wait outside it's boarding hours still allows you to board the boat.

No animation on the boat leaving the dock, but after some time it does put you on the casino boat. 
Should do like a check if passing 22:00 and dialog is open to close it. 

https://user-images.githubusercontent.com/9866863/185720952-b1ffc7cf-4e8d-40b4-aac9-677c1ce39512.mp4

**Comment by David-Goru** [comment]
Fixed in build 1445
