### ISSUE TITLE
GAME BREAKING: When the dialog is open to fast-forward your trip, when it hits 5am, you can click it again and it freezes the game completly.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1295]
### Build number

1144

### Bug description

When the dialog is open to fast-forward your trip, when it hits 5am, you can click it again and it freezes the game completly.

![afbeelding](https://user-images.githubusercontent.com/9866863/185721790-44f5ebe8-323d-49cf-85d8-a6569f700379.png)

As you can see here, I could click it and then it does the animation again of the boat but this time you don't actually get on to land. 
https://user-images.githubusercontent.com/9866863/185721687-8a2fb611-af19-454d-b4e3-ef99a3a9cdac.mp4

You're stuck and the game is broken even waiting to pass out doesn't work as it actually passes you out still on the boat. 
![afbeelding](https://user-images.githubusercontent.com/9866863/185721769-23866bed-5149-485d-9afe-40f76d34dde5.png)

**Comment by David-Goru** [comment]
Fixed in build 1445
