### ISSUE TITLE
Purchasing agents importers localisation is bit wrong with the $$

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1297]
### Build number

1144

### Bug description

Purchasing agents importers localisation is bit wrong with the $$
![afbeelding](https://user-images.githubusercontent.com/9866863/185765832-8bec736e-b84c-41f0-88c0-7171b4cbd4d3.png)

**Comment by David-Goru** [comment]
Fixed in build 1445
