### ISSUE TITLE
Able to input minus digits on daily payment > EconoView for the loans

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1298]
### Build number

1144

### Bug description

Able to input minus digits on daily payment > EconoView for the loans.
It doesn't actually save, but it should refrain the input to not give the impression it could be bugged this way. Because it will remember the last inputted value before that and if that's not a value you wanted to set then well ...

![afbeelding](https://user-images.githubusercontent.com/9866863/185807106-c031720d-e8da-41fa-b68d-ca573734341b.png)

**Comment by David-Goru** [comment]
Fixed in build 1145
