### ISSUE TITLE
Can choose a higher daily payment > EconoView Loans then the entire pay off amount?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1299]
### Build number

1144

### Bug description

Can choose a higher daily payment > EconoView Loans then the entire pay off amount?
This should max out at your pay off amount to avoid confusion.

![afbeelding](https://user-images.githubusercontent.com/9866863/185807325-12c17c0e-9aaf-46b5-858c-a81219f55e4f.png)

**Comment by David-Goru** [comment]
Fixed in build 1145
