### ISSUE TITLE
Glitching Building Highlight

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#130]
Alpha 4 - Build 49

Building highlight and info box glitches on and off when running into it with mouse cursor in a certain position. 

https://user-images.githubusercontent.com/44293115/120383620-0331df00-c31d-11eb-9e1d-143a072e7452.mp4

**Comment by Gerwanese** [comment]
You don't have to be running, just standing in front is enough. The player has a certain "outline" around him where the building highlight doesn't show up (as it's blocked). If the curser hits exactly the border between building highlight and the player's outline, it starts flickering.

**Comment by David-Goru** [comment]
Fixed in the past
