### ISSUE TITLE
Daily intrest doesn't change when you increase/decrease daily payback? > EconoView Loans

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1300]
### Build number

1144

### Bug description

Daily intrest doesn't change when you increase/decrease daily payback? > EconoView Loans
Not sure if this is intendend or a bug? I mean realistically speaking that's a yehhh not gone happen. :P 

![afbeelding](https://user-images.githubusercontent.com/9866863/185807519-3e9027dd-1d67-4516-8ea2-fef69c10cd50.png)

**Comment by David-Goru** [comment]
That's by design. Daily interest depends on the initial amount, not on the daily payment.
