### ISSUE TITLE
Can keep clicking on the item when call/ordering furniture & appliances, price increases but the limit stays at 18.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1301]
### Build number

1144

### Bug description

Can keep clicking on the item when call/ordering furniture & appliances, price increases but the limit stays at 18. Needs to stop adding the price to your total bill if max allowed items is only 18. 

+ It should show the amount of items you are having in your 'virtual shopping cart' as the list view looks awesome! But you have no indication on how many items you have selected. Unless you click out of it but that's just silly ... 
![afbeelding](https://user-images.githubusercontent.com/9866863/185808295-90310ed5-4456-49b6-86c6-1477b6970f75.png)

https://user-images.githubusercontent.com/9866863/185808273-81637fc7-f3b6-4be1-8da3-e2e0fcf6c0f0.mp4

https://www.youtube.com/watch?v=2Y_VUq4aIQA

**Comment by David-Goru** [comment]
Fixed in build 1445
