### ISSUE TITLE
GAME CRASH: When selecting more than 18 items and select another one game crashes.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1302]
### Build number

1144

### Bug description

When you are at the desk to buy any furniture/appliances, select of an item more then 18 items and click on another item the game simply crashes.

https://user-images.githubusercontent.com/9866863/185808355-de533ff9-69ae-4d2f-9886-380883883a48.mp4

https://user-images.githubusercontent.com/9866863/185809310-1fede591-84e0-4e6e-bfd9-f053f038792d.mp4

**Comment by David-Goru** [comment]
Fixed in build 1445
