### ISSUE TITLE
Furniture Delivery will be delivered after the set time and day passed?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1304]
### Build number

1144

### Bug description

Furniture Delivery will be delivered after the set time and day passed?

I ordered the mops for day 1375 - 10:00, I ordered after that time and they said they will deliver. (I checked and no pallets where delivered.) Should do a check if time/day >= set delivery time equals to error message!

https://user-images.githubusercontent.com/9866863/185810755-843b37dc-bc8d-471f-9733-eb134679360f.mp4

**Comment by David-Goru** [comment]
Due to https://github.com/hovgaardgames/bigambitions/issues/1303 being fixed, is almost impossible that this can be reproduced again, unless you spend over 12 hours choosing the items. In that last case, it would be fixed when https://github.com/hovgaardgames/bigambitions/issues/404 is also fixed
