### ISSUE TITLE
Can't call the recently added Mr Scott's Office furniture store in the contacts list.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1305]
### Build number

1145

### Bug description

Can't call the recently added Mr Scott's Office furniture store in the contacts list.

![afbeelding](https://user-images.githubusercontent.com/9866863/186004616-696651a0-58c0-4543-9729-b135cf15219d.png)

**Comment by jokoho48** [comment]
Fixed in Build 1147
