### ISSUE TITLE
'Annoyances' beta 5 ...

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1306]
### Build number

1145

### Bug description

Coffee and salad, really? Where's the cigars and wine atleast? It's a casino not your local Green Salad.
![afbeelding](https://user-images.githubusercontent.com/9866863/186012142-3936310a-da02-4802-a612-b78b82b8570a.png)

In a casino you expect some nicely dressed people no? (I know there's gone come more clothing down the pipeline.) But you might aswell put the suited people in to look somewhat representable. 
![afbeelding](https://user-images.githubusercontent.com/9866863/186012118-696c41fb-94c2-4e08-bb99-02b00af98c2a.png)

![afbeelding](https://user-images.githubusercontent.com/9866863/186012249-3aff1274-5fca-4976-9771-0b036253b5f3.png)

Why is the button 'Decline' Orange in one window and not in the other one?
![afbeelding](https://user-images.githubusercontent.com/9866863/186013154-850e3930-d60f-4e1b-8b83-a51c2b4de7d8.png)

This looks yanky, maybe make the box larger and then put it like:

Saturday (Day 1735)
10:00

![afbeelding](https://user-images.githubusercontent.com/9866863/186013650-0b21b1c8-87ce-4ca8-886d-b7ff7d3af287.png)

**Comment by David-Goru** [comment]
Last one (delivery time dropdown) fixed on build 1148

**Comment by David-Goru** [comment]
Third one (gray != orange button) fixed on build 1149

**Comment by David-Goru** [comment]
Second one (Casino staff clothes) fixed on Beta 7

Closing this, as wine and cigars have no utility right now
Feel free to add it as a feature suggestion on the forums!
