### ISSUE TITLE
You can buy Casino Tickets between 18 > 22 not until 21

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1307]
### Build number

1145

### Bug description

You can buy Casino Tickets between 18 > 22 not until 21.
The message is wrong or the boat is too slow ... and departs an hour later.

https://user-images.githubusercontent.com/9866863/186015634-48b68edb-1083-4cef-b2ee-042ed3110cc7.mp4

![afbeelding](https://user-images.githubusercontent.com/9866863/186015266-82070917-7ba0-4c17-86a2-dca882ce9ef3.png)

**Comment by David-Goru** [comment]
Fixed in build 1147
