### ISSUE TITLE
Overlapping UI when having a box in your hand, when discussing a delivery job.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1309]
### Build number

1145

### Bug description

Overlapping UI when having a box in your hand, when discussing a delivery job.
I know you can Discard but for the trolley you have a nice message pop up, before you can even take a seat.
![afbeelding](https://user-images.githubusercontent.com/9866863/186020990-042701c2-84e2-4d1b-bdb8-c636d51e6599.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/186020908-0d3e71bb-ca13-4569-9c1b-a0725b933e09.png)

**Comment by jokoho48** [comment]
Fixed in Build 1147
