### ISSUE TITLE
Loans could get potentially VERY easy this way ...

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1310]
### Build number

1145

### Bug description

Loans could get potentially VERY easy this way ...

Max loan at Vatander bank is 800K, which has a normal payback scheme as such.
![afbeelding](https://user-images.githubusercontent.com/9866863/186024569-4f1330ef-98f4-4f9c-95a9-8019b28a2ecb.png)

But I can set the capital payback to $ 0? This could be a potential easy mechanic to get very cheap loans, as you only have to pay back the intrest? Sort of game breaking to me as you go from 8K payback to 1.333k ... I mean some minimum capital payback should be demanded by the bank!
![afbeelding](https://user-images.githubusercontent.com/9866863/186024500-a1603dad-f1e7-4622-902d-88b876641dde.png)

**Comment by David-Goru** [comment]
This is by design. If the daily payment is $0, you'll have to pay the loan forever, as the daily interest can't be skipped. The daily payment is just how much you want to contribute towards the payment of the loan. So, this is intended
