### ISSUE TITLE
Should have logo color on white, black makes it look like it doesn't work

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1311]
### Build number

1145

### Bug description

Should have logo color on white, black makes it look like it doesn't work. I actually got pm'ed quite frequently about this people saying their logo doesn't work because the color initialy is black and they think it didn't load correct. So maybe make it default stand on white to avoid future confusion? 

https://user-images.githubusercontent.com/9866863/186026039-f6dc942c-1a07-4210-b6c6-568960246065.mp4

**Comment by David-Goru** [comment]
Fixed in build 1148
