### ISSUE TITLE
Seeing delivery day-time in the store dialog

### ISSUE THREAD

**Issue by Samm-G** [hovgaardgames/bigambitions#1312]
### Build number

1146

### Bug description

Small QOL request.
I forgot what time I ordered the furniture, Can you plz mention the Time and Day here in the Dialog, so I can look it up again?

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43959475/186109192-d27440fb-9dcd-461b-b6fa-42c53b8c5a35.png)

**Comment by David-Goru** [comment]
Fixed in build 1148
