### ISSUE TITLE
Coffee Machine need not fulfilled? Yet It's on a counter and it's filled?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1314]
### Build number

1146

### Bug description

Coffee Machine need not fulfilled? Yet It's on a counter and it's filled?

https://user-images.githubusercontent.com/9866863/186534400-588a294f-8909-4421-ae80-2ff14461546a.mp4

**Comment by Gerwanese** [comment]
You are in Anneliens Lawyer, but the coffee machine is required in RPGforYOU HQ. Thus closing this bug.

**Comment by Gerwanese** [comment]
Reopened, video will be updated to show the error in the correct building.

**Comment by David-Goru** [comment]
Fixed in build 1148
