### ISSUE TITLE
Doesn't pop up the you haven't paid for this item yet at NY Distro for paperbags

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1315]
### Build number

1146

### Bug description

Doesn't pop up the you haven't paid for this item yet at NY Distro for paperbags

![afbeelding](https://user-images.githubusercontent.com/9866863/186532784-980b5d1d-f778-4197-ad6e-53a8da09b03a.png)

https://user-images.githubusercontent.com/9866863/186532876-c0df94ef-72c7-4d63-b393-243ec7b1ae63.mp4

**Comment by David-Goru** [comment]
Fixed in build 1148
