### ISSUE TITLE
Employee demands - an Office Char 2?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1316]
### Build number

1146

### Bug description

Employee demands - an Office Char 2?
![afbeelding](https://user-images.githubusercontent.com/9866863/186533027-28eddeee-51e4-46e6-bd5f-3d9d8d624adc.png)
Besides the obvious missing I ...

The type office chair 2 doesn't exist anymore right? I believe that's now the Stump Mesh Office Chair?
![afbeelding](https://user-images.githubusercontent.com/9866863/186533082-bd0a8ba2-ad94-492c-a410-fdb488c18562.png)

**Comment by Gerwanese** [comment]
Is this a new candidate, or was that person in the messages before already?
Office Chair 2 (with i) was just renamed to Stump Mesh Office Chair, so it might be possible that old candidate messages still list the old name. It shouldn't happen anymore in new candidate messages.

**Comment by Gerwanese** [comment]
Fixed in build 1147 and later, or with a manual language update in build 1146.
