### ISSUE TITLE
Simplfy the new micro management that's needed for the employee needs in beta 5

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1317]
### Build number

1146

### Bug description

With the fysical need of items like sofa, type of desk and such, it would be a huge improvement to see like a:
![afbeelding](https://user-images.githubusercontent.com/9866863/186536253-c6b77687-5917-4d9d-8e84-0c20fe4d3354.png)
or the need in green when it's actually fulfillied. Cause otherwise you need to right click, manage and you lose your position in the schedule completly.

![afbeelding](https://user-images.githubusercontent.com/9866863/186536186-aef4ea9b-914f-4801-85db-551a72b07621.png)

Also because of the need of specific chairs and desk types it might be nice to have a tooltip for the computer. So you can see what type of furniture that office setup has so you can actually put the right lawyer at the office setup he needs with chair x and desk y. Cause when you have allot of desks and employees this can be very painful to see what desk that lawyer sits on to then change the furniture to the required needs of that lawyer.

![afbeelding](https://user-images.githubusercontent.com/9866863/186536391-55e525fa-0834-41f1-85e5-bcdc789beffe.png)

**Comment by David-Goru** [comment]
Fixed in build 1149
