### ISSUE TITLE
GAME BREAKING: When you click on a phone app before/while the boarding animation of the boat you get stuck.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1318]
### Build number

1149

### Bug description

GAME BREAKING: When you click on a phone app before/while the boarding animation of the boat you get stuck.
You have to close the game down, waiting doesn't help you are stuck. 

https://user-images.githubusercontent.com/9866863/186774245-9bf80061-eb24-4617-8f33-1f423a4285d9.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1253.
