### ISSUE TITLE
False forwarding of time when sleeping.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1320]
### Build number

1149

### Bug description

False forwarding of time when sleeping.

It should skip 1 hour, but it skipped two ... might need to have a look at that.

https://user-images.githubusercontent.com/9866863/186775875-8e516d15-4a2e-4f2d-b821-812e05cd742c.mp4

**Comment by jokoho48** [comment]
that is due to the size and complexity of your save game, due to that onNewHour taking a lot of time. this should be reduced in Beta 6
