### ISSUE TITLE
Importance of a handcart in warehouses increased with beta 5 adding the delivery of furniture.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1321]
### Build number

1149

### Bug description

Importance of a handcart in warehouses increased with beta 5 adding the delivery of furniture.

I mean moving 18 boxes, 1 by 1 cause there's no handcart in the warehouse seems bit unnesecary and tedious, maybe add a handcart to the warehouse? :)

![afbeelding](https://user-images.githubusercontent.com/9866863/186781698-e78ab0a7-b4c2-4fa1-add2-3781cc4c8551.png)

**Comment by David-Goru** [comment]
Fixed in beta 8
