### ISSUE TITLE
Enter and Esc key support for all Confirmation Dialog Boxes

### ISSUE THREAD

**Issue by Samm-G** [hovgaardgames/bigambitions#1322]
### Build number

1151

### Bug description

Another Small QOL Request:
It would be way easier to use Enter key to Accept a Confirmation, and Esc key to Cancel.
Plz add the key support, to save some mouse clicks..

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43959475/186962900-59f478fd-4dd6-443f-933a-f0bf10c63c6f.png)

**Comment by David-Goru** [comment]
Fixed in build 1248
