### ISSUE TITLE
GAME CRITICAL: Fast-forwarding time doesn't show any sales in Econoview and also doesn't complete the objective

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1324]
### Build number

1151

### Bug description

Did the entire day of fast-forwarding until my energy ran out, went to bed woke up and 0 income gained. Although I saw multiple clients buy stuff from me during the fast-forwarding.

![afbeelding](https://user-images.githubusercontent.com/9866863/187047835-ddb55476-9f08-4cb2-b030-cc83773c4857.png)

![afbeelding](https://user-images.githubusercontent.com/9866863/187047849-95309b9c-a60a-44b1-b4ac-b12273e21985.png)

This also doens't complete the following objective making people stuck in 'tutorial' progression.
![afbeelding](https://user-images.githubusercontent.com/9866863/187047842-79619e96-0bc7-49d6-b6c9-4fc97c8afa4a.png)

**ALSO** 

The objective: Run the business for 2 days

Is confusing for new people, they think just passing 2 days should complete this. But they actually have to assign themself to work at the register on the store for 2 days. So I think this should be changed to make it more clear as for the new people this is confusing and they think they are stuck.

**Comment by David-Goru** [comment]
Fixed in build 1152

(By Joko!)
