### ISSUE TITLE
Oversight on view on map button for IRS in contact list?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1326]
### Build number

1151

### Bug description

Oversight on view on map button for IRS in contact list? It's on all the rest of the business so, probably an oversight?

![afbeelding](https://user-images.githubusercontent.com/9866863/187083532-2a563508-017f-452c-a20e-5228b668216c.png)

![afbeelding](https://user-images.githubusercontent.com/9866863/187083524-db91ca59-89e7-4b9d-8d4c-2a3710b786e8.png)

**Comment by David-Goru** [comment]
Fixed in build 1247
