### ISSUE TITLE
Handtruck indicates entry point at garage doors, but you can't enter through those doors.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1327]
### Build number

1152

### Bug description

Handtruck indicates entry point at garage doors, but you can't enter through those doors.

Either you remove those entry points as a choice, like you don't see them when you are on foot. OR you do make them work? 

![afbeelding](https://user-images.githubusercontent.com/9866863/188313003-9c06ab1c-45c0-41b2-8e06-d8de6e3812fb.png)

**Comment by jokoho48** [comment]
Fixed in Build 1248
