### ISSUE TITLE
Auto park at gas stations might need a little bit of fixing so you don't bounce around or under.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1331]
### Build number

1152

### Bug description

Auto park at gas stations might need a little bit of fixing so you don't bounce around or under.

https://user-images.githubusercontent.com/9866863/189502597-e6b731d0-fe38-4bdc-9b66-86f3b414072e.mp4

https://user-images.githubusercontent.com/9866863/189502614-d57574e7-67ee-41e6-87d3-3cc003bf9f5e.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1253
