### ISSUE TITLE
Buying gas at 0 $ ? spamming Econoview with it.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1332]
### Build number

1152

### Bug description

Buying gas at 0 $ ? 

You got it fixed with the repairs it doesn't do it for that. Just gas you can apparently buy at 0 $ ... If statement needed? 

![afbeelding](https://user-images.githubusercontent.com/9866863/189502918-92eb9972-ec64-424b-be79-941d0a5beb63.png)

**Comment by David-Goru** [comment]
Fixed in build 1248
