### ISSUE TITLE
Market insider information blob on the left and the Total size column are in m2 and I put my stuff in Feet. So these haven't been adjusted correctly.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1334]
### Build number

1252

### Bug description

Market insider information blob on the left and the Total size column are in m2 and I put my stuff in Feet. So these haven't been adjusted correctly.

![afbeelding](https://user-images.githubusercontent.com/9866863/190270805-7ee93b73-9e65-4f7d-aa5e-62ea1a637e41.png)

https://user-images.githubusercontent.com/9866863/190270784-5ff7c192-b3b7-44fe-bb53-e06c683c6905.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1253.
