### ISSUE TITLE
Assigning employee types to stores/warehouses/offices/headquarters / optimalisation

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1338]
### Build number

1252

### Bug description

Assigning employee types to stores/warehouses/offices/headquarters / optimalisation

You should make it so when you select a lawyer only Office type business end up in the dropdown list.
Same with Logistic/HR/PA's only for headquarters.
Drivers only warehouses.
Etc...

Once you have so many business it's an absolute pain to scroll through the list. _(Like for my HR finding my 1 HR building in my list was terrible experience haha.)_

![afbeelding](https://user-images.githubusercontent.com/9866863/190274738-9c39bf75-e864-4e3b-8641-6c8fa6330a60.png)

**Comment by David-Goru** [comment]
Fixed in beta 7
