### ISSUE TITLE
Can't call Autotow for the truck or is there gone be a Trucktow or simply not planned?

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1339]
### Build number

1252

### Bug description

Can't call Autotow for the truck or is there gone be a Trucktow or simply not planned?

https://user-images.githubusercontent.com/9866863/190277108-76afdcf1-54b4-44d2-9274-9ec528d9724f.mp4

**Comment by jokoho48** [comment]
Already Fixed in Build 1253
