### ISSUE TITLE
Very slow scrolling in Purchase Screen When Queueing

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#134]
Alpha 4 - Build 51

When in the purchase menu in a store and you have more than 3 items in your basket to see the 4th you need to scroll down to see it, however to scroll to see it you will be there scrolling for about 5 mins

**Comment by Gerwanese** [comment]
https://user-images.githubusercontent.com/17579552/120858867-b6037680-c583-11eb-967c-4d6648740813.mp4

**Comment by jhovgaard** [comment]
Fixed in build 51

**Comment by Gerwanese** [comment]
Have to reopen this - scrolling now is fast, but shows some strange behaviour on top or bottom: It "overscrolls" the list and then comes back to the top/bottom shuddering. At the beginning of the video you see it when I move the mouse wheel slowly; later in the movie you see that when I move the mouse wheel faster, it will scroll very far off the first/last item and it takes a bit to return.

https://user-images.githubusercontent.com/17579552/121816048-b08be780-cc79-11eb-9cc9-d2590923d084.mp4

**Comment by David-Goru** [comment]
Fixed in build 257
