### ISSUE TITLE
Make a button empty, so you don't have to manually unassign 25 of them ...

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1340]
### Build number

1252

### Bug description

Make a button empty, so you don't have to manually unassign 25 of them ... very annoying lol.

![afbeelding](https://user-images.githubusercontent.com/9866863/190278074-5a3acd90-dbd6-41a9-a3b0-424d1f91178f.png)

**Comment by jokoho48** [comment]
Fixed in Build 1253
