### ISSUE TITLE
Radiator creates invisible obstacle on the other side of the wall that blocks movement

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1343]
### Build number

1252

### Bug description

Radiator creates invisible obstacle on the other side of the wall that blocks movement

https://user-images.githubusercontent.com/9866863/190821238-aa60c23d-685c-45a7-a663-27078b5c4ff1.mp4

**Comment by jokoho48** [comment]
Fixed in build 1254
