### ISSUE TITLE
HR manager training, a unexperienced employee shouldn't be able to train to 100 %

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1346]
### Build number

1252

### Bug description

HR manager training, a unexperienced employee shouldn't be able to train his assigned employees to 100 %. Makes no sense ... It's like I'm gone teach you guy's to program to a 100 % level never gone happen.

Suggestion, limit the training level to the training level the employee has. 

**Also** training your employees should increase their wage but there should be still a wage gap between hiring an experienced employee through the recruitment offices. Or training a low experienced employee to a higher standard. Training in house employees should still be more worth it then hiring them. But training a 20/30 % employee to 100 % withouth a wage increase is unrealistic. 

![afbeelding](https://user-images.githubusercontent.com/9866863/190922809-fd388f6b-c4f8-4c28-afa0-c2bddb7e3d51.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/190922552-068ada95-d148-4b7d-871d-4325c9b9d5de.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/190922744-ea620061-f0b3-4f75-832d-2edaf0540e02.png)

**Comment by David-Goru** [comment]
HR Managers don't train, they outsource the training. You should be getting a transaction with the cost of the training. That cost is lower than training them yourself, though
