### ISSUE TITLE
HR Manager settings, can't click through to the employee menu

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1347]
### Build number

1252

### Bug description

HR Manager settings, can't click through to the employee menu

I wanted to see why Natalie Collins only has 50 % satisfaction, but clicking on her name doesn't bring me up to her information screen.
![afbeelding](https://user-images.githubusercontent.com/9866863/190923027-a16e1327-ac71-4929-b527-a8984cc786e9.png)

Should open up this:

![afbeelding](https://user-images.githubusercontent.com/9866863/190923067-bc739854-1de2-4f43-81db-02f4b25dc522.png)

**Comment by David-Goru** [comment]
Fixed in build 1254
