### ISSUE TITLE
When you loaded a save game you can't go back main menu and start a new game.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1349]
### Build number

1252

### Bug description

When you loaded a save game you can't go back main menu and start a new game.

You click on the button but nothing happens.
![afbeelding](https://user-images.githubusercontent.com/9866863/191378103-de160e29-f00d-4f42-8194-fc946237fe94.png)

**Comment by jokoho48** [comment]
Already fixed
