### ISSUE TITLE
Real Estate settings mentions ft² and sqm

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1350]
### Build number

1254

### Bug description

Real Estate settings mentions ft² and sqm.

Totaly daily rent ( ft² & sqm)

![afbeelding](https://user-images.githubusercontent.com/9866863/192373442-8e47a85c-aa32-4d1c-b2e1-d950e2f79b7d.png)

**Comment by jokoho48** [comment]
Fixed in Build 1255. (can be locally fixed by pulling a localizor update in the settings ;) )
