### ISSUE TITLE
Amount of businesses is counted wrongly. 

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1355]
### Build number

1254

### Bug description

Amount of businesses is counted wrongly. 

On the midnight cycle it says 25.
![afbeelding](https://user-images.githubusercontent.com/9866863/192648386-f475d047-8209-494c-9924-667008f7820b.png)
In Persona 24.
![afbeelding](https://user-images.githubusercontent.com/9866863/192648403-9ab9f764-6c1a-4ed5-878a-762c7c38d282.png)

**Comment by David-Goru** [comment]
Fixed in build 1256
