### ISSUE TITLE
Car stuck between gas pumps @ 47 5th avenue

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1356]
### Build number

1254

### Bug description

Car stuck between gas pumps @ 47 5th avenue

![afbeelding](https://user-images.githubusercontent.com/9866863/192901226-ef28f1b9-f1ee-4d0a-9b52-25b8f8b2cd6b.png)

**Comment by David-Goru** [comment]
Fixed in build 1256
