### ISSUE TITLE
Imperial and 12 hour stays in my save game even after disabling it.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1357]
### Build number

1254

### Bug description

Imperial and 12 hour stays in my save game even after disabling it.

Everytime I load my savegame it's back to 12h and Imperial system even tough I disabled it everytime. Might not save correctly in the savegame?

![afbeelding](https://user-images.githubusercontent.com/9866863/193467701-0f9c30db-cfd6-4e15-b30b-02fff351bc80.png)

**Comment by David-Goru** [comment]
Fixed in build 1256
