### ISSUE TITLE
Fryer has a new item called Itemname_donut, thats a classified woopsie right there

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1359]
### Build number

1259

### Bug description

Fryer has a new item called Itemname_donut, thats a classified woopsie right there.

It was in the shadows before, but now someone activated it from the shadows! It must return into the darkness!

![afbeelding](https://user-images.githubusercontent.com/9866863/195950508-25390877-1cbe-4b14-beb4-daab9fc5e985.png)

**Comment by David-Goru** [comment]
Fixed in build 1358
