### ISSUE TITLE
Clicking on the checkmark in the Happiness Category or the big personal goals stars in Persona triggers a wrong Help section.

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1361]
### Build number

1261

### Bug description

Clicking on the checkmark in the Happiness Category or the big personal goals stars in Persona triggers a wrong Help section.

Video tells it all. :)

https://user-images.githubusercontent.com/9866863/196558516-82c572e3-ae81-4452-a958-6be2f7d6a55b.mp4

PS: Why if you click on your guy/girl doesn't it open up the Persona window?

![afbeelding](https://user-images.githubusercontent.com/9866863/196559133-413f9cd0-b9b7-4301-ba32-81792459295a.png)

**Comment by David-Goru** [comment]
Fixed in build 1358
