### ISSUE TITLE
Can't put a plant on coffee table type 3

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1363]
### Build number

1368

### Bug description

Can't put a plant on coffee table type 3

![afbeelding](https://user-images.githubusercontent.com/9866863/200078238-5542130c-df7e-4b1b-b94c-a1c6be5cc917.png)

Works for the other one's.
![afbeelding](https://user-images.githubusercontent.com/9866863/200078259-bbfa906f-4b53-4e24-a827-dbdff05dccfb.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/200078281-bbdaba0d-6b36-43c0-8652-827bf1bf87cc.png)

**Comment by rpgforyou** [comment]
Alsoo normal table you can't place a plant on it.
![afbeelding](https://user-images.githubusercontent.com/9866863/200081144-6e5955a4-dfb9-43b9-9179-847430ba1683.png)

**Comment by David-Goru** [comment]
Fixed in build 1580
