### ISSUE TITLE
Wall textures are off in the new apartment layout

### ISSUE THREAD

**Issue by rpgforyou** [hovgaardgames/bigambitions#1364]
### Build number

1368

### Bug description

Wall textures are off in the new apartment layout

They don't have the colour of the wall around the glass panes.
![afbeelding](https://user-images.githubusercontent.com/9866863/200079832-347637ba-870b-449e-a2c4-31658c7c598e.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/200079954-c87ad19b-3107-427d-a3d2-50437eff7bba.png)

In the right corner of the balcony a piece of the wall is green.

![afbeelding](https://user-images.githubusercontent.com/9866863/200080028-eab4dd2e-27a3-497b-9b9d-52f011116eb8.png)
![afbeelding](https://user-images.githubusercontent.com/9866863/200080053-936ab70f-3907-4613-ac13-0d11583c8eb9.png)

Also on the left side corner, but the longer wall side.
![afbeelding](https://user-images.githubusercontent.com/9866863/200083862-dc04777c-1306-43b9-a688-9971fbbba3fc.png)

**Comment by David-Goru** [comment]
Fixed in the past
