### ISSUE TITLE
Uncle Fred not able to complete my objective

### ISSUE THREAD

**Issue by Samm-G** [hovgaardgames/bigambitions#1365]
### Build number

1369

### Bug description

I have rented a Small Warehouse, Still the Objective "Rent a Small Warehouse" is not completed.

### Steps to reproduce the bug

Just following through Uncle Fred's Objectives.

### Savegame file

[Samarth G -Beta7-Unstable.hsg.txt](https://github.com/hovgaardgames/bigambitions/files/9967700/Samarth.G.-Beta7-Unstable.hsg.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/43959475/200747964-c9cbeeff-7d95-46c8-abca-4a07cf4b4b6b.png)
![image](https://user-images.githubusercontent.com/43959475/200748189-8b0902a4-a4ce-4d55-9819-2e6a0c30a8dc.png)

**Comment by David-Goru** [comment]
Fixed in build 1370!
