### ISSUE TITLE
Placing Furniture "P" Key Bug

### ISSUE THREAD

**Issue by Samm-G** [hovgaardgames/bigambitions#1367]
### Build number

1369

### Bug description

When I place the Second Furniture using the "P" key from my handtruck, the Handtruck Inventory Window is not closing and it not possible to click through this window to place.

### Steps to reproduce the bug

1. Park Handtruck
2. Take 1 Item from Handtruck
3. Press "P" to place the Item
4. The Inventory Window does not hide, and it's difficult to place.

I have encountered this bug only a few times.. Unable to reproduce all the time.

### Savegame file

![image](https://user-images.githubusercontent.com/43959475/200750960-4fff0073-56ff-4c2b-b67a-84a8c26e17ca.png)

**Comment by jokoho48** [comment]
Fixed in Build 1370
