### ISSUE TITLE
Inventories won't open after opening Voogle Maps while using an inventory

### ISSUE THREAD

**Issue by erottier** [hovgaardgames/bigambitions#1369]
### Build number

1714

### Bug description

All 'Manage Storage' inventories are not accessible anymore after opening Voogle Maps while in an inventory.
The only fix is to exit and reload the game.

I can still eat from my fridge or sleep, only not able to access inventories.
I can click on Manage Storage, I hear the sound and see the blue circle below me 'pinging', but no window appears.

### Steps to reproduce the bug

I am in a store, using Manage Storage on a Storage shelf.
When the inventory is still open, I click on the Voogle Maps app.
After closing this app, all inventories are not able to open anymore.

### Savegame file

[eS8bLRdQoEKB0uetvTytPw==.zip.txt](https://github.com/hovgaardgames/bigambitions/files/11008819/eS8bLRdQoEKB0uetvTytPw.zip.txt)

**Comment by rpgforyou** [comment]
Thank you soooooo much! :) We have a reproduction on one of the high priority bugs! Thanks thanks!!!

**Comment by David-Goru** [comment]
Thank you very much for the report, we've been trying to reproduce it for weeks!

Fixed in build 1718!
