### ISSUE TITLE
Task list entries ending with variations of period/exclamation marks

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#152]
Build 54

First item ("requires at least one") does not have any period or exclamation mark at line end.
The "has no" sentences all end with a period (that's okay for me).
The "is out of" sentences all end with ".!" instead of just one of them.

Besides, the read can be quite hard to read depending on the background of the task list. So I would recommend to make it either more opaque or change the text color somehow, although that's not really a bug.
My recommendation: Keep text white and add a read or orange icon in front (red for problems, orange for warnings, for example "soon running out of" messages).

![grafik](https://user-images.githubusercontent.com/17579552/121816257-e087ba80-cc7a-11eb-8f66-40766351a9db.png)

**Comment by David-Goru** [comment]
Fixed in the past
