### ISSUE TITLE
Car physics issues when leaving Metro Wholesales

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#153]
Build 54

When I came out of the shop, I found the situation in the first screenshot.
None of the cars involved is mine, so it happend completely by AI cars.

Second screenshot shows what happened when the "normal" cars (those not on the side) where automatically removed after a while. The black car turned on its wheels again, made a U turn and drove into the building wall. Seems it's somehow off the road system.

After entering and leaving the shop a few times, more issues happened (see video). I could reproduce this several times. Probably that also caused the first issue (cars on top of each other and the black one just fell down onto its side).

![grafik](https://user-images.githubusercontent.com/17579552/121816700-63117980-cc7d-11eb-917d-9bf76a7f6504.png)

![grafik](https://user-images.githubusercontent.com/17579552/121816706-6b69b480-cc7d-11eb-89cd-d55bf9aaa625.png)

https://user-images.githubusercontent.com/17579552/121816807-05316180-cc7e-11eb-9c6c-c5f0649d515d.mp4

**Comment by jokoho48** [comment]
Fixed a long time ago
