### ISSUE TITLE
Building on 25th Thirdstreet flickers when standing next to it and selecting the building

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions#156]
Build 55.

https://user-images.githubusercontent.com/85610694/121817893-68be8d80-cc84-11eb-8f7f-b6ce22fe7bd2.mp4

**Comment by Gerwanese** [comment]
Confirmed. Only happens when the building is invisible and you hover over it.

**Comment by tomvbj** [comment]
in build 75 only the UI of the building Flickers.

https://user-images.githubusercontent.com/85610694/124762832-9d480100-df33-11eb-9f0b-48d7c3dc1e25.mp4

**Comment by David-Goru** [comment]
Fixed in the past
