### ISSUE TITLE
Clothing shop: Can take out box with clothes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#163]
Build 55

In clothing store it's possible to take out a whole box of clothes if you don't take a shopping basked first (if you take the basket, everything is working as intended). It seems shopping basked is no requirement for taking clothes.

https://user-images.githubusercontent.com/17579552/121819072-7c212700-cc8b-11eb-9ede-af9a084c1bb7.mp4

**Comment by David-Goru** [comment]
Fixed in the past
