### ISSUE TITLE
Clicking slightly above/below GUI elements not recognised

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#175]
Build 55

If I click slightly above or below the phone apps overlay (to walk to that position) it's not recognised. It seems the "blocked out" area is larger than the overlay itself.
The same is true for the status bar on top of the screen, if you click slightly below it, the click is not registered. Probably a general problem of all the GUI elements.

https://user-images.githubusercontent.com/17579552/121822588-2efb8000-cca0-11eb-9d15-33bc2e013d9a.mp4

**Comment by jokoho48** [comment]
This is due to the Textures being smaller than the Element and Raycast Padding. Unity 2021.2 will apparently get a tool for visualising and thus fixing those offsets easier. I would say that is an issue for that point and after.

**Comment by David-Goru** [comment]
Fixed in build 276
