### ISSUE TITLE
Task: Clothes store is out of "undefined"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#178]
Build 55

Clothes store shows it's out of "undefined. Obviously clothes is meant.

Additionally, the message is shown twice because I have two clothes racks. No matter how many racks I have, the message should always only shown once.

Actually the same happens for an empty shelf in the gift store (build 69). Maybe it's because it can be stocked with different types of items (although not yet for gift store).
A solution would be just to have a task "<Store name> has empty ClothingRacks" (or "MetalShelves"), if there is at least one empty.

![grafik](https://user-images.githubusercontent.com/17579552/121823388-4a1cbe80-cca5-11eb-8457-7491e6f2f49c.png)

**Comment by David-Goru** [comment]
Fixed in the past
