### ISSUE TITLE
BizMan: Upper opening times bar of previous store are not reset when changing next store

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#179]
Build 55

I've selected opening times 8:00-24:00 for one restaurant (adjusted through top bar, so all days are same).

Then I opened the next store in the BizMan (even closed BizMan in between). The bars for every day are reset to the default (8:00 to 16:00), but the upper bar for adjusting all days at once still shows the times of the previous restaurant.
It also shows the green "open" switch active from the previous restaurant.

![grafik](https://user-images.githubusercontent.com/17579552/121823517-f8286880-cca5-11eb-9f30-c1937a62ef34.png)

**Comment by David-Goru** [comment]
New system removes that functionality
