### ISSUE TITLE
Metro Whoesales: Classic cheap male clothing box shelf shows empty but items can be bought

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#180]
Build 55

The metal shelf for "Classic cheap male clothing box" is displayed empty although I can still take boxes from it.

![grafik](https://user-images.githubusercontent.com/17579552/121823638-ccf24900-cca6-11eb-9b24-edce9ef6db8b.png)

**Comment by David-Goru** [comment]
Fixed in the past
