### ISSUE TITLE
Industrial Fridge can only be placed with huge gap to the wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#185]
Build 55

The industrial fridge can only be placed with a huge gap to the wall.
This is in part because the placement grid doesn't extend all the way to the wall, but in part also because the fridge's back has some gap behind it.
This is only the case for one side of the room, where the grid has a border. On the other side the grid is "open" and allows the green area of items to extend out of it.

![grafik](https://user-images.githubusercontent.com/17579552/121824623-c9ae8b80-ccad-11eb-9aa6-7fee8cfa0734.png)

![grafik](https://user-images.githubusercontent.com/17579552/121824648-f9f62a00-ccad-11eb-86bd-d28f0c99a835.png)

**Comment by adameg2305** [comment]
Is also the same for the normal fridge.

**Comment by jokoho48** [comment]
Fixed a while ago
