### ISSUE TITLE
Bank stops giving out credit without any response

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#186]
Build 55

After a while of playing, suddenly the bank doesn't give out credit anymore without any message why. The button simply doesn't work anymore.

It does not matter how much I have taken already (had >80 million before) or how many loans I have (only 4 in this savegame, I had 6 in others already).

This happened several times with different savegames. Even saving and reloading doesn't fix the issue.

https://user-images.githubusercontent.com/17579552/121825545-60317b80-ccb3-11eb-8a90-854bfd493d3a.mp4

**Comment by Gerwanese** [comment]
This might be an issue with pre build 55 savegames. With a new savegame it's hard to judge since the bank won't allow any further credit after the initial 15.000$.

**Comment by David-Goru** [comment]
Fixed in the past
