### ISSUE TITLE
Bank: Wrong message when no more loan possible (only display issue)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#188]
Build 55

When I can't get any further loan, the message tells me that "we won't be able to loan you more than a total of 0$"
That's technically correct but it should rather say: "we won't be ably to loan you any money"

![grafik](https://user-images.githubusercontent.com/17579552/121825759-6e33cc00-ccb4-11eb-8f60-1b1719202627.png)

**Comment by David-Goru** [comment]
Fixed in build 295
