### ISSUE TITLE
Can drive outside of the map with one side of a car

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions#192]
When you drive over the sidewalk you can drive with one side of the car over the map outline.
Not a big issue thought you should know for alpha 5

https://user-images.githubusercontent.com/85610694/121942054-5873e480-cd50-11eb-926a-3b5f391d1525.mp4

**Comment by tomvbj** [comment]
Build 55

**Comment by David-Goru** [comment]
Fixed in the past
