### ISSUE TITLE
Drive-in wholesale store can drive in to the cash registers

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions#193]
When you drive to the exit of the drive-in wholesale store you can drive threw the cash register. Expected to be blocked or not accessible by cars to drive threw. 
![Big Ambitions 6_14_2021 8_45_28 PM](https://user-images.githubusercontent.com/85610694/121943595-09c74a00-cd52-11eb-9ab4-adf9d8383f02.png)
![Big Ambitions 6_14_2021 8_45_47 PM](https://user-images.githubusercontent.com/85610694/121943602-0af87700-cd52-11eb-8dbf-0314cfdfdbf7.png)

**Comment by tomvbj** [comment]
Build 55. and youre also able to park youre car in the ventilation pipe.
![Big Ambitions 6_14_2021 8_51_32 PM](https://user-images.githubusercontent.com/85610694/121943818-4004c980-cd52-11eb-923e-707e1a9cc241.png)

**Comment by tomvbj** [comment]
Same with these pallets.
![Big Ambitions 6_14_2021 8_53_27 PM](https://user-images.githubusercontent.com/85610694/121944008-74788580-cd52-11eb-9cd8-68c394c1621e.png)

**Comment by David-Goru** [comment]
Fixed in build 344
