### ISSUE TITLE
Drive-in wholesale store Bizman view doesn't show market value and building size.

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions#194]
When in Bizman the drive-in wholesale store doesn't show the market value and building size

![Big Ambitions 6_14_2021 9_38_26 PM](https://user-images.githubusercontent.com/85610694/121949462-c1f7f100-cd58-11eb-8da5-dae1b6a0b0ae.png)

**Comment by Gerwanese** [comment]
Build 55

**Comment by David-Goru** [comment]
Fixed in build 268
