### ISSUE TITLE
Floating Building

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#197]
Alpha 4 - Build 57

11th Fourth Avenue is floating above the ground.

The front is visible but the sides arent.
![eeDUxg](https://user-images.githubusercontent.com/44293115/122126581-e079ed00-ce29-11eb-98ae-3c79f597c1c5.jpg)

**Comment by Gerwanese** [comment]
It's the same building mentioned in #74, possibly related to that issue?

**Comment by adameg2305** [comment]
> 
> 
> It's the same building mentioned in #74, possibly related to that issue?

It is the same building, however it's now a different issue, the bottom part of the building is missing.

**Comment by Gerwanese** [comment]
The comment was mostly ment for Jonas, because it might be possible that the reason for this bug might be related to the reason for the other bug. :)
I still keep both bugs open since it might as well have different reasons.

**Comment by adameg2305** [comment]
Looks to now be the same issue for the El Gato food store in build 138
![PkYCaK](https://user-images.githubusercontent.com/44293115/128352942-952945b9-84ee-448c-b641-f1aa98377d1b.png)

**Comment by adameg2305** [comment]
Similar issue in 23rd street 3rd avenue
![DFJdGe](https://user-images.githubusercontent.com/44293115/128353634-4a0286fa-a2d1-4c4c-9e3f-4c6e476e7af1.png)

**Comment by jhovgaard** [comment]
All fixed at some point. I couldn't recognize the building mentioned as `Similar issue in 23rd street 3rd avenue`.
