### ISSUE TITLE
When working myself in my own shop, a customer can be stuck at the counter after closing time

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#199]
Build 57

My own shop opening times are set until 18:00.
I am automatically removed from duty after that time, but a customer was still in the shop and is now stuck at the counter - because I can't serve him anymore without changing the opening times.

A fix would be to check if there's still a customer in the shop, and only unassign me from counter if there is no customer left (combined with not generating new customers after closing time, it should only require a few minutes of overtime work).

![grafik](https://user-images.githubusercontent.com/17579552/122136684-41fa8580-ce43-11eb-8764-7a67ef749d79.png)

**Comment by Gerwanese** [comment]
Additional info: The items the customer had in his shopping basket will be lost if you leave and re-enter the shop.

[Build130-GiftysJustBeforeClosingTime.txt](https://github.com/hovgaardgames/bigambitions-public/files/6913108/Build130-GiftysJustBeforeClosingTime.txt)

https://user-images.githubusercontent.com/17579552/127780444-911f76ad-0d92-460f-9607-509685648ea3.mp4

**Comment by David-Goru** [comment]
Fixed in the past
