### ISSUE TITLE
Shop: After paying it's possible to add more items and walk out without paying those

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#20]
After you've paid for an item in a shop, you can just pick more items and walk out without having (and without being able) to pay the additional items.
![grafik](https://user-images.githubusercontent.com/17579552/115999705-113d6300-a5ed-11eb-9805-825d1316ce27.png)
Those additional items are not consumable right away but can be placed into my fridge at home.

**Comment by Gerwanese** [comment]
This even works with different stores. Buy some food and you'll get a fridge for free...
![grafik](https://user-images.githubusercontent.com/17579552/116000714-a0e51080-a5f1-11eb-9b65-72c55eab4c48.png)

**Comment by jhovgaard** [comment]
Fixed in build 49

**Comment by Gerwanese** [comment]
Reopening, as of build 130 you can steal again at the supermarket:

[Build130-SupermarketTheft.txt](https://github.com/hovgaardgames/bigambitions-public/files/6911731/Build130-SupermarketTheft.txt)

https://user-images.githubusercontent.com/17579552/127750280-094f0334-dc99-4af7-970f-77fd366af647.mp4

**Comment by jokoho48** [comment]
Fixed in Build 186

**Comment by Gerwanese** [comment]
Reopened: The main issue is fixed - you can't leave the store anymore with unpaid items.
However it is still possible to add new items after paying the first one, they will all end up in your paperbag and it's impossible to pay for them.
I think best would be to completely disallow unpaid items in paper bags.

**Comment by jokoho48** [comment]
assigning Jonas#1 as i think that is his decision what we should do about that

**Comment by jhovgaard** [comment]
>I think best would be to completely disallow unpaid items in paper bags.
I agree. We should only allow adding items to the ShoppingContainer defined in `BusinessTypeSettings.RequiredShoppingContainer` for the specific business.

**Comment by David-Goru** [comment]
Fixed in build 344
