### ISSUE TITLE
Shop 19th Fourth Ave (next to the bank) entered through the wrong door

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#200]
Build 57

The shop 19th Fourth Avenue next to the bank is not entered through the visible shop door but through a door besides the shop (which rather looks like it would belong to the apartments above).

https://user-images.githubusercontent.com/17579552/122138487-23968900-ce47-11eb-914a-168f6d71c0f4.mp4

**Comment by David-Goru** [comment]
Fixed in build 329
