### ISSUE TITLE
Space for pause not working after clicking pause or speed change buttons

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#201]
Build 57

This is probably a similar issue like in #12 (Space not working due to focus problems with the phone apps).

If you click the pause icon (and nowhere else afterwards), pressing Space won't work and simply do nothing.
If you click the speed change button, the first time pressing Space will pause the game AND change the speed setting. Every further press on Space will switch the speed setting too but won't unpause the game.

https://user-images.githubusercontent.com/17579552/122139796-129b4700-ce4a-11eb-877e-4a1457ae4a40.mp4

**Comment by David-Goru** [comment]
Fixed in build 245
