### ISSUE TITLE
Last Transactions in new EconoView: Text not fully visible

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#202]
Build 57

The text in Last Transactions is not fully visible. If it has to be shortened to save space, there should at least be a tooltip to make it completely visible.

![grafik](https://user-images.githubusercontent.com/17579552/122210492-ff1dc980-cea5-11eb-84e3-a1362695c59f.png)

**Comment by jhovgaard** [comment]
Will be redesigned in Beta 7. Closing this.
