### ISSUE TITLE
Building Hiding when standing close, even if not blocking the view

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#203]
Alpha 4 - Build 59 

When leaving the first residential building the 2 buildings hide even if the camera is not going to be blocked by them. Happens on a few buildings but most noticeable on 17 ThirdStreet.

![YDzT8P](https://user-images.githubusercontent.com/44293115/122414736-462bbd80-cf7f-11eb-8591-0205f9bb432f.jpg)

**Comment by Gerwanese** [comment]
Not just when leaving, generally when you just get close to the building:

https://user-images.githubusercontent.com/17579552/122457697-375cff00-cfaf-11eb-8e68-bc1965594c6c.mp4

**Comment by David-Goru** [comment]
Fixed in build 870
