### ISSUE TITLE
Pedestrian Glitching while waiting at crossing

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#204]
Alpha 4 - Build 59

When more than 2 pedestrians are waiting at a road crossing and a third walk behind them it tries to walk as close to the edge of the road as possible, however as the other 2 pedestrians are in that space it just appears to glitch out, Spinning, Flickering and continuos animation playing.

Forgot to pause game while loading video recording tool, unable to get video.

**Comment by Gerwanese** [comment]
Could reporduce it yet. For me, they just push away each other. Maybe you caught a special situation where this pushing didn't work properly. We should have an eye on that.
