### ISSUE TITLE
Green area/arrow below shop item not turning when turning the item with mouse outside shop area

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#207]
Build: 60

If you turn an item in the shop while the mouse pointer is outside the shop area, the item will turn but the green area below and also the arrow (indicating the front) are not updated. They only update after you move the pointer inside the shop area.

Additionally, when placing the item again while the mouse pointer is outside the shop area, picking up another item will first show the green arrow of the previous item (seen in the middle of the video).

https://user-images.githubusercontent.com/17579552/122455667-f19f3700-cfac-11eb-9871-c42c323783ec.mp4

**Comment by David-Goru** [comment]
Fixed in the past
