### ISSUE TITLE
Can pick up and place one shop item while game is paused but not more

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#208]
Build 60

After pausing the game, I can pick up and turn/place one item. After placing it, I can't pick up any further items (not even the same). After resuming the game I can pick up any again.

I think when paused, you should either be able to pick any item or none, but not just one.

https://user-images.githubusercontent.com/17579552/122456308-b2bdb100-cfad-11eb-83d1-476908e60949.mp4

**Comment by David-Goru** [comment]
Fixed in the past
