### ISSUE TITLE
No reactions to mouse clicks for first seconds after leaving apartment

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#220]
Build 66

After leaving my apartment, mouse clicks are not registered for the first seconds.
It doesn't happens all the time but pretty often.

https://user-images.githubusercontent.com/17579552/122658347-666c9f80-d16c-11eb-9177-b77a45d21415.mp4

**Comment by jhovgaard** [comment]
Fixed after merging scenes.
