### ISSUE TITLE
No cashier at supermarket after end of my shift

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#227]
Build 66

After my shift ends, I can't buy food right away because there's no new cashier although the shop is still open.
Once I leave and reenter the shop, the new cashier is there.

![grafik](https://user-images.githubusercontent.com/17579552/122807526-fc6b0c00-d2cb-11eb-9729-433891196130.png)

**Comment by Gerwanese** [comment]
Build 106

Additionally now right after my shift the CashRegister shows "STOCK_COUNT" below the title.

[Build106-CashChaosAfterShift.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896857/Build106-CashChaosAfterShift.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127406274-8f6cbaa6-6f5b-4720-9896-da6767cb716f.png)

**Comment by David-Goru** [comment]
Fixed in the past
