### ISSUE TITLE
Bicycle "sunken" in front of house

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#230]
Build 66

As you can see, the bicycle is half sunken into the earth.

Besides, items like the bicycle or the blue box a few houses further down the road (third screenshot) are not hidden when the buildings are hidden. Not sure if that's a bug, so for now I don't open a separate one...

![grafik](https://user-images.githubusercontent.com/17579552/122812885-8fa74000-d2d2-11eb-8bc4-15beae3305aa.png)

![grafik](https://user-images.githubusercontent.com/17579552/122812908-9930a800-d2d2-11eb-932d-2c563363699d.png)

![grafik](https://user-images.githubusercontent.com/17579552/122812933-9fbf1f80-d2d2-11eb-9dfc-d020bfa4a456.png)

**Comment by David-Goru** [comment]
Fixed in the past
