### ISSUE TITLE
Placement Area in flat

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#234]
Alpha 4 - Build 67

The placeable area in the flat is a bit off. The grid is in the wall on the right-hand side, but a large gap on the left. Then in the right-hand room, the far right-hand column isn't closed. Would probably make sense to separate each placeable area per room instead of per building as then the placeable area can be adjusted to fit each room properly.

![image](https://user-images.githubusercontent.com/44293115/123103314-c9d92480-d42d-11eb-8c88-a2ab85d2ae05.png)

**Comment by Gerwanese** [comment]
It's similar in shops so I thought it would be normal, but definitely confirmed.

**Comment by jokoho48** [comment]
Fixed in the Mean while
