### ISSUE TITLE
Spawning and despawning of cars visible

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#244]
Build 69
Resolution: 1920x1200

First you can see a car spawning in my driving direction. It's not exactly spawned inside the lane but a bit off and has to correct.
Later on, you see two cars coming towards me and being despawned. It appears as if they were just spawned before but that's hard to tell.

Video was taking at crossing 4th Avenue / 2nd Street, looking towards 3rd Street.

https://user-images.githubusercontent.com/17579552/123333332-e797ae00-d541-11eb-90a6-5b5c0b9beb91.mp4

**Comment by jhovgaard** [comment]
Related to this, also be aware that the new harbor area is missing traffic routes causing vehicles to despawn when entering the area.

**Comment by jokoho48** [comment]
Fixed a while ago
