### ISSUE TITLE
Income Statement has no padding at the bottom

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#249]
Build 70

If the income statement is very long, it goes all the way to the bottom of the screen with no padding there. Although you can scroll, it still feels as if something would be "missing" at the bottom.

[IncomeStatement.txt](https://github.com/hovgaardgames/bigambitions-public/files/6719228/IncomeStatement.txt)

![grafik](https://user-images.githubusercontent.com/17579552/123493326-5e08de80-d61c-11eb-8c05-52802005e26c.png)

**Comment by David-Goru** [comment]
Fixed in build 264
