### ISSUE TITLE
Inventory count can be extremely hard to read on bright background

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#251]
Build 71

If the background is bright, it can be almost impossible to read the numbers of the inventory.

[NewStart-Build57.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750571/NewStart-Build57.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124185011-ab70ca00-daba-11eb-8ac6-a95f628d69ea.png)

**Comment by jhovgaard** [comment]
Fixed in build 731
