### ISSUE TITLE
Slow scrolling in cargo list

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#255]
Build 71

Scrolling in cargo list is very slow.
Same issue as for the other dialogs in #134 and #183 - might want to fix them all together.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750743/Build71.txt)

https://user-images.githubusercontent.com/17579552/124188503-a19d9580-dabf-11eb-9574-1c7041d137d2.mp4

**Comment by David-Goru** [comment]
Fixed in build 257
