### ISSUE TITLE
Options dialog (Save / Quit) opens behind cargo dialog

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#256]
Build 71

When cargo dialog is open and you click the options icon, the save/quit dialog opens behind the cargo dialog.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6750752/Build71.txt)

https://user-images.githubusercontent.com/17579552/124188699-e7f2f480-dabf-11eb-8f2c-ebe565beed1d.mp4

**Comment by David-Goru** [comment]
Fixed in build 257
