### ISSUE TITLE
Quick One Shop (14 Fourth Avenue): Looking at Job Board can cause player to exit building

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#262]
Build 73

When taking a look at the job board of Quick One Shop in 14 Fourth Avenue, it can cause the player to exit the building (seems to be depending on the camera angle) because he will stand right in front of the doors.

[Build71.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758760/Build71.txt)

https://user-images.githubusercontent.com/17579552/124361993-adf62f80-dc32-11eb-99cb-588377fc7da8.mp4

**Comment by David-Goru** [comment]
Fixed in the past
