### ISSUE TITLE
Number of boxes in cargo not readable for every second box

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#263]
Build 73

The cargo dialog of my van has a display issue with the number of boxes für every second box in the list (1st, 3rd).

[Build71-Shopping.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758778/Build71-Shopping.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124362352-97e96e80-dc34-11eb-8fea-488284a961d5.png)

**Comment by David-Goru** [comment]
Fixed in build 273
