### ISSUE TITLE
Wrong button label "Empty shelf" for DrinksFridge, no such button at all for SaladBar and MetalShelf

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#268]
Build 73

DrinksFridge has an "Empty shelf" button although it's not a shelf (maybe you could use a more generic label like "Remove content").
SaladBar and MetalShelf have no such button at all.

[Build71-FastFood.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758837/Build71-FastFood.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124363008-fd3f5e80-dc38-11eb-9da5-15d66109cdda.png)

**Comment by David-Goru** [comment]
Fixed in build 581
