### ISSUE TITLE
MetalShelf still showing content although stock is 0

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#270]
Build 73

Even if stock is 0, the metal shelf will still show items on it.

[Build71-GiftShop.txt](https://github.com/hovgaardgames/bigambitions-public/files/6758853/Build71-GiftShop.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124363304-bd797680-dc3a-11eb-89d4-9c9fc49e3e8b.png)

**Comment by David-Goru** [comment]
Fixed in the past
