### ISSUE TITLE
Metal shelf at appliance store filled with boxes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#283]
Build 75

The metal shelf at the appliance store is filled with boxes. Also the boxes are showing through the upper board.

[Build75-NoInterviews.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773043/Build75-NoInterviews.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124672698-c6c34700-deb7-11eb-8b54-187695ec6a53.png)

**Comment by David-Goru** [comment]
Fixed in build 256
