### ISSUE TITLE
Clothing racks in non-owned shops don't show type of clothes

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#287]
Build 75

In non-owned clothing shops the racks only show the label "ClothingRack" but not what type of clothes are on them.
Not very relevant in the game yet, but might be relevant later on if you have to buy clothes for yourself.

[Build75-ClothingLabels.txt](https://github.com/hovgaardgames/bigambitions-public/files/6773139/Build75-ClothingLabels.txt)

![grafik](https://user-images.githubusercontent.com/17579552/124675188-7ac6d100-debc-11eb-9c65-0a8607d65784.png)

**Comment by David-Goru** [comment]
Fixed in build 250
