### ISSUE TITLE
Using Mop: Cleaning condition displays wrong percentage

### ISSUE THREAD

**Issue by tomvbj** [hovgaardgames/bigambitions#301]
Build 76.

Very minor issue.

When you clean your floor the condition bar shows 100% while there is still dirt on the floor.

![Big Ambitions 7_9_2021 5_04_19 PM](https://user-images.githubusercontent.com/85610694/125098858-b4bfef00-e0d7-11eb-8d20-81bac50b1dd4.png)

**Comment by Gerwanese** [comment]
I think the 100% when there's still a bit of dirt left might be a rounding issue (probably happens more in larger buildings).
However there's also  a second issue: When I let my restaurant run in high speed mode, I could quickly see the dirt getting more and more but the condition staying at 99%. Once I started cleaning, it dropped to 89%.

[Build75.txt](https://github.com/hovgaardgames/bigambitions-public/files/6795678/Build75.txt)


https://user-images.githubusercontent.com/17579552/125171415-73514180-e1b4-11eb-9652-69635658a468.mp4

**Comment by David-Goru** [comment]
Fixed in the past
