### ISSUE TITLE
Pedestrians often get stuck on the sidewalk

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#308]
Build 78

Since this build it frequently happens that people are standing still on the sidewalk and are stuck. In the video (just after starting a new game) you can see 5 people being stuck.
I can even interview them, causing them to turn around for a short moment but still they will be stuck.

https://user-images.githubusercontent.com/17579552/125525103-68066f76-b4f7-4cc7-b59f-7f7053b75d43.mp4

**Comment by jhovgaard** [comment]
@Gerwanese can you check if this is still relevant? It only happens when the exit door is out of reach. I believe I've fixed them all aleady.

**Comment by jhovgaard** [comment]
Nevermind. It only happened with pedestrians having the furniture store as their target (it was unreachable).

Fixed in build 250
