### ISSUE TITLE
First day rent for business building + first day wage not registered in BizMan

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#315]
Build 78

Start a new game and rent a business building, starting a business.
The BizMan for the first day shows 0$ rent.
Probably this is caused by the rent being charged at 00:00 and thus being calculated for the next day, so it only makes a difference on the first day but is misleading in BizMan.

The same happens for the first day's wage for your employee, it will also only be registered 00:00 and as such count for the next day, although it was the wage for the previous day.

![grafik](https://user-images.githubusercontent.com/17579552/125681622-ec217cc4-679c-441d-8991-e0921e6d6aa5.png)

**Comment by David-Goru** [comment]
Fixed in build 725
