### ISSUE TITLE
Customers in shops can push others in queue away when leaving, sometimes leaving them stuck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#316]
Build 78

Customers sometimes after paying push other people in the queue back to get out of the shop. Sometimes the queue will "repair" itself, sometimes it will be stuck afterwards.

[Build78-PushMe!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6818629/Build78-PushMe.txt)

https://user-images.githubusercontent.com/17579552/125685257-ba3054e7-206d-44a7-8ee3-c84903e82992.mp4

**Comment by David-Goru** [comment]
Fixed in the past
