### ISSUE TITLE
Retail Prices allow to enter small values with comma only, while for display dot is used as decimal separator

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#321]
Build 78

Generally in the game, the dot is used as decimal separator and comma as thousands separator, which is the standard in USA.
When you're changing the retail prices in your shop however, you can only enter a comma as decimal separator.

[Build78-StreetWalker.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819036/Build78-StreetWalker.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125695626-95069b53-4d68-462f-b79e-0cedf398d46d.png)

**Comment by jhovgaard** [comment]
TMPro is using the player's computer's settings for this. On my machine, for example, I can only use a dot.

We would need to create a custom implementation of TMPro decimal validator that also allows copy/pasting etc. Quite a big task.

As we haven't received any actual player feedback (you're not a player Daniel :D) and considering the size of the task, I'm closing this for now.
