### ISSUE TITLE
"soon runs out of" message for clothes shows up right from the start

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#324]
Build 78

It seems that the treshold for the "soon runs out of ClassicCheapMaleClothing" message is at 50 (or at least 45). The box of those items however only contains 50, so if you stock up your clothing rack with one box you immediately run into the message.

[Build78-Emptyployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819175/Build78-Emptyployee.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125699555-2c7eb955-c2a9-46a1-a46c-b0e3adccad9f.png)

**Comment by David-Goru** [comment]
Fixed in build 295
