### ISSUE TITLE
The first time opening BizMan after loading a game, "Insight" doesn't immediately get underlined if you're indoors

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#325]
Build 78

When you open the BizMan for the first time after loading a savegame and select a business, the "Insight" tab title will not be underlined in white if you are indoors. If you are outdoors, it will immediately be correct.
Any further time you open BizMan it will be correct.

In the video, you will first see it working correctly when loading a savegame where I'm outdoors. Afterwards you see two savegames being loaded where I'm indoors, both showing the issue.

[Build78-Emptyployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819223/Build78-Emptyployee.txt)

https://user-images.githubusercontent.com/17579552/125701129-60e562c6-52f3-450e-9551-5671ddf9ddcb.mp4

**Comment by David-Goru** [comment]
Fixed in build 268
