### ISSUE TITLE
Percentage bars moving when opening a panel containing them

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#326]
Build 78

When you open any panel containing a percentage bar, it will move from the middle to the correct value.
For example if the value is below 50%, you will see a red bar moving down. If the value is above 50%, you will see a green bar moving up.

Issue found in:
- Employees app: Job Satisfaction
- BizMan app: Insight (all 4 bars below "Overall Satisfaction")
- Interview Lite app: Research Accuracy

[Build78-Emptyployee.txt](https://github.com/hovgaardgames/bigambitions-public/files/6819248/Build78-Emptyployee.txt)

https://user-images.githubusercontent.com/17579552/125701600-d2990346-4fdf-4d7d-8930-8ea6ab1cc548.mp4

**Comment by David-Goru** [comment]
Fixed in build 256
