### ISSUE TITLE
More than two workplaces in one business will cause the additional places to be out of the screen.

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#328]
Build 78

If there are more than two workplaces, the additional ones will be out of the screen. The third one is still partly visible, but it's not possible to completely bring it into view.

[Build78-PaymentOptionsBaby!.txt](https://github.com/hovgaardgames/bigambitions-public/files/6825492/Build78-PaymentOptionsBaby.txt)

![grafik](https://user-images.githubusercontent.com/17579552/125839624-8e2889ad-af37-4d3c-b815-0ffac20e0e67.png)

**Comment by David-Goru** [comment]
Fixed in build 264
