### ISSUE TITLE
Customers leaving the shop are walking a curve instead of straight to the door

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#333]
Build 83

When customers are leaving the shop, they don't walk straight to the door but in a curve, as if they wanted to get to the shopping baskets.

[Build75-GiftshopNoCustomers.txt](https://github.com/hovgaardgames/bigambitions-public/files/6854790/Build75-GiftshopNoCustomers.txt)

https://user-images.githubusercontent.com/17579552/126473269-3552444a-a7aa-4f72-bba3-2773a51d7674.mp4

**Comment by jhovgaard** [comment]
@Gerwanese I believe this has been fixed in the meantime.
