### ISSUE TITLE
Prices displayed rounded to full numbers in stores

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#334]
Alpha 4 - Build 85

The price in the fridge shows as $6 however then goes to $5.5. When purchasing the price is the total it displays in the basket of $5.5.
Looks as though they display price can only show full numbers
![H26P1M](https://user-images.githubusercontent.com/44293115/126497756-e9b1b903-0bc2-433b-8a21-07efaec16be2.png)

**Comment by Gerwanese** [comment]
Confirmed. No savegame needed, just start a new game and go to the supermarket.

**Comment by David-Goru** [comment]
Fixed in build 256
