### ISSUE TITLE
People can get pushed into wall at 7/9 Third Street

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#335]
Alpha 4 - Build 85
You can push people in between 9th and 7th Third Street, you can push people by running up behind them and they just get pushed by you, if you then run them from 11th third street towards 9th and7th against the buildings they will slip in between the 2 buildings, They will then continue there initial path but walk through the building (As seen in the photo)
![8AdqIE](https://user-images.githubusercontent.com/44293115/126499525-33fcc3f9-612f-419b-8ca4-d1b2947751dc.png)
Sometimes they will just get stuck at the gap and only show up when you hide the 7th third street building.
This is the gap that they get pushed through
![yThemA](https://user-images.githubusercontent.com/44293115/126499992-3f80446d-5230-4cc8-847b-66fa4888c567.png)

Hard to reproduce (Video - Once I redo it)

**Comment by adameg2305** [comment]
A basic video to show, if the npc is static it is a lot easier. this time they only stood in that spot, if they were already walking they would walking into the middle of the building
https://user-images.githubusercontent.com/44293115/126501667-a239d62d-f4bb-437a-b7c6-744436d69f9f.mp4

**Comment by jhovgaard** [comment]
@Gerwanese Can you confirm this isn't working anymore?
