### ISSUE TITLE
Multi-line error message doesn't fit into red box

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#337]
Build 85

If an error message (the one on the top right, not the error console) exceeds the line and is wrapped, the containing red box is too small.
Besides, the comma in this particular message is wrong. :)

[Build78-FreeGiftsForEveryone.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856243/Build78-FreeGiftsForEveryone.txt)

![grafik](https://user-images.githubusercontent.com/17579552/126500246-22f3a5bb-9ca9-439b-be78-fdd140cfd0c7.png)

**Comment by David-Goru** [comment]
Fixed in build 257
