### ISSUE TITLE
BizMan: White underline for "Settings" still shown after shutting down business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#339]
Build 85

If you shut down a business, the white underline for the "Settings" tab will still be shown.

No savegame needed, just start a new game, rent any small shop building, start a business and immediately terminate it again.

https://user-images.githubusercontent.com/17579552/126503674-826f0606-f409-4c76-a533-0ac2c3be693f.mp4

**Comment by David-Goru** [comment]
Fixed in build 295
