### ISSUE TITLE
Uncle Fred Message not fitting in box

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#346]
Alpha 4 - Build 85
Uncle Freds message doesn't fit in the box
![IvSMcg](https://user-images.githubusercontent.com/44293115/126511470-49ba8129-829c-4560-b6b0-938b97f87264.png)

**Comment by Gerwanese** [comment]
Confirmed. It's only this one step, all others are short enough.

[Build78-MessageTLDR.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856953/Build78-MessageTLDR.txt)

**Comment by David-Goru** [comment]
Fixed in build 295
