### ISSUE TITLE
New car dealer shows different doors from inside and outside

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#347]
Build 85

The new car dealer at 70 Third Street has a small steel door from outside but two large wooden doors from inside.
Also the windows don't fit.

[Build85-MyPreferredDealer.txt](https://github.com/hovgaardgames/bigambitions-public/files/6856834/Build85-MyPreferredDealer.txt)

https://user-images.githubusercontent.com/17579552/126513542-83e5a5a8-59b2-406f-9b6d-3da3eaafa137.mp4

**Comment by jhovgaard** [comment]
We'll never get perfectly synced exterior or interiors. At least with current budgets :) Closing this.
