### ISSUE TITLE
EconoView showing income of 10 sold CheapGifts although in BizMan stock has just reduced by 9.

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#357]
Build 106

After the first day of my new gift shop:

Stock:
CheapGift: 191 (9 sold) - price $10
Paperbags: 994 (6 sold)

Purchase prices (drive-in wholesales):
CheapGift: $900 / 200pc ($4.5 per item)
Paperbags: $450 / 1000pc ($0.45 per item)

What doesn't add up in BizMan:
- "Sales" showing income of $100 for CheapGift which would mean 10 sold items
- "Resources" showing expenses of $45 for CheapGift matching the 10 items
- Paperbags are not listet at all in the "Resources" of BizMan so you get a wrong impression of the actual result

Besides the problems in BizMan, is it by purpos that not every customer gets a paper bag?

[Build106-MathLesson.txt](https://github.com/hovgaardgames/bigambitions-public/files/6896830/Build106-MathLesson.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127405285-070da2be-7561-42bf-9e86-79ea577467d3.png)

**Comment by David-Goru** [comment]
Fixed in build 600
