### ISSUE TITLE
EconoView: Probably rounding issue in daily results

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#360]
Build 120

The last day's profit of my gift store shows -$79 although it should have been -$80.
I guess it's a rounding issue (theoretically it could also be a bug that the wrong store's result is shown, as my burger restaurant got -$79 as well but I don't think it's the case here).

[Build106-EconoViewBugs.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903498/Build106-EconoViewBugs.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127562729-9b908bf8-d8f8-483a-9682-e5f6c7f8219b.png)

**Comment by David-Goru** [comment]
Fixed in the past
