### ISSUE TITLE
Newly purchased car placed on the sidewalk and rolling by itself

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#365]
Build 120

After buying a new car, it will be placed on the sidewalk and rolling by itself.

[Build106-BuyTheRollingThing.txt](https://github.com/hovgaardgames/bigambitions-public/files/6903671/Build106-BuyTheRollingThing.txt)

https://user-images.githubusercontent.com/17579552/127567551-13d5131e-494a-4bc2-a7e5-a876a2ba06a5.mp4

**Comment by jhovgaard** [comment]
Fixed in build 279 (or earlier)
