### ISSUE TITLE
Pushing cars around

### ISSUE THREAD

**Issue by Abdullamousawi** [hovgaardgames/bigambitions#374]
Build 123 - Alpha 5

I'm able to push vehicles around.. Hulk reference? :P Speed was set to x2 and the car was moving.
![image](https://user-images.githubusercontent.com/68964428/127700859-45a2f79d-2fcc-42b9-81ca-62cb3a12734b.png)

**Comment by jhovgaard** [comment]
@Gerwanese should this be closed?

**Comment by Gerwanese** [comment]
@jhovgaard It's not that bad anymore, but sometimes vehicles still get lifted up a little bit. So I think it's not 100% fixed.

**Comment by jhovgaard** [comment]
Should be fine now! Fixed in build 279 (or earlier)
