### ISSUE TITLE
Massive lag when walking Third Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#377]
Build 123

When walking Third Street, there's always a massive lag / the player getting "stuck" at the same spots. It doesn't matter whether you play on double or normal speed. Only seems to be that one street (others have sporadic very short lags, but not that much).
During the video, the mouse button was permanently kept pressed.

[Build123-ThirdStreet.txt](https://github.com/hovgaardgames/bigambitions-public/files/6909730/Build123-ThirdStreet.txt)

https://user-images.githubusercontent.com/17579552/127705019-1de9dd50-0478-4a87-9b4c-34ba3d1d134a.mp4

**Comment by jhovgaard** [comment]
@Gerwanese I think this can be closed :D
