### ISSUE TITLE
Cant get out of building if a hand cart is left in the door way

### ISSUE THREAD

**Issue by damianshiell** [hovgaardgames/bigambitions#389]
![image](https://user-images.githubusercontent.com/63842183/127739527-4d8966de-c8b1-42a8-904c-099874ade881.png)

Left the hand cart in the door way and cant pick it up to move it out of the way so will slowly starve to death in my new gift shop :)

**Comment by Gerwanese** [comment]
@damianshiell How did you place the hand cart there? Did you click "park vehicle" immediately after entering the building? And which building (street/number) is this?

This used to be a bug but was fixed a while ago. Seems the fix wasn't 100%, so it needs a bit more investigation.

**Comment by jhovgaard** [comment]
Closed until we can reproduce.

**Comment by jhovgaard** [comment]
David was able to reproduce it. We're looking into it!

**Comment by David-Goru** [comment]
Fixed in build 249
