### ISSUE TITLE
Hidden road block at corner 6th Avenue / 1st Street

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#398]
Build 130

At the corner of 6th Avenue and 1st Street there's a hidden road block.
It's the same like #364  but at a different location. As #364 is closed to be fixed with build 131, I create this separate bug for the new location for documentation although it *might* be fixed with build 131 as well (has to be retested once the build is available).

[Build130-DontBlockMe.txt](https://github.com/hovgaardgames/bigambitions-public/files/6912938/Build130-DontBlockMe.txt)

https://user-images.githubusercontent.com/17579552/127777249-b69041e5-9e2a-4739-805b-ec89eedb2d9e.mp4

**Comment by adameg2305** [comment]
Alpha 5 - Build 132
Also at in the same places:
6th Avenue 3rd Street
https://user-images.githubusercontent.com/44293115/127905472-aea2cecb-c533-40a3-8bdc-216aa35e102c.mp4

6th Avenue 2nd Street
https://user-images.githubusercontent.com/44293115/127905548-b918c47e-8351-4fb1-999b-7e606f03eb0e.mp4

Also still at 6th Avenue 1st Street

**Comment by David-Goru** [comment]
Fixed in the past
