### ISSUE TITLE
Hand Truck can block way between appliances

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#400]
Build 130

The hand truck can be placed in a way that it's impossible to get past it but also impossible to pick it up.
Interestingly, it was possible to pass by it with a box in my hands to fill up the frozen food.

Looking at this and also the issue #389, I think a general solution is needed. Suggestion: No matter from which side you approach the hand truck after clicking on it, once you're standing next to it it will move into your hands and turn into the right direction.

[Build130-HandTruckRefusal.txt](https://github.com/hovgaardgames/bigambitions-public/files/6912988/Build130-HandTruckRefusal.txt)

https://user-images.githubusercontent.com/17579552/127778329-557f690f-a226-4852-9129-510ba7a19d6e.mp4

**Comment by David-Goru** [comment]
Fixed in build 249
