### ISSUE TITLE
Wording: "Condition" on mop actually shows "Cleanliness"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#403]
Build 130

When holding a mop you'll the the "Condition" displayed. This is the wrong wording.
The "Condition" is shown when driving the car to indicate the condition of the car.
In the BizMan at Customer Satisfaction there's a rating for "Cleanliness".
The correct wording when using a mop would thus be "Cleanliness" as it doesn't indicate the condition of the mop but rather the cleanliness of the shop's floor.

[Build130-MopTheCleanlinessAway.txt](https://github.com/hovgaardgames/bigambitions-public/files/6913037/Build130-MopTheCleanlinessAway.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127779081-20698ac5-0256-4dd1-98d1-094ddd7c6570.png)

**Comment by David-Goru** [comment]
Fixed in build 295
