### ISSUE TITLE
Progress bar not showing proper progress

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#407]
Alpha 5 - Build 130

As shown in the image basic management course is 100% complete but the progress bar shows around 90% mark.
![LGgDBA](https://user-images.githubusercontent.com/44293115/127899017-72717efe-78c3-4bca-8c98-f55179e748b6.png)

**Comment by adameg2305** [comment]
[130ProgressBar.txt](https://github.com/hovgaardgames/bigambitions-public/files/6918566/130ProgressBar.txt)

**Comment by adameg2305** [comment]
Also shows incorrect progress on the vehicle toolbar
![44sNdh](https://user-images.githubusercontent.com/44293115/127905877-9adab2db-e7dd-431b-b18c-ef0ca280db66.png)

**Comment by David-Goru** [comment]
Fixed in build 257
