### ISSUE TITLE
No scrolling in BizMan with many businesses

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#410]
Build 132

If you own many businesses you can't see all of them in BizMan because there's no scrollbar.

[Build130-CrowdedBizMan.txt](https://github.com/hovgaardgames/bigambitions-public/files/6919255/Build130-CrowdedBizMan.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127915053-d04942a1-9e94-44f4-810a-1e76a961e4b4.png)

**Comment by David-Goru** [comment]
Fixed in build 248
