### ISSUE TITLE
1st Street and 3rd Avenue: balcony and marquee over sidewalk acts as wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#411]
Build 132

Most of the block issues were fixed through bug #165 - there's still one building not fixed on 1st Street however:

[Build130-FirstStreetFirstWorldProblems.txt](https://github.com/hovgaardgames/bigambitions-public/files/6919304/Build130-FirstStreetFirstWorldProblems.txt)

![grafik](https://user-images.githubusercontent.com/17579552/127916331-fa239ec1-d96c-4f32-853f-b7b01e9dba28.png)

https://user-images.githubusercontent.com/17579552/127916540-1bb57c03-24b9-4448-929d-dd846b32d83f.mp4

**Comment by Gerwanese** [comment]
Additionally, the marquee of the large building at the corner 3rd Avenue / 3rd Street / 4th Street has the same problem on the sides of 3rd Street and 3rd Avenue. Only on the side of 4th Street it's correct.

[Build139-BuildingsNotHidingProperly-3rdAvenueLargeBuilding.txt](https://github.com/hovgaardgames/bigambitions-public/files/6945216/Build139-BuildingsNotHidingProperly-3rdAvenueLargeBuilding.txt)


https://user-images.githubusercontent.com/17579552/128504434-d5e56a37-f17e-4a09-b1c3-d7cbe9ccbf8a.mp4

**Comment by David-Goru** [comment]
Fixed in build 281
