### ISSUE TITLE
6th avenue 2nd street in the middle building incorrect floor

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#418]
Alpha 5 - Build 132

6th avenue 2nd street in the middle building has the incorrect floor when the building is hidden compared to all other buildings
![Abarp4](https://user-images.githubusercontent.com/44293115/128071093-705d1bca-b165-44ee-991a-425100090671.jpg)

(Same building also mentioned in #197 with a separate issue)

**Comment by Gerwanese** [comment]
Issue should be double checked once #197 is fixed.

**Comment by David-Goru** [comment]
Fixed in the past
