### ISSUE TITLE
Apartment rent displayed as $64 but only charged $63.8

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#437]
Build 139

The apartment rent of the initial apartment should be $64, however only $63.8 is charged and the player's money only reduced by $63.

[Build139-ApartmentDiscount.txt](https://github.com/hovgaardgames/bigambitions-public/files/6941561/Build139-ApartmentDiscount.txt)

https://user-images.githubusercontent.com/17579552/128417996-72adbe78-f3fd-4386-a622-18ace47d2a2c.mp4

**Comment by David-Goru** [comment]
Fixed in Build 250
