### ISSUE TITLE
"Sandy" floors visible at many buildings

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#441]
Build 139

At many buildings you can see a yellow "sandy" floor in front.
At even more buildings you can see it when they're hiding (sometimes on the building floor, sometimes a thin yellow line in between buildings).
For more variation, on 5th Avenue between 3rd and 4th Street there's green/grassy floor instead of yellow/sandy.

[Build139-SandyStreet.txt](https://github.com/hovgaardgames/bigambitions-public/files/6945239/Build139-SandyStreet.txt)

![grafik](https://user-images.githubusercontent.com/17579552/128504714-5dca471c-0e48-4fda-a765-e96d79386fe7.png)

![grafik](https://user-images.githubusercontent.com/17579552/128504877-a9c58af5-0400-415e-900c-d42ac0f47259.png)

![grafik](https://user-images.githubusercontent.com/17579552/128505210-1d916162-889a-44d0-8d70-d8e3bb3a97f4.png)

**Comment by jhovgaard** [comment]
Fixed once upon a time
