### ISSUE TITLE
Wrong behaviour when clicking on items while holding a paperbag

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#449]
Build 153

When holding a paperbag and clicking other items, the error messages are not quite correct:
- Clicking a mop: No message at all
- Clicking shopping baskets: Message "This resource doesn't fit into this type of shelf" (technically correct, but not much helpful for players)
- Clicking on clothing rack: "This item is already holding <ClothingType>" (correct but a bit misleading, as the player probably didn't want to place the bag there but take an item)
- Clicking on a cash register: Paperbag disappears including its contents (it is NOT added to cash register stock count however)

[Build153-PaperbagFun.txt](https://github.com/hovgaardgames/bigambitions-public/files/6951098/Build153-PaperbagFun.txt)

https://user-images.githubusercontent.com/17579552/128638511-9ecc5c92-9298-4f69-8a4a-55684e686e4b.mp4

**Comment by David-Goru** [comment]
Fixed in the past
