### ISSUE TITLE
Own money always showing green "$1.57K" no matter how much you earn / lose

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#455]
Build 153

In the info bar on top of the screen, besides the own money it always show a fixed value ($ 1.57K) that will never change.

You can start a new game and it will already be there.

[Build153-WrongMoneyDisplay.txt](https://github.com/hovgaardgames/bigambitions-public/files/7017227/Build153-WrongMoneyDisplay.txt)

https://user-images.githubusercontent.com/17579552/130130657-75068701-e62a-4831-b902-a981a7f1bff5.mp4

**Comment by David-Goru** [comment]
Fixed in build 270
