### ISSUE TITLE
Subway: GarmentDistrictStation2 and 3 entrance/exit besides the actual entrance

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#461]
Build 169

The entrance/exit of GarmentDistrictStation2 as well as GarmentDistrictStation3 is a little bit besides the actuall entrance location.
The same for HellsKitchenStation2 (see also bug #462).

[Build169-GarmentDistrictStation2Entrance.txt](https://github.com/hovgaardgames/bigambitions-public/files/7061476/Build169-GarmentDistrictStation2Entrance.txt)

https://user-images.githubusercontent.com/17579552/131004942-80fa0c8f-9f47-4718-bdbe-d79cff9413e1.mp4

**Comment by jhovgaard** [comment]
Fixed in build 270
