### ISSUE TITLE
[Low Priority] Car lights only displaying 1 source and not lining up correctly

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#495]
Alpha 5 - Build 173 [Low Priority]

The lights for all cars and vans only show as 1 light source, but they all have 2 headlights, the light also appears too far away from the actual headlight.
![2to3pF](https://user-images.githubusercontent.com/44293115/131222770-7d249e4c-0fa9-4c2f-bb7e-354c80c2d594.png)

**Comment by jhovgaard** [comment]
@jokoho48 @Gerwanese @adameg2305 We could of course add an additional light source, but it will be quite expensive.

Looking at this drone footage, it's often hard to actually see the two beams: https://youtu.be/DslTxXsDLsw?t=1902

What are your thoughts?

**Comment by jokoho48** [comment]
We could try to find and add a Lightcookie to fake it. with 1 Light Source

**Comment by Gerwanese** [comment]
I personally don't mind, you could even leave it like it currently is or maybe make the light source wider so that it doesn't only seem to start from in between the lights but from the whole car front.
But cookies sound delicious and food is always my favourite solution.

**Comment by jokoho48** [comment]
Fixed in Build 294
