### ISSUE TITLE
Loan payment shows 5 decimal places when deducted

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#511]
Build 175

At midnight when paying the bank loan, it will show 5 decimal places.
In this example I should pay $49 per day, but the red number shows -$48,77685 (besides, a comma is used here instead of the decimal point).

[Build175-LoanPayment.txt](https://github.com/hovgaardgames/bigambitions-public/files/7071564/Build175-LoanPayment.txt)

![grafik](https://user-images.githubusercontent.com/17579552/131232181-870549ff-55e3-4238-9557-ddb6db1570cc.png)

**Comment by David-Goru** [comment]
Fixed in build 250
