### ISSUE TITLE
NPC cars hitting player's car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#527]
Build 184

The NPC cars are not always stopping for the player's car anymore. Especially when the player's car is not in the middle of a lane, they will just run into it and push it away.

See here for examples: https://community.bigambitionsgame.com/t/cars-hitting-me-while-trying-to-park/421

[Build184-CarMadness.txt](https://github.com/hovgaardgames/bigambitions-public/files/7094594/Build184-CarMadness.txt)

In the savegame, you can just and walk around until generated cars try to get around the corner (coming from 3rd Street / El Gato). They will happily run into you. 
I had to walk to the opposite site of the crossing to get cars generated from 3rd Street.

**Comment by jhovgaard** [comment]
@jokoho48 I think we need a custom behavior to resolve this. 

An option could be a large right-hand sided trigger collider only detecting player vehicles. If player vehicle is present and current speed is below 5 kmh we hold back the vehicle.

We could use Physics.BoxCast for performance. Thoughts?

**Comment by jhovgaard** [comment]
Fixed in Build 603
