### ISSUE TITLE
Drive-In Wholesales store: Wrong door used for entering and exiting

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#53]
Build 12
When entering the Drive-In Wholesales store, no matter through which door I drive, inside I will always be at the wrong side (where the counters are which should be the exit).
When leaving the store, I always get out on the wrong side as well.

https://user-images.githubusercontent.com/17579552/116482198-f7b64880-a884-11eb-87d5-0c412a6d2202.mp4

**Comment by jhovgaard** [comment]
Fixed in some build

**Comment by Gerwanese** [comment]
Only 50% fixed. Entering works well for me, exiting still on the wrong side.
I tried exiting backwards as well, unfortunately doesn't change anything. ;)

https://user-images.githubusercontent.com/17579552/120249517-784cd800-c27b-11eb-9c1b-05fdc9e1e1cb.mp4

**Comment by David-Goru** [comment]
Fixed in the past
