### ISSUE TITLE
Tutorial partly hiding after finishing first tasks

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#545]
Build 208

After finishing the first two tasks, the tutorial is partly hiding and only a small bit is visible.

What I did after starting the game:
- Walk to supermarket
- Accept job
- Buy 3 fresh food (but not eating yet)
- Rent apartment
- Sleep

It's back again after leaving the apartment.

[Build208-TutorialHiding.txt](https://github.com/hovgaardgames/bigambitions-public/files/7272279/Build208-TutorialHiding.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135732660-199d5888-b688-4df7-9785-71004968cffa.png)

**Comment by jhovgaard** [comment]
We fixed this sometime in the past. Was related to merging of scenes.
