### ISSUE TITLE
Possible to place cash register through the wall

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#558]
Build 212

The cash register can be placed partly through the wall.

[Build212-CashRegisterPlacement.txt](https://github.com/hovgaardgames/bigambitions-public/files/7281532/Build212-CashRegisterPlacement.txt)

![grafik](https://user-images.githubusercontent.com/17579552/135930163-554f004f-c68a-45f2-9202-d480add070bd.png)

**Comment by jokoho48** [comment]
Fixed in Build 213.

**Comment by Gerwanese** [comment]
Not 100% fixed, it can still be with the edge in the wall. Probably because the door frame is not an "obstacle".
I think it would be okay to leave it this way, but it needs a decision. ;)

![grafik](https://user-images.githubusercontent.com/17579552/136277137-1a7a6ea3-516b-4034-b5c9-727bbc0eb603.png)

**Comment by jhovgaard** [comment]
Looks like this has been fixed in the meantime. Impossible to get close to the wall now:

https://user-images.githubusercontent.com/1388347/146353253-0176ec97-a900-4fa3-9d1d-ba9ff8a82472.mp4
