### ISSUE TITLE
4th Ave / 3rd Street: Truck blocking traffic

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#559]
Build 212

I could see this several times already - at the corner 4th Ave and 3rd Street (where the appliance store is), turning trucks will
a) cut the sidewalk
b) get stuck because they can't turn all the way when a car is waiting at the traffic light in 3rd street already.

No savegame attached because traffic is newly spawned after loading anyways.

![grafik](https://user-images.githubusercontent.com/17579552/135931040-956e1a6f-a457-4e73-a4b8-47bec83992c8.png)

**Comment by David-Goru** [comment]
Fixed in build 285
