### ISSUE TITLE
Voogle Maps opens all the way zoomed in after starting a new game or loading a savegame

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#579]
### Build number

220

### Bug description

When starting a new game or loading a savegame, the first time Voogle Maps will be opened all the way zoomed in and I have to zoom out.
Afterwards during the session the map will keep the previous setting, so it happens only initially.

My preference would be to always start zoomed out.
Alternative would be to save the last zoom setting with the savegame.

### Steps to reproduce the bug

Load a savegame or start a new game, then open the map.

**Comment by David-Goru** [comment]
Fixed in build 295
