### ISSUE TITLE
No light from subway stations at night

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#586]
### Build number

222

### Bug description

The subway stations have two light poles in front of their entrance, however they don't have any light at night.

### Savegame file

[Build222-SubwayLight.txt](https://github.com/hovgaardgames/bigambitions-public/files/7330868/Build222-SubwayLight.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/136977236-8151658b-ff01-493c-9554-51762578230e.png)

**Comment by David-Goru** [comment]
Fixed in build 256
