### ISSUE TITLE
Interior Designer colours entire corner not one section

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#592]
### Build number

223

### Bug description

When choosing the colour for a new wall and you try to colour the corner it colours the entire corner instead of just one section like the rest of the building

### Screenshots or videos

![Big_Ambitions_790M6yVfjv](https://user-images.githubusercontent.com/44293115/136985367-89fba27c-efa8-4b7c-9c0a-18f67b6b04b9.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 293.
