### ISSUE TITLE
Can work with hand truck

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#596]
### Build number

223

### Bug description

You can work while you are holding a hand truck, 

### Steps to reproduce the bug

Pick up a hand truck
Go to the store you work at
At the beginning of your shift start work
You are now working while holding the hand truck

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/136991821-b41909dc-85bf-4081-ab69-d485c41c14e5.png)

**Comment by David-Goru** [comment]
Fixed in build 256
