### ISSUE TITLE
Clicking desk while holding handtruck displays 2 messages

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#597]
### Build number

223

### Bug description

Linked to #596 when holding the hand truck and you click on the cashier desk it displays the work and purchase screens

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/136992170-d7595f10-5c14-4840-8c76-8b728c074116.png)

**Comment by jokoho48** [comment]
Fixed in Build 234
