### ISSUE TITLE
Checkout counter at Appliance Store and Metro Wholesales facing wrong direction

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#610]
### Build number

227

### Bug description

The checkout counter at the appliance store across of El Gato is facing the wrong direction. Customers squeeze in between counter and window, coming from the door side.

### Savegame file

[Build227-ApplianceStore.txt](https://github.com/hovgaardgames/bigambitions-public/files/7340918/Build227-ApplianceStore.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/137202956-90702350-82a2-4cbb-bc34-ea639df7d70a.png)

**Comment by Gerwanese** [comment]
Same for Metro Wholesales:
![grafik](https://user-images.githubusercontent.com/17579552/137204565-bdf5f145-0033-4fbf-a264-0d75d5db3ba6.png)

**Comment by David-Goru** [comment]
Fixed in build 285
