### ISSUE TITLE
Driving in drive-in wholesales zooms in too much

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#625]
### Build number

228

### Bug description

When driving in the drive-in wholesales store, the camera will zoom in even more than when walking (when leaving the car it will zoom out a bit), making it almost impossible to find the right items.

### Savegame file

[Build227-ZoomInWholesales.txt](https://github.com/hovgaardgames/bigambitions-public/files/7347394/Build227-ZoomInWholesales.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/137348091-e75fc1ec-ddfb-4b5a-be67-6e7664ca9b5a.png)

**Comment by jokoho48** [comment]
Fixed in Build 284
