### ISSUE TITLE
Missing scrollbar in upcoming tasks / objectives

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#627]
### Build number

228

### Bug description

If objectives and tasks are too many, they will expand behind the "Submit Feedback" button and Uncle Fred's pretty face, so you can't read the lower items anymore.

### Savegame file

[Build227-TooManyTasks .txt](https://github.com/hovgaardgames/bigambitions-public/files/7348271/Build227-TooManyTasks.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/137370857-49a5854b-e39b-46d6-bba4-54d88afc8af1.png)

**Comment by David-Goru** [comment]
Fixed in build 249
