### ISSUE TITLE
Wrong Spacing for Street Lights

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#631]
### Build number

229

### Bug description

The lights are too close together compared to the rest of the lights. 
So far only noticed on:
13th Third Street

### Screenshots or videos

![Big_Ambitions_XrVAwSzQEa](https://user-images.githubusercontent.com/44293115/137377407-1a49a417-fd71-4cb1-a66b-fb353e058cbb.jpg)

**Comment by David-Goru** [comment]
Fixed in the past
