### ISSUE TITLE
Madame Ikea-Tussauds: People get stuck at Ikea when picking up any box

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#636]
### Build number

232

### Bug description

All generated people at Ikea who picked up a box are stuck right afterwards.

### Savegame file

[Build227-IkeaSleep.txt](https://github.com/hovgaardgames/bigambitions-public/files/7348998/Build227-IkeaSleep.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/137385631-cb69682d-61cd-42d9-bbcb-07c3dc0c2249.mp4

**Comment by jhovgaard** [comment]
Fixed in build 233

**Comment by Gerwanese** [comment]
Fixed in other shops but the issue is back / still there inside Ikea (build 242).

[Build242-IkeaStuck.txt](https://github.com/hovgaardgames/bigambitions/files/7446715/Build242-IkeaStuck.txt)

https://user-images.githubusercontent.com/17579552/139535811-ff4a3957-bf7b-4746-b3df-5c27a0b16db9.mp4

**Comment by jokoho48** [comment]
Fixed in Build 244
