### ISSUE TITLE
"Customers over time" in BizMan showing erroneous graph for yesterday

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#642]
### Build number

233

### Bug description

If you switch the graph in BizMan for a business to yesterday, it won't be displayed correctly anymore.
In my example, the dot for 5 is way above the 5 line.
For very low numbers, it can even happen that you got two lines with the same number (for example 1, 2, 2, 3). Probably that's because internally it's 0.8, 1.6, 2.4, 3.2 and then rounded.

### Savegame file

[Build227-LiquorStoreStartWork.txt](https://github.com/hovgaardgames/bigambitions-public/files/7369221/Build227-LiquorStoreStartWork.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/137823375-6f1402d3-ded0-473d-af03-770d53f016e7.png)

**Comment by David-Goru** [comment]
Fixed in build 267
