### ISSUE TITLE
Low amount of pedestrians and vehicles after exiting building

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#643]
After exiting a building the streets are empty.

We need a custom spawn radius point when inside buildings for both PedestrianSpawner and TrafficAiController.

**Comment by jokoho48** [comment]
Partially fixed in Build 237. PedestrianSpawner now uses the Entrance door if the Player is Inside of building

**Comment by Gerwanese** [comment]
Fixed for cars, but pedestrians are still all gone when leaving a building.
Build 242

**Comment by jhovgaard** [comment]
Fixed in build 250
