### ISSUE TITLE
Switch from Navmesh to A* Pathfinding

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#646]
### Build number

233

### Bug description

Hidden collider is causing weird path finding

### Steps to reproduce the bug

Walk towards 4th avenue.

### Savegame file

[Build 233 - Weird collider.txt](https://github.com/hovgaardgames/bigambitions-public/files/7372352/Build.233.-.Weird.collider.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/1388347/137892567-0ec0156b-53c7-4d84-90f6-0bb795179eb2.mp4

**Comment by jokoho48** [comment]
Fixed
