### ISSUE TITLE
Mac: Screen turning black when close to a non-finished area

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#649]
### Build number

234

### Bug description

[dehp3000](https://community.bigambitionsgame.com/t/alpha-7-is-finally-making-its-way-to-you/477/12?u=gerwanese):
> I have the Mac Version build 234. The map goes completely black if you get too close to an area that isn't finished yet. This means if I ride the subway for example to the large drive-in warehouse. When I get off the subway I can't do anything because everything turns black.

**Comment by jhovgaard** [comment]
This does sound like the camera clipping issue we fixed long ago. Closing this now. Reopening if we get fresh reports.
