### ISSUE TITLE
New right click menu for building closed on lost focus

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#652]
### Build number

242

### Bug description

The overlay dialog for buildings auto-hides when the mouse cursor leaves the building.
Unfortunately the same happens with the right-click dialog, which is smaller than the "normal" overlay dialog. So it happens often that the first dialog is still over the building, but the smaller right-click dialog not and thus unreachable.

What I expect:
After right clicking, the small dialog should not auto-hide when the mouse leaves the building. It should only hide when clicking the "X".

### Savegame file

[Build242-InFrontOfElGato.txt](https://github.com/hovgaardgames/bigambitions/files/7445471/Build242-InFrontOfElGato.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139513543-762b3779-1f54-4b9e-afbb-ae7b4dbfefbe.mp4

**Comment by jhovgaard** [comment]
Fixed in build 279 (or earlier)
