### ISSUE TITLE
Wrong queueing position at second El Gato counter

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#653]
### Build number

242

### Bug description

At the second counter at El Gato (the one further away from the door), the queueing position is wrong. Customers are standing too far away from the counter.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139514186-ad49ab91-26e3-4d9c-9ab2-e3708ea06638.mp4

**Comment by David-Goru** [comment]
@Gerwanese can you help reproduce it?

**Comment by Gerwanese** [comment]
Can't reproduce it anymore, so I'll close the issue.
