### ISSUE TITLE
Misplaced speed toggle in working dialog

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#654]
### Build number

242

### Bug description

In the working dialog, there's a misplaced toggle to change speed while working.
Besides, the dialog is still titled "Start working" while already working. Maybe in that case, "Start" should be removed from the dialog title. :)

### Steps to reproduce the bug

Start work.
The toggle will be visible and can be used.
It doesn't matter whether your shift has started already or not, behaviour is the same.

### Savegame file

[Build242-StartWorkBeforeShift.txt](https://github.com/hovgaardgames/bigambitions/files/7445492/Build242-StartWorkBeforeShift.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/139514324-c410c5e2-5747-4992-b7f0-8800178886e5.png)

**Comment by jhovgaard** [comment]
Fixed in build 243
