### ISSUE TITLE
"Open in Bizman / Interior Designer" dialog stays open when openening Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#655]
### Build number

242

### Bug description

When opening Voogle Maps from inside a building, the dialog with the "Open in Bizman" and "Interior Designer" on the right side will stay open. You can even open the Interior Designer while showing the map.

### Steps to reproduce the bug

Go inside a building and open the map.

### Savegame file

[Build242-InsideApartment.txt](https://github.com/hovgaardgames/bigambitions/files/7445503/Build242-InsideApartment.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/139514544-fd91dbd7-9226-4ea8-bd5f-e22a432f2799.png)

![grafik](https://user-images.githubusercontent.com/17579552/139514594-61ad87c5-fbe6-46c6-a8f2-4424e3974978.png)

**Comment by David-Goru** [comment]
Fixed in build 273
