### ISSUE TITLE
Interior designer: One wall color and multiple floor styles wrong

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#656]
### Build number

242

### Bug description

For wall colors, the first color looks kind of brown but just paints white (same like the last color).

For floor styles, the second style shows dark gray (similar to the black wall color) but will paint in blue.
The last two styles are repeated.

### Savegame file

[Build242-InsideApartment.txt](https://github.com/hovgaardgames/bigambitions/files/7445517/Build242-InsideApartment.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139514873-d0571704-8d40-42c9-975d-04c7debbf7d7.mp4

**Comment by David-Goru** [comment]
Fixed in build 328
