### ISSUE TITLE
Work doesn't stop automatically in own shop after end of shift

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#658]
### Build number

242

### Bug description

When the shift is finished, working used to stop automatically.
Now however it's not stopping and you continue to work.

### Steps to reproduce the bug

Start working at your own shop and wait for the shift to end.
I tried with active and inactive double speed toggle, no difference.

### Savegame file

[Build242-NoTimeMachineOwnShop.txt](https://github.com/hovgaardgames/bigambitions/files/7445590/Build242-NoTimeMachineOwnShop.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/139515994-f9888faa-f187-454e-9865-c6e0ab17b0d5.png)

**Comment by jokoho48** [comment]
Fixed in Build 243
