### ISSUE TITLE
Time Machine stops at 16:00, when restarted stops at 16:00 of the next day

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#659]
### Build number

242

### Bug description

When using time machine in my shop (open 11:00 to 21:00), time machine will stop at 16:00.
When starting it again, it will run to the next day 16:00.

See also https://community.bigambitionsgame.com/t/time-machine-to-end-of-shift-stops-at-16-00/486

### Steps to reproduce the bug

Start work, then start time machine.

### Savegame file

[Build242-GiftysBeforeShiftStart.txt](https://github.com/hovgaardgames/bigambitions/files/7445620/Build242-GiftysBeforeShiftStart.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139516591-c4e41f7f-3abd-4d58-ad2c-5f6fdf84126a.mp4

**Comment by Gerwanese** [comment]
Didn't happen after reloading the savegame.
Maybe it only happens in a new game when the shop was just set up with its opening times?

**Comment by David-Goru** [comment]
Fixed in build 285
