### ISSUE TITLE
Car's cargo dialog stays open when opening Voogle Maps

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#662]
### Build number

242

### Bug description

When opening Voogle Maps while the car's cargo dialog is open, it will still stay open on the map.

### Steps to reproduce the bug

1. Open the car's cargo dialog
2. Press M

### Savegame file

[Build242-InFrontOfApplianceStore.txt](https://github.com/hovgaardgames/bigambitions/files/7446587/Build242-InFrontOfApplianceStore.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139533809-afe1fa2a-47af-4bd2-8096-921ef4c1a9c5.mp4

**Comment by David-Goru** [comment]
Fixed in build 273
