### ISSUE TITLE
"Open in BizMan" button sometimes visible on building's overlay popup

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#663]
### Build number

242

### Bug description

Sometimes the "Open in BizMan" button is still visible in the building's overlay popup.
Once you do a right click, it will be gone and only appear in the smaller "right-click dialog". The issue will come back after a while however.

It happend both when the building was closed and opened, so it doesn't depend on that.

### Savegame file

[Build242-InFrontOfApplianceStore.txt](https://github.com/hovgaardgames/bigambitions/files/7446589/Build242-InFrontOfApplianceStore.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139533898-b82fc851-cba0-450f-b1d3-75a8d1d7e49d.mp4

**Comment by David-Goru** [comment]
Fixed in build 285
