### ISSUE TITLE
EconoView shows only Yesterday's statistics but no older anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#664]
### Build number

242

### Bug description

In EconoView, only yesterday's statistics are populated. "The day before yesterday" is always empty.

### Savegame file

[Build242-EconoViewWrongStats.txt](https://github.com/hovgaardgames/bigambitions/files/7446607/Build242-EconoViewWrongStats.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/139534159-c09a1852-1f9e-4537-ba0a-e06105bd05cb.png)

**Comment by David-Goru** [comment]
Fixed in build 248
