### ISSUE TITLE
Driving into Drive-In Wholesales breaks camera angle

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#665]
### Build number

242

### Bug description

When driving a car into the drive-in wholesales, the camera turns to the "walking perspective" where you manually have to adjust the angle.
This behavior still stays when leaving the drive-in wholesales. To fix it you have to leave and re-enter the car.

### Savegame file

[Build242-DriveInWholesales.txt](https://github.com/hovgaardgames/bigambitions/files/7446656/Build242-DriveInWholesales.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139534980-86b674dd-0ead-432b-89aa-19eece58cf81.mp4

**Comment by jokoho48** [comment]
Fixed in Build 244
