### ISSUE TITLE
Car duplicated when leaving drive-in wholesales

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#666]
### Build number

242

### Bug description

When leaving the drive-in wholesales by car, the car is duplicated. The newly generated car will show the green "steering wheel" icon and is also indicated on Voogle Maps, however you can't enter it.
This happens every time, so the number of cars gets more and more.

### Savegame file

[Build242-DriveInWholesales.txt](https://github.com/hovgaardgames/bigambitions/files/7446659/Build242-DriveInWholesales.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139535033-345c312d-61dc-4750-95fe-d58e2eb40986.mp4

**Comment by jokoho48** [comment]
Fixed in Build 244
