### ISSUE TITLE
Subway station GarmentDistrictStation2 not accessible anymore

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#668]
### Build number

245

### Bug description

It's not possible anymore to enter the subway station GarmentDistrictStation2.

(When fixing this, #461 might be worth taking a look at too)

### Savegame file

[Build245-GarmentDistrictStation2.txt](https://github.com/hovgaardgames/bigambitions/files/7452904/Build245-GarmentDistrictStation2.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/139666859-224127f8-5c1c-4ff9-bb89-785c5e715ffe.mp4

**Comment by jhovgaard** [comment]
Fixed in build 270
