### ISSUE TITLE
"Cut" in street textures at the corner of 3rd Street / 3rd Avenue

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#669]
### Build number

248

### Bug description

At the corner of 3rd Street and 3rd Avenue, just a few meters into 3rd street, you can see a clear cut in the street textures. When turning into the sunlight, you can see an even stronger effect.

### Steps to reproduce the bug

Start a new game, you're at the right location already.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/140377560-c556e23a-7db4-481c-b4fa-0048f4df9528.mp4

**Comment by jhovgaard** [comment]
Fixed in build 278 (or earlier)
