### ISSUE TITLE
Clipping in park bench

### ISSUE THREAD

**Issue by Libror** [hovgaardgames/bigambitions#670]
### Build number

245

### Bug description

When I tried to skip time, I slept on the park bench multiple times and eventually got stuck in it. Restarting the game helped.

**Comment by jhovgaard** [comment]
@Gerwanese Can you reproduce this?

**Comment by Gerwanese** [comment]
@jhovgaard We had sporadic reports of this. Once happened to me long ago, but no certain way to reproduce.

**Comment by jhovgaard** [comment]
I experienced this too. Only happens in build, not in editor.

**Comment by David-Goru** [comment]
How to reproduce: sleep on a bench, cancel it before ending, and then try to move to it without clicking it. Happens both in build and in editor

**Comment by David-Goru** [comment]
Fixed in build 717
