### ISSUE TITLE
BizMan insight button not aligned correctly

### ISSUE THREAD

**Issue by Libror** [hovgaardgames/bigambitions#671]
### Build number

245

### Bug description

The part where I can click the button is not in the right place

1920x1080 full screen

![GIF 05 11 2021 23-03-39](https://user-images.githubusercontent.com/47794032/140583607-117f30b4-4918-4e37-a9d9-83e3a0e86aa5.gif)

FYI, I am constantly clicking in the video above

### Screenshots or videos

Refer to the gif above

**Comment by Gerwanese** [comment]
Confirmed.

[Build242-IkeaInsideWall.txt](https://github.com/hovgaardgames/bigambitions/files/7489174/Build242-IkeaInsideWall.txt)

**Comment by David-Goru** [comment]
Fixed in build 272
