### ISSUE TITLE
Pausing and unpausing while sped up makes your game run at 100% speed

### ISSUE THREAD

**Issue by Libror** [hovgaardgames/bigambitions#673]
### Build number

245

### Bug description

When speeding up your shift with the 'Fast-forward time' slider and then pausing/unpausing, the game will continue at normal speed instead of the fast forward speed

![GIF 06 11 2021 12-57-31](https://user-images.githubusercontent.com/47794032/140608775-46089ab0-d995-4ceb-b811-aae9bc4077ea.gif)

**Comment by Libror** [comment]
This also happens when you open and close any menu

**Comment by David-Goru** [comment]
Fixed in build 253
