### ISSUE TITLE
Products can have a negative quantity 

### ISSUE THREAD

**Issue by Libror** [hovgaardgames/bigambitions#675]
### Build number

245

### Bug description

![image](https://user-images.githubusercontent.com/47794032/140608867-2d741c45-a41e-4da3-959e-0a79de79eae3.png)

**Comment by Gerwanese** [comment]
@Libror Can you explain what you did before this happened? Without more explanation I'm afraid it won't be possible to verify this bug.

**Comment by jokoho48** [comment]
Fixed in Build 288.
