### ISSUE TITLE
Faulty Save

### ISSUE THREAD

**Issue by JakeProxZ** [hovgaardgames/bigambitions#676]
### Build number

245

### Bug description

Saved the game on day 23 and it automatically went to the main menu and did not save.

### Steps to reproduce the bug

Hit Save multiple times.

### Savegame file

[ProxZ Day - Copy.txt](https://github.com/hovgaardgames/bigambitions/files/7531652/ProxZ.Day.-.Copy.txt)

**Comment by jhovgaard** [comment]
Hi @JakeProxZ! Sorry for the late relpy.

The savegame you attached starts at day 23. Doesn't that mean it saved, or do I misunderstand you?

**Comment by jhovgaard** [comment]
Closing until further info.
