### ISSUE TITLE
Stackable cargo (+2) becomes 1

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#679]
### Build number

276

### Bug description

https://user-images.githubusercontent.com/1388347/144398328-d82bb456-db01-47cd-b805-84d469490596.mp4

### Savegame file

[Cargo-Destroyed.json.txt](https://github.com/hovgaardgames/bigambitions/files/7640863/Cargo-Destroyed.json.txt)

**Comment by jhovgaard** [comment]
Additional tasks:

- [ ] Vehicle cargo status is showing wrong amount.
- [ ] Switch to stackable version of the background

**Comment by David-Goru** [comment]
Fixed in build 276
