### ISSUE TITLE
AI Clothing store not working

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#680]
### Build number

276

### Bug description

![image](https://user-images.githubusercontent.com/1388347/144406492-e40b3133-7bb3-465a-8cda-3abf492272ba.png)

### Savegame file

[Clothing store doesn't work.json.txt](https://github.com/hovgaardgames/bigambitions/files/7641200/Clothing.store.doesn.t.work.json.txt)

**Comment by jokoho48** [comment]
Fixed in Build 278
