### ISSUE TITLE
Can work on my day off

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#681]
### Build number

276

### Bug description

Started a new game and got a job at El Gato Foods, straight away I clicked on the desk.
The message showed was "Your Shift Hasn't Started Yet" However i could still work, and fast forward time, however the Time Machine to end of shift button was still greyed out. 
Working still appears to work perfectly fine as I'm still being paid for it. 

Would expect to not be able to work while on a day off.

### Steps to reproduce the bug

Start a new Game
Complete first few tasks
Go to El Gato Food 
Apply for the job
Before leaving the store click on a desk to start working
You will see the start work button show up
Click it
You are now working on your day off
Still being Paid $25 an hour

### Savegame file

[Work on day off.txt](https://github.com/hovgaardgames/bigambitions/files/7641339/Work.on.day.off.txt)

### Screenshots or videos

![Big_Ambitions_sYQmKVbIdI](https://user-images.githubusercontent.com/44293115/144410191-d0420332-1096-4eab-bf85-64e4ee384d63.jpg)

**Comment by adameg2305** [comment]
Update: You can carry on working even once the store is closed and you are still paid
Can carry on working with no food
Stops working when tired

**Comment by jhovgaard** [comment]
Let's rename the "Start working" button to "Assign yourself" (in lack of better phrasing), as we want the player to be able to use fast-forward. Stop working should be renamed to "Unassign".

**Comment by jokoho48** [comment]
Fixed in Build 278

**Comment by Gerwanese** [comment]
Not fully fixed in 278, you still get $25 per hour even outside your shift.


[Build278-SuspiciousGuyLoitering.json.txt](https://github.com/hovgaardgames/bigambitions/files/7644659/Build278-SuspiciousGuyLoitering.json.txt)
(go into your apartment and sleep, next day you can start the work before 7)

https://user-images.githubusercontent.com/17579552/144491213-a646afbb-d18b-4045-9501-4923e6153867.mp4

**Comment by jokoho48** [comment]
Fixed in Build 279. this issue was Unrelated to the other one.
