### ISSUE TITLE
"Unassign yourself" button too small at workplace

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#684]
### Build number

278

### Bug description

The button for "Unassign yourself" while working is too small for the text.

### Savegame file

[Build278-SmallUnassignButton.json.txt](https://github.com/hovgaardgames/bigambitions/files/7644632/Build278-SmallUnassignButton.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/144490210-9a869bd3-3174-46dd-ae00-a08ed4e0e51b.png)

**Comment by jhovgaard** [comment]
Fixed in build 280
