### ISSUE TITLE
Double $ sign for income while working

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#685]
### Build number

278

### Bug description

While working, the hourly income of $25 is shown as $$25

### Savegame file

[Build278-SmallUnassignButton.txt](https://github.com/hovgaardgames/bigambitions/files/7644641/Build278-SmallUnassignButton.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/144490464-76f0be82-2099-48e0-b984-ac05c1026030.png)

**Comment by jhovgaard** [comment]
Fixed in build 280
