### ISSUE TITLE
$$25 shown as income from job doesn't get removed from screen

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#687]
### Build number

278

### Bug description

The $$25 displayed as your income from working doesn't get removed from screen. You can see that it's still there twice.

### Savegame file

[Build278-SmallUnassignButton.json.txt](https://github.com/hovgaardgames/bigambitions/files/7644736/Build278-SmallUnassignButton.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/144492770-c2291b6f-9cc5-4994-869a-3709b1d35d8f.png)

**Comment by jhovgaard** [comment]
I can't reproduce, but build 279 was pushed in between, so it might have been indirectly fixed.

Let's confirm it works in build 280.
