### ISSUE TITLE
Pressing ESC on Voogle Maps leaves you stuck between map and street mode

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#688]
### Build number

278

### Bug description

If you open Voogle Maps and then press X, the UI switches to street mode, colors also change but the camera is not brought back to street level and the game is still paused.
You're stuck in that situation with no way out.

### Savegame file

[Build278-TakeARestTiredGirl.json.txt](https://github.com/hovgaardgames/bigambitions/files/7644774/Build278-TakeARestTiredGirl.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/144494143-6df0efef-8ebe-446c-97d5-46eaac36fa4c.mp4

**Comment by jhovgaard** [comment]
Fixed in build 279
