### ISSUE TITLE
Subway broken: You're stuck after selecting a destination

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#689]
### Build number

278

### Bug description

If you select a destination after entering a subway station, you will end up being stuck. The game is paused, subway doesn't start and you can't do anything about it.

### Savegame file

[Build278-TakeARestTiredGirl.json.txt](https://github.com/hovgaardgames/bigambitions/files/7644794/Build278-TakeARestTiredGirl.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/144494613-423a56a0-94ec-482d-a973-76119e10c9f2.mp4

**Comment by jhovgaard** [comment]
Fixed in build 279
