### ISSUE TITLE
Assigning yourself to workplace and then selecting fast-forward will bring back the "Assign Yourself" and "Cancel" buttons

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#690]
### Build number

281

### Bug description

If you assign yourself to a workplace (in my case during my day off) and then select fast-forward, the buttons will go back to the previous state, showing "Cancel" and "Assign yourself" instead of "Unassign".

### Savegame file

[Build281-AssignTheUnassigned.json.txt](https://github.com/hovgaardgames/bigambitions/files/7651380/Build281-AssignTheUnassigned.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/144647460-286037a1-fff0-452c-ae71-9d63ab02ee14.mp4

**Comment by David-Goru** [comment]
Fixed in build 283
