### ISSUE TITLE
Drive-In Wholesales: Can't enter by clicking on the doors

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#692]
### Build number

281

### Bug description

The drive-in wholesales store can only be entered by clicking on the walls, but not by clicking on the doors.

### Savegame file

[Build281-DriveInButOnlyThroughTheWalls.json.txt](https://github.com/hovgaardgames/bigambitions/files/7651535/Build281-DriveInButOnlyThroughTheWalls.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/144651451-5fb0438e-6d66-43b2-85b7-024e91de92fa.mp4

**Comment by jhovgaard** [comment]
The doors should also be highlighted.

**Comment by jokoho48** [comment]
Fixed in Build 291
