### ISSUE TITLE
Contextual popups are out of frame

### ISSUE THREAD

**Issue by Navsigda** [hovgaardgames/bigambitions#694]
### Build number

245

### Bug description

Hovering the cursor over a building brings up the contextual popup regarding the premises, including the street address, name, ownership, open/closed trading state, and traffic index. Unless the character is right up against the building and has it centered, the popup will be out of frame.

### Steps to reproduce the bug

Approaching the supermarket on 11 3rd Avenue. Hover the cursor over the building to highlight it.

### Screenshots or videos

![Out of frame](https://user-images.githubusercontent.com/55465313/145110175-74ec336f-317a-4e31-829e-edd36cf0807f.png)

**Comment by David-Goru** [comment]
Fixed in build 285
