### ISSUE TITLE
Sleeping mechanic not working as intended

### ISSUE THREAD

**Issue by Navsigda** [hovgaardgames/bigambitions#697]
### Build number

245

### Bug description

In the "tutorial" phase of BA, you're instructed to sleep until fully rested. When interacting with the bed, there's no indication given of how many hours of sleep equate to a full nights rest. If you sleep for 1 hour, time progresses and the interface closes as intended. What's not intended, is that your energy starts to fill in 1 second increments until full, despite no longer being in the bed. It would seem that a single hour worth of sleep is enough to fill your energy if you're patient enough. 

### Steps to reproduce the bug

Interact with the bed in your apartment at 117 3rd street, opt to sleep for 1 hour, and observe your energy levels increasing incrementally despite no longer sleeping. 

### Savegame file

[Ryno.zip](https://github.com/hovgaardgames/bigambitions/files/7671926/Ryno.zip)

### Screenshots or videos

![Incremental energy regeneration](https://user-images.githubusercontent.com/55465313/145114107-c5e2b445-4e65-44f8-b1ba-f257fe661d60.png)

**Comment by David-Goru** [comment]
Fixed in build 285
