### ISSUE TITLE
Voogle Maps opening on wrong location if opened while pressing mouse button

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#698]
### Build number

288

### Bug description

If I open Voogle Maps by pressing "M" while pressing a mouse button (in my case because I'm walking), the map will open at the wrong location. If I don't press a mouse button it will open at the right location.

### Savegame file

[Build288-MapIsSlipperyWhenWet.json.txt](https://github.com/hovgaardgames/bigambitions/files/7677788/Build288-MapIsSlipperyWhenWet.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/145254223-85f7f214-66b5-4c0e-9efe-2cf9f0dc73c4.mp4

**Comment by David-Goru** [comment]
Fixed in build 295
