### ISSUE TITLE
Character Stops moving when hover action occurs (When you use WASD)

### ISSUE THREAD

**Issue by alaingraham13** [hovgaardgames/bigambitions#699]
### Build number

288

### Bug description

Character stops moving when the mouse hovers over a building or object that has an hover action (like benches, store products etc) when you are using the WASD keys. A recommended quality of life improvement would be to stop this from occurring, as it can lead to the player being late to attending to businesses. 

### Steps to reproduce the bug

Move in any direction with the mouse pointed in a place where it will hit an object.

Keep holding that key even when it hovers over something.

You'll notice your character will stop moving and won't move until the hover action is stopped (ie moving the mouse away from the object) 
Keep repeating until your character stops moving.

### Savegame file

[Newgame.txt](https://github.com/hovgaardgames/bigambitions/files/7682416/Newgame.txt)

### Screenshots or videos

Video didn't upload

**Comment by Gerwanese** [comment]
Could verify it with a bench once, the next time it didn't happen again. Definitely some weird issue.

**Comment by alaingraham13** [comment]
https://user-images.githubusercontent.com/25529451/145937658-c1c5d6e8-251f-4f3f-afed-096a93581168.mp4

was repeatable more than once for me.

**Comment by jokoho48** [comment]
Fixed in Build 294

**Comment by Gerwanese** [comment]
Reopening because of https://community.bigambitionsgame.com/t/hover-wasd-issue-still-occurring-in-alpha-9/643

**Comment by David-Goru** [comment]
Fixed in build 1142
