### ISSUE TITLE
Buildings hiding too late

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#702]
### Build number

288

### Bug description

When walking along the street, buildings are hiding too late just a short time after the player is hidden behind them.

### Savegame file

[Build288-BuildingsHidingButICanStillSeeThem.txt](https://github.com/hovgaardgames/bigambitions/files/7707386/Build288-BuildingsHidingButICanStillSeeThem.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/145900256-ab1bc068-66b8-43f5-ba74-1076750dcc63.mp4

**Comment by jokoho48** [comment]
Fixed in Build 292
