### ISSUE TITLE
Player doesn't stop working at the right time if business hours are changed while working

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#703]
### Build number

288

### Bug description

If you change the business hours while you are working, the player will still continue to work until the time set when he started working.
For example I start working with scheduled hours 11:00-21:00. Now I change it to 11:00-12:00. The player will still continue working until 21:00.

### Savegame file

[Build288-OpeningHoursChangedButNobodyToldMeSoSad.json.txt](https://github.com/hovgaardgames/bigambitions/files/7707421/Build288-OpeningHoursChangedButNobodyToldMeSoSad.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/145901183-19eafa58-3959-4a86-9181-108fb5cdf939.mp4

**Comment by David-Goru** [comment]
Fixed in build 314
