### ISSUE TITLE
Upcoming task for employees in training or on their day off

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#705]
### Build number

288

### Bug description

If an employee is either on training or has a day off (but is assigned to a shift on other days), an "upcoming task" will be shown.
For employees on training, it's saying that the employee is not assigned to any business.
For employees on their day off it's saying that the employee is not assigned to any tasks.

### Savegame file

[Build288-IFeelSoUnassigned.json.txt](https://github.com/hovgaardgames/bigambitions/files/7707585/Build288-IFeelSoUnassigned.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/145906038-f1a2ff5b-93e5-4ccb-b156-a6fff71939ce.mp4

**Comment by jokoho48** [comment]
Fixed in Build 294
