### ISSUE TITLE
Pathfinding issue around 3rd Avenue

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#707]
### Build number

290

### Bug description

Can walk through large plant pot and the character gets stuck on the tables and chairs in the area. 

Better to watch video to understand

### Savegame file

[PathFinding.txt](https://github.com/hovgaardgames/bigambitions/files/7735952/PathFinding.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/146570672-30c92829-34d7-4df6-8208-1695d5e99cc7.mp4

**Comment by jokoho48** [comment]
Fixed in the Meanwhile.
