### ISSUE TITLE
Movement blocked when mousing over UI Buttons

### ISSUE THREAD

**Issue by TinyPandas** [hovgaardgames/bigambitions#708]
### Build number

Alpha 8

### Bug description

Not sure if this is intentional: If it is, please kindly let me know.

However, when walking about and mousing over any form of UI Button player movement stops. If the mouse is already over a UI Button, and you try to move with WASD it does not move as well.

### Steps to reproduce the bug

1. Hover mouse over UI Button
2. Try to move using WASD

**Comment by jokoho48** [comment]
duplicate of https://github.com/hovgaardgames/bigambitions/issues/699
