### ISSUE TITLE
Traffic lights progress when game paused

### ISSUE THREAD

**Issue by TinyPandas** [hovgaardgames/bigambitions#709]
### Build number

289 (Alpha 8)

### Bug description

Traffic lights will continue to cycle even if game is paused.

### Steps to reproduce the bug

1. Pause game looking at Traffic light

### Savegame file

[AutoSaved#5765.txt](https://github.com/hovgaardgames/bigambitions/files/7740320/AutoSaved.5765.txt)

### Screenshots or videos

https://streamable.com/apbsyb

**Comment by jhovgaard** [comment]
Fixed in build 330
