### ISSUE TITLE
 Cant release item when holding it 

### ISSUE THREAD

**Issue by SHALEVa7x** [hovgaardgames/bigambitions#714]
### Build number

7888663

### Bug description

Hi

Love the game, a great idea.

when I pick up items (shelf, registry, and more items of the store) it won’t release them at all.

another problem I have is the camera won’t move with the car while I drive. I can start driving and the camera will stay at the same place I entered the car.

Hope you could fix that.

### Savegame file

[A7X.txt](https://github.com/hovgaardgames/bigambitions/files/7769327/A7X.txt)

**Comment by David-Goru** [comment]
Closing and reopening the businesses fixes the error
