### ISSUE TITLE
Map no work when in car.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#715]
### Build number

296

### Bug description

When in the car The map opens, however, you cant move the map, you cant rotate. The filters do still work. 

### Steps to reproduce the bug

Open the map and try to move it while in a car

### Savegame file

[Map No Work.txt](https://github.com/hovgaardgames/bigambitions/files/7771862/Map.No.Work.txt)

**Comment by jokoho48** [comment]
Fixed in Build 300.
