### ISSUE TITLE
Infinite loading screen

### ISSUE THREAD

**Issue by ksaumaz** [hovgaardgames/bigambitions#716]
### Build number

289

### Bug description

I was just playing around, saved the game and now I cannot load back into the latest save.

### Steps to reproduce the bug

Load the gamefile

### Savegame file

[save.txt](https://github.com/hovgaardgames/bigambitions/files/7774096/save.txt)
[player.log.txt](https://github.com/hovgaardgames/bigambitions/files/7774100/player.log.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/64628051/147348287-0d37fb38-4fb9-409e-b3a4-21bcb4aba963.png)

**Comment by jokoho48** [comment]
Fixed in Build 296
