### ISSUE TITLE
Endless loading sreen is shown in case saved with equipped hand truck

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#717]
### Build number

289

### Bug description

Save file has endless loading screen when saved with equipped hand truck

### Steps to reproduce the bug

1. Equip hand truck
2. Save game
3. Go to Main Menu
4. Load the saved game

### Savegame file

[BugTest.zip](https://github.com/hovgaardgames/bigambitions/files/7780184/BugTest.zip)

**Comment by jokoho48** [comment]
Fixed in Build 296
