### ISSUE TITLE
Supermarket: Can't add anything to shopping basket

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#718]
### Build number

296

### Bug description

Picking up the shopping basket already took 2-3 seconds before I was able to move again, now it's not possible to add anything into it.

### Savegame file

[Build296-SupermarketNotSoSuper.json.txt](https://github.com/hovgaardgames/bigambitions/files/7781649/Build296-SupermarketNotSoSuper.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147503744-e57dbd49-dd10-4106-91a9-ab76b063b6dd.mp4

**Comment by Gerwanese** [comment]
This applies to drive-in wholesales as well. Probably all kinds of shelves are broken in build 296.

**Comment by jokoho48** [comment]
Fixed in Build 300.
