### ISSUE TITLE
Possible to leave supermarket while holding a shopping basket, impossible to discard it afterwards

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#719]
### Build number

296

### Bug description

It is possible to leave the supermarket while holding a shopping basket.
Afterwards you can't discard the basket anymore and are stuck.

### Savegame file

[Build296-SupermarketNotSoSuper.json.txt](https://github.com/hovgaardgames/bigambitions/files/7781679/Build296-SupermarketNotSoSuper.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147504101-ced2c950-b3fb-49a0-a6fe-be8ecda87bda.mp4

**Comment by jokoho48** [comment]
Fixed in Build 300.
