### ISSUE TITLE
People don't immediately get spawned in shops on reload if saving paused game 

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#720]
### Build number

296

### Bug description

If you save a game inside a shop while the same is paused, after reloading the game you'll at first just see people stacked at the entrance door. Only when unpausing the game, they suddenly spread all over the shop.

### Savegame file

[Build296-SupermarketNotSoSuper.json.txt](https://github.com/hovgaardgames/bigambitions/files/7781706/Build296-SupermarketNotSoSuper.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147504805-02eb6589-ab3c-463d-9400-d2442d6f0522.mp4

**Comment by David-Goru** [comment]
Fixed in build 301
