### ISSUE TITLE
Forklift in drive-in wholesales is for single use only

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#722]
### Build number

296

### Bug description

If you use the forklift in drive-in wholesales, then leave and re-enter the building, the forklift will be gone.

### Savegame file

[Build296-SingleUseForklift.json.txt](https://github.com/hovgaardgames/bigambitions/files/7781752/Build296-SingleUseForklift.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147505993-8101bc89-aaa9-4a37-b621-12afd57e4547.mp4

**Comment by jokoho48** [comment]
Fixed in Build 300!!!
