### ISSUE TITLE
Can't pick up anything in drive-in wholesales except paperbags

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#723]
### Build number

231

### Bug description

The only item that can be picked in the drive-in wholesales store are paperbags. All other items can't be picked from the shelves.

### Savegame file

[Build296-CheapGiftsAreNotSoGifted.json.txt](https://github.com/hovgaardgames/bigambitions/files/7789660/Build296-CheapGiftsAreNotSoGifted.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147679629-02209519-c2f4-4c16-b94c-a1cd9238c642.mp4

**Comment by jokoho48** [comment]
Fixed in Build 301
