### ISSUE TITLE
New "blocked-out" buildings don't hide when walking in front of them

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#725]
### Build number

303

### Bug description

The new blocked-out buildings (those not in use yet) don't hide if the player walks behind them.

### Savegame file

[Build303-DontBlockMe.json.txt](https://github.com/hovgaardgames/bigambitions/files/7796321/Build303-DontBlockMe.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147826266-21a3fe63-b285-4b3f-8a94-4e5826c109e8.mp4

**Comment by jokoho48** [comment]
Fixed in Build 313.
