### ISSUE TITLE
Contacts app: Buttons in recruitment agency messages overlap

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#727]
### Build number

303

### Bug description

When opening the contacts app and immediately selecting the recruitment agency messages, the buttons to hire or cancel an employee overlap each other.
When clicking on some other message thread and back to recruitment agency, they're shown correctly.

### Savegame file

[Build303-ButtonsInLove.json.txt](https://github.com/hovgaardgames/bigambitions/files/7796417/Build303-ButtonsInLove.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147828376-f1b19af0-7973-4fe2-90c9-f10d214c969b.mp4

**Comment by David-Goru** [comment]
Fixed in build 314
