### ISSUE TITLE
Vehicles stack up at car dealer

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#728]
### Build number

303

### Bug description

It's the second time already I've come to the car dealer to see a truck sitting on another vehicle, so there seems to be some issue at this location.
It's already like this when arriving at the location, so it could be a problem with spawning.

### Savegame file

[Build303-VehicleStackAtCarDealer.json.txt](https://github.com/hovgaardgames/bigambitions/files/7796438/Build303-VehicleStackAtCarDealer.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/147828728-21d07c78-77fe-4efb-a556-045060cc8a68.png)

**Comment by jhovgaard** [comment]
Fixed in build 319
The solution might fix other traffic-related bugs. Vans were always ignored by other vehicles.
