### ISSUE TITLE
Drive-In Wholesales: Expensive gifts sold as single item

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#730]
### Build number

303

### Bug description

Expensive gifts in the drive-in wholesales are priced as single item instead of a box. Also the boxes in the shelves show no quantity.

### Savegame file

[Build303-DriveInWholesalesSingleGifts.json.txt](https://github.com/hovgaardgames/bigambitions/files/7796456/Build303-DriveInWholesalesSingleGifts.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147829167-5b8e3369-b69d-4902-af33-869e5128ce50.mp4

**Comment by jokoho48** [comment]
Fixed in Build 305.
