### ISSUE TITLE
Buildings hiding too late when driving car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#731]
### Build number

303

### Bug description

When driving car, buildings are hiding too late.
They're probably hiding only when the player (=driver's seat) is getting very close, but at that time half of the car might be behind the building already.

### Savegame file

[Build303-BuildingsHidingLate.json.txt](https://github.com/hovgaardgames/bigambitions/files/7796473/Build303-BuildingsHidingLate.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/147829466-f2aa40e9-565f-474d-bb48-a64264ee135f.mp4

**Comment by jokoho48** [comment]
Fixed in Build 305
