### ISSUE TITLE
Invisible Doors

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#732]
### Build number

304

### Bug description

In the large office type (EG. 10 2nd Avenue) you can only walk in the hallway, all of the rooms off of the corridor wont allow you to walk through the doors.

### Steps to reproduce the bug

Rent a large office building type
Try to enter any of the rooms

### Savegame file

[Faulty Doors.txt](https://github.com/hovgaardgames/bigambitions/files/7803491/Faulty.Doors.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/147966746-f6738e1d-1802-4f29-9482-d46493937a91.mp4

**Comment by jokoho48** [comment]
Fixed in Build 310.
