### ISSUE TITLE
Cars in the bridge

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#734]
### Build number

304

### Bug description

The road layout appears to be slightly offset as vehicles are driving half on the sidewalk and half in the bridge

### Steps to reproduce the bug

Head to 2nd Avenue 3rd street look at the bridge.

### Savegame file

[Ghost Cars.txt](https://github.com/hovgaardgames/bigambitions/files/7803547/Ghost.Cars.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/147968160-0a425075-f7a2-48e6-9cb3-a73af0fff90c.png)

**Comment by jhovgaard** [comment]
Fixed in build 320
