### ISSUE TITLE
No doors for toilet areas in buildings

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#735]
### Build number

304

### Bug description

No door appears for the toilets in the large office building type as it does in other building types such as El Gato foods.

### Steps to reproduce the bug

Hire a building with the large office style
find a hole to the abyss instead of a toilet door.

### Savegame file

[Hole to the Abyss.txt](https://github.com/hovgaardgames/bigambitions/files/7803569/Hole.to.the.Abyss.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/147967879-795b0f38-dc5d-4010-9764-f62e0b876cda.png)

**Comment by jokoho48** [comment]
Fixed in Build 310.
