### ISSUE TITLE
Daily Summary still plays while paused

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#736]
### Build number

304

### Bug description

At midnight if you pause the game the daily summary will still play while paused so could be missed by the player as it doesn't stay on the screen either.

### Steps to reproduce the bug

Pause the game at midnight, watch the summary

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/147969231-96190e28-2c5f-488c-90dd-cee9a644c7a8.mp4

**Comment by David-Goru** [comment]
Fixed in build 314
