### ISSUE TITLE
17th Third street occupied

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#737]
### Build number

311

### Bug description

In the beginning phase of the game, you are told to rent 17th Third Street, however, the building can become occupied

### Savegame file

[ocupado .txt](https://github.com/hovgaardgames/bigambitions/files/7856727/ocupado.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/149197374-e8c070c8-f333-4e71-be64-d8883a68f4ae.png)

**Comment by jokoho48** [comment]
Fixed in Build 313. new savegame required.
