### ISSUE TITLE
Business school not open on sunday

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#738]
### Build number

314

### Bug description

In Bizman it shows that the Business school is open from 06:00 until 20:00, however on Sundays the building is displayed as closed so you cant enter.

### Savegame file

[No Skool .txt](https://github.com/hovgaardgames/bigambitions/files/7872605/No.Skool.txt)

### Screenshots or videos

![Big_Ambitions_0f2SitHgRp](https://user-images.githubusercontent.com/44293115/149570664-c578064f-1075-4e1e-8194-6a6b09aed9e9.jpg)
![Big_Ambitions_ZqnM3rf3dl](https://user-images.githubusercontent.com/44293115/149570672-e8015e12-0dc0-4d7c-b5f1-8e20e85cc7aa.jpg)

**Comment by Gerwanese** [comment]
Same issue currently exists for El Gato and the Office Supply Store, probably for others as well.

**Comment by David-Goru** [comment]
Fixed in build 315
