### ISSUE TITLE
Can't grab paper bag with food after placing it on the floor

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#739]
### Build number

316

### Bug description

I can't pick up the paper bag with food from the floor, I'll just get an error message: "You cant grab an item cargo or shelf stock".

Besides, it should be "can't" instead of "cant". ;)

### Savegame file

[Build316-Ungrabbable.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873451/Build316-Ungrabbable.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149590618-999a709a-3fdb-4650-88ac-4e7be3b16906.mp4

**Comment by jokoho48** [comment]
Fixed in Build 324
