### ISSUE TITLE
Building Borders Extending Too Far

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#74]
Alpha 4 - Build 47

https://i.adameg.net/a6vp2n.png

As seen in the screenshot Number 11 on Fourth Avenue had building borders that display outside of the actual building, and under other building to the side.

Havent noticed on other buildings yet.

**Comment by Gerwanese** [comment]
Same problem exists for building in 1st Street (I think).
![grafik](https://user-images.githubusercontent.com/17579552/121819942-331fa180-cc90-11eb-99d5-09bd36720bd6.png)

**Comment by jhovgaard** [comment]
Fixed in build 279 (or earlier)
