### ISSUE TITLE
Missing text in new business schedule UI options

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#740]
### Build number

316

### Bug description

The "Options" in the new business schedule UI don't have proper texts yet.

### Savegame file

[Build316-BizManScheduleOptions.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873589/Build316-BizManScheduleOptions.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/149593514-473a7be2-cea7-46c8-8d39-8ce762a3bd32.png)

**Comment by David-Goru** [comment]
Fixed in build 319
