### ISSUE TITLE
Map Filter: Category lines hiding when scrolling on resolution below 1080p

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#741]
### Build number

316

### Bug description

When playing the game in a resolution lower than 1080p and scrolling in the map filter list, the category lines sometimes hide.
When playing in 800x600, even the category titles partially hide.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149594850-4afbde85-d515-4e45-ba03-861b894b26bb.mp4

**Comment by David-Goru** [comment]
Fixed in build 327
