### ISSUE TITLE
Scrolling my mouse wheel in combobox causes camera zoom

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#742]
### Build number

316

### Bug description

If you use the mouse wheel to scroll through a list (while not being in a phone app), the mouse wheel will also trigger zooming.

### Savegame file

[Build316-ScrollMeToTheMoon.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873703/Build316-ScrollMeToTheMoon.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149596238-bd20f42d-6e6e-4aa8-bb49-2a9e063a80b3.mp4

**Comment by jhovgaard** [comment]
Fixed in build 319
