### ISSUE TITLE
Bought items can sometimes show the "Unpaid Total" text under the Place/Discard/Pack buttons

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#744]
### Build number

316

### Bug description

After buying an item, sometimes it can show the "Unpaid Total" text together with the buttons Place/Discard/Pack.
The buttons are correct while the text is wrong, as the item has already been purchased.
In this case it's a rounded shelf from the second appliance store (AJ Pederson & Son). Joko had the issue with a Standard Fridge.

### Savegame file

[Build316-TotallyPaidUnpaidTotal.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873789/Build316-TotallyPaidUnpaidTotal.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/149598063-77cd6c29-a4c4-48c3-a523-165428ffba2a.png)

**Comment by jhovgaard** [comment]
Fixed in build 319
