### ISSUE TITLE
Cleaners can't be unassigned from a business and thus can't be trained

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#745]
### Build number

316

### Bug description

It's not possible to unassign a cleaner from a business. Without unassigning, you also can't train them.

### Savegame file

[Build316-CleanersDontTrain.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873802/Build316-CleanersDontTrain.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/149598616-bddba4a4-a473-438d-961f-cce81b060b5b.png)

**Comment by jhovgaard** [comment]
Fixed in build 319
