### ISSUE TITLE
All employees can be assigned to Cashregister and Mop, no matter their profession

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#746]
### Build number

316

### Bug description

There's no employee separation between customer service and cleaners, all employees can be assigned to any type of work. You also can't see their profession in the scheduling screen.

### Savegame file

[Build316-CleanersDontTrain.json.txt](https://github.com/hovgaardgames/bigambitions/files/7873816/Build316-CleanersDontTrain.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149598950-9b60c253-f94d-4ebf-8da6-08186c49c932.mp4

**Comment by David-Goru** [comment]
Fixed in build 319
