### ISSUE TITLE
Cant pick up any item

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#747]
### Build number

319

### Bug description

You can no longer use the Hand truck in the latest build, clicking on it doesn't pick it up.
EDIT: Turns out nothing can be picked up anymore, after completing the first few objectives (Buying fridge etc) after trying to open the gift shop i cant pick up any objects.

### Savegame file

[Handtruck.txt](https://github.com/hovgaardgames/bigambitions/files/7875362/Handtruck.txt)

**Comment by jokoho48** [comment]
Fixed in Build 320.
