### ISSUE TITLE
BizMan: ESC for closing not working while focus is on combobox

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#748]
### Build number

322

### Bug description

If the combobox in BizMan's schedule tab has the focus, ESC for closing doesn't work.
While this might be understandable while the combobox is expanded, this still happens if I close the combobox by clicking somewhere else. Only after I click a second time somewhere else, ESC will work again.

### Savegame file

[Build316-ESChasEscaped.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877550/Build316-ESChasEscaped.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149671323-78de4f26-370e-4019-a63f-da2d719573cd.mp4

**Comment by David-Goru** [comment]
Fixed in build 327
