### ISSUE TITLE
Cleaner's salary not part of EconoView

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#749]
### Build number

322

### Bug description

Cleaners are nowhere to be found in the EconoView. Their salary should be spread between all businesses they are assigned to. Here you only see $180 for Gifty's, which is the salary for 10 hours of customer service.
Additionally, unassigned employees are also not part of EconoView, and assigned employees on closed businesses as well (here I have one service employee assigned to Foody's, which is still closed right now and employee cost was $0 in EconoView).

### Savegame file

[Build316-DontPayTheFerrymanIfHeIsACleaner.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877571/Build316-DontPayTheFerrymanIfHeIsACleaner.json.txt)

### Screenshots or videos

Uploading Big Ambitions Playtest_2022.01.16-18.47.mp4…

**Comment by David-Goru** [comment]
Fixed in build 327
