### ISSUE TITLE
Impossible to leave Drive-In Wholesales backwards

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#750]
### Build number

322

### Bug description

You can't leave the drive-in wholesales anymore driving backwards.
I noticed that you also enter it when driving towards it even before you reach the door. This is possibly related. My guess would be that driving out backwards will leave you so close to the door that you immediately enter again.

### Savegame file

[Build316-BackOutToGetIn.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877585/Build316-BackOutToGetIn.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149672073-09bdf4c5-dc12-4c80-be6c-ba301c7f22fe.mp4

**Comment by jokoho48** [comment]
Fixed in Build 324.
