### ISSUE TITLE
No Salad at Drive-In Wholesales store, but available for delivery

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#751]
### Build number

322

### Bug description

The Drive-In Wholesales store offers salad for delivery but doesn't sell it anymore. It should probably be sold from the inactive shelves you see at the start of the video.

### Savegame file

[Build316-BackOutToGetIn.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877642/Build316-BackOutToGetIn.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149672926-8c2cee49-fb1d-4515-852a-d50b9dd0b85b.mp4

**Comment by jokoho48** [comment]
Fixed in Build 324
