### ISSUE TITLE
POI markers shown while sleeping on bench

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#752]
### Build number

322

### Bug description

While sleeping on a bench, the POI markers are still shown.

### Savegame file

[Build322-PoiBench.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877668/Build322-PoiBench.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149673287-d4c7e6a0-a7bd-4a2d-ac2e-749e534fd335.mp4

**Comment by jokoho48** [comment]
Fixed in Build 324.
