### ISSUE TITLE
Hand truck magically disappears when put into an already full car

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#754]
### Build number

322

### Bug description

When you put a hand truck into an already full car (by clicking the car while holding the hand truck), it will magically disappear.

### Savegame file

[Build322-MagicDisappearingHandTruck.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877700/Build322-MagicDisappearingHandTruck.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149673870-0a03465b-8904-4f37-85cf-0c3e99d17ef5.mp4

**Comment by jokoho48** [comment]
Fixed in Build 324
