### ISSUE TITLE
Hand truck holding flying box if car is full

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#755]
### Build number

322

### Bug description

If you have more items than the car can hold (in this case 4 items, while the car only had space for 3 more), the leftover box will be flying on the hand truck.
The box was bought at The Appliance Store and not at Copperfield&Co, so I would expect it to fall down to the bottom of the hand truck.

### Savegame file

[Build322-CopperfieldsFlyingBox.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877704/Build322-CopperfieldsFlyingBox.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/149674090-509ba708-9b81-40af-8144-5042e78db5a3.png)

**Comment by jokoho48** [comment]
Fixed in Build 324.
