### ISSUE TITLE
Scrolling not working properly in new schedule UI

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#756]
### Build number

322

### Bug description

In the new schedule UI, when having more than one cash register, scrolling by mouse wheel only works in the area of the cash registers.
In the area of the cleaning ("Mop" timeline and anywhere right of it) it doesn't scroll.

### Savegame file

[Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877763/Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149674906-c4794c58-d0cc-45a1-9775-f5a3255f8de1.mp4

**Comment by David-Goru** [comment]
Fixed in build 324
