### ISSUE TITLE
Picking up a counter with cash register while being staffed is possible

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#757]
### Build number

322

### Bug description

If you pick up and place a counter with cash register while it's staffed by an employee, the employee will get an offset depending on how you move the counter.
This is just a temporary display issue; once you leave and reenter the store, it's all fine again.

### Savegame file

[Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877769/Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149675050-e7c129c7-8c92-461c-a67c-eaf464976272.mp4

**Comment by jokoho48** [comment]
Picking it up should not be possible at all!

**Comment by jokoho48** [comment]
Fixed in Build 324.
