### ISSUE TITLE
Savegame broken because of SpawnCustomersOnStart()

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#758]
### Build number

322

### Bug description

Savegame is broken and can't be loaded. Playing with an earlier savegame to the same progress and then saving/reloading worked, so something went wrong only in this single savegame (and probably can happen to any savegame anytime).

### Savegame file

[Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877845/Build322-ScrollOrNoScrollThatIsTheQuestion.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/149676282-ed6650ea-5bf5-41bc-aa20-b64fe248371a.png)

**Comment by Gerwanese** [comment]
[Player-prev.log](https://github.com/hovgaardgames/bigambitions/files/7877848/Player-prev.log)

**Comment by jokoho48** [comment]
Fixed in Build 324.
