### ISSUE TITLE
"is dirty and needs to be cleaned" task showing even with cleaner assigned

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#759]
### Build number

322

### Bug description

In my restaurant (large building), even with a cleaner assigned I still regularly get the task that cleaning is needed. The task will disappear at midnight, and it will only show for this business, not for my gift shop (small building).
Having a cleaner should be sufficient to get through the day without this message. So I guess the generated dirt needs to be reduced (or the task just needs to be hidden in this case).

### Savegame file

[Build322-DirtyRestaurantOrJustDirtyMind.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877886/Build322-DirtyRestaurantOrJustDirtyMind.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149676924-693ace06-f99a-4d9b-80ce-e32209b631cb.mp4

**Comment by David-Goru** [comment]
Fixed in build 327
