### ISSUE TITLE
Law Firm gets broken permanently when adding more than two desks

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#760]
### Build number

322

### Bug description

After having the law firm equipped with 2 desks and employees, I added 8 more desks and now try to assign a third employee.
The assignment doesn't work, instead I get an error. Afterwards the BizMan will only show two desks, and the Mop schedule will show above the desks.
When saving and reloading, the business hours are showing empty and the only employee is "John Doe", I still only see two desk slots and the mop above.
When clicking in the business hour row, the new slot plus the previous one will show up.
After closing and reopening the BizMan, it will show the same as it did before saving and reloading the game (mop on top, then two desks, but all employees available and the correct business hours).

### Savegame file

[Build322-LawFirmDone.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877909/Build322-LawFirmDone.json.txt)

[Build322-IBrokeIt-DavidFixItPlease.json.txt](https://github.com/hovgaardgames/bigambitions/files/7877910/Build322-IBrokeIt-DavidFixItPlease.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149677743-2527254d-3cbe-4495-89e0-52b19d9615a3.mp4

**Comment by David-Goru** [comment]
Fixed in build 324
