### ISSUE TITLE
BizMan Scheduler: Wrong color for employees when filtering cleaners

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#761]
### Build number

322

### Bug description

When filtering cleaners from the BizMan's Schedule screen, the colors of the employees don't match anymore.
My two lawyers automatically change their color to the one that was previously assigned to the first two cleaners.

### Savegame file

[Build322-LawFirmDone.json.txt](https://github.com/hovgaardgames/bigambitions/files/7884525/Build322-LawFirmDone.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/149834071-4a655758-7eed-4f3b-9ad6-1140a6b04105.mp4

**Comment by David-Goru** [comment]
Fixed in build 323
