### ISSUE TITLE
Marketing Agency: Sitting offset to seat location

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#763]
### Build number

328

### Bug description

When sitting down in the marketing agency, I'm sitting a bit offset to the chair with half of my leg inside the armrest.
This happens randomly, the seating location always varies a bit. Sometimes it's fine but it can go too far to both sides of the chair.

### Savegame file

[Build322-HalfLeggedHurtsTwice.json.txt](https://github.com/hovgaardgames/bigambitions/files/7891655/Build322-HalfLeggedHurtsTwice.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/150001303-811ca624-0928-44ca-9a98-9ec1229fb8f5.png)

**Comment by David-Goru** [comment]
Fixed in build 329
