### ISSUE TITLE
Marketing Agency: Desks and counters are just an illusion (you can walk through them)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#764]
### Build number

328

### Bug description

You can walk through the desks and counters at the marketing agency.

### Savegame file

[Build322-HalfLeggedHurtsTwice.json.txt](https://github.com/hovgaardgames/bigambitions/files/7891693/Build322-HalfLeggedHurtsTwice.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150002527-14de776d-2acc-4784-a742-88433ac07ef9.mp4

**Comment by jokoho48** [comment]
Fixed in Build 331
