### ISSUE TITLE
Wrong tasks for employees (not assigned to a business, not assigned to any tasks)

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#765]
### Build number

328

### Bug description

After hiring several new employees and assigning their shifts, I get the following errors:
- For all newly hired lawyers, I get a task that they're not assigned to any task although they are in the scheduler (checked for today). For previously hired lawyers it's all fine.
- For employees on training it shows that they're not assigned to any business. This not just for new employees but also for the older ones. It affects one CustomerService, one Lawyer and one Cleaning (you could argue that the cleaning one is correct, as they can be assigned while being on training).

The second issue (not assigned to any business) disappears after the full hour; the first issue persists.

### Savegame file

[Build322-IHateMyTasks.json.txt](https://github.com/hovgaardgames/bigambitions/files/7891748/Build322-IHateMyTasks.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150004048-182227a2-3c99-4c49-bfd7-022fe04a05b4.mp4

**Comment by David-Goru** [comment]
Fixed in build 331
