### ISSUE TITLE
Entering apartment 34 Fifth Avenue breaks several things in game

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#766]
### Build number

328

### Bug description

When entering the apartment 34 Fifth Avenue, the following things break:

- Hand truck in apartment gets duplicated when picking
- After leaving, car parked on the street appears (first after loading it's not there), and every further time gets duplicated
- Entering the car will zoom in instead of the zoomed-out view
- Saving the game doesn't work anymore

Things get fixed by entering another building. Then you can save again, but after reloading the save all your cars will be gone again (I have a second car parked in front of the car dealer that is also hidden after reloading).

### Savegame file

[Build322-ApartmentBugs.json.txt](https://github.com/hovgaardgames/bigambitions/files/7892122/Build322-ApartmentBugs.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150013201-37e582ea-caa9-4ad6-9864-ce0596f7f247.mp4

**Comment by David-Goru** [comment]
Fixed in build 330
