### ISSUE TITLE
No customers in law firm

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#767]
### Build number

328

### Bug description

The law firm never gets any customer, even though all workstations are occupied by employees and an advertising campaign is active.

### Savegame file

[Build322-NooneWantsLawyers.json.txt](https://github.com/hovgaardgames/bigambitions/files/7892303/Build322-NooneWantsLawyers.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150016253-b07e743f-17be-4e03-97b4-277ca3f231f9.mp4

**Comment by jokoho48** [comment]
Fixed in Build 322
