### ISSUE TITLE
Restaurant doesn't sell anymore after one "shelf" is empty

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#768]
### Build number

328

### Bug description

The fast food restaurant stops selling products if one shelf is empty, even if there's another shelf containing the item.
You can see in the savegame that for every product I got two "shelves". Those where one of them is empty are not sold anymore. At the same time I don't get a warning message because the restaurant is not running out of those items.

### Savegame file

[Build322-RestaurantRefusesSales.json.txt](https://github.com/hovgaardgames/bigambitions/files/7892342/Build322-RestaurantRefusesSales.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150017318-8f4d00c6-1919-4b25-84b0-9d80dbed305c.mp4

**Comment by David-Goru** [comment]
Fixed in build 329

**Comment by Ampire-M** [comment]
Issue persists in build 337

**Comment by David-Goru** [comment]
> Issue persists in build 337

Could you please attach a savegame with the issue? Thank you!

**Comment by Ampire-M** [comment]
Sure, but I must warn you. The game is a bit broken there. You can just sleep and look at the stock items for FastFood business(e.g. Hot-Dogs, Burgers, Pizza).
[Ampire.zip](https://github.com/hovgaardgames/bigambitions/files/7978871/Ampire.zip)

**Comment by David-Goru** [comment]
This issue happens when simulating a retail business when being outside of it and having a station (HotDogGrill, PizzaOven...) empty. 

It should be fixed in the next version, thank you for reporting it!

**Comment by Ampire-M** [comment]
Thank you.
