### ISSUE TITLE
Low traffic index in Hell's Kitchen

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#769]
### Build number

328

### Bug description

Traffic index only depends on nearby roads but not building sizes in the area.
This results in most buildings in Hell's Kitchen having a very low traffic index even though skyscrapers should cause lots of traffic.

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/150017877-325625c8-f90f-4905-8a25-df6789b93d4e.png)

**Comment by jhovgaard** [comment]
Fixed in build 331
