### ISSUE TITLE
Car horns still heard in 17th Street Apartment [Low Priority]

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#770]
### Build number

331

### Bug description

On starting a new game and entering the 17th street apartment a truck horn is heard multiple times very loudly, like you are blocking a truck in the road.

### Savegame file

[Horn.txt](https://github.com/hovgaardgames/bigambitions/files/7898755/Horn.txt)

### Screenshots or videos

Unable to get video so far

**Comment by adameg2305** [comment]
Update:

Its when you walk in the apartment it plays the sound

https://user-images.githubusercontent.com/44293115/150171929-7b9bb6f3-f2e2-479d-810d-2ffb929b2d18.mp4

.

**Comment by jokoho48** [comment]
Fixed in Build 332
