### ISSUE TITLE
Car always horns on the player after approching closely when waiting in road queue for traffic light

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#771]
### Build number

332

### Bug description

Car always horns on the player after approching closely when waiting in road queue for traffic light

### Steps to reproduce the bug

1. Get in the car
2. Drive to the nearest traffic light which displays the red signal
3. Wait for npc to approach the player on a car

**Expected result:** NPC **doesn't horn** on the player whilst waiting in the queue for traffic light
**Actual result:** NPC **horns** on the player whilst waiting in the queue for traffic light

**Comment by David-Goru** [comment]
Fixed in the past
