### ISSUE TITLE
Resupply Contracts: WholesaleStore is only delivering the first position to the "Bussiness" and with incorrect amount

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#772]
### Build number

332

### Bug description

Resupply Contracts: WholesaleStore is only delivering the first position to the "Bussiness" and with incorrect amount

### Steps to reproduce the bug

1. Contact WholesaleStore
2. Create a contract for "CheapGifts" with amount "3" boxes on the next day from the current
3. Create a contract for "ExpensiveGifts" with amount "3" boxes on the next day from the current
4. Wait for delivery date.

**Expected result:** WholesaleStore delivered "CheapGifts" with amount "3" and "ExpensiveGifts" with amount "3"
**Actual result:** WholesaleStore delivered only "CheapGifts" with amount **"1"**

### Savegame file

[Ampire.zip](https://github.com/hovgaardgames/bigambitions/files/7910831/Ampire.zip)

**Comment by David-Goru** [comment]
Fixed on build 334
