### ISSUE TITLE
Hand truck is not accessible in 16th FourthAvenue ApplicationStore

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#773]
### Build number

332

### Bug description

Hand truck is not accessible in 16th FourthAvenue ApplicationStore

### Steps to reproduce the bug

1. Go to 16th FourthAvenue ApplicationStore
2. Go to the hand truck in the top left corner of the shop

**Expected result:** User **takes** the hand truck
**Actual result:** User **cannot take** the hand truck

### Screenshots or videos

![изображение](https://user-images.githubusercontent.com/96728197/150477880-2f29d0a3-5964-4bb2-baf8-74d411b10f6b.png)

**Comment by David-Goru** [comment]
Fixed in build 336
