### ISSUE TITLE
Pedestrians stop whenever the player clicks "Interview" but whilst the player is running to the pedestrian clicks "WASD"

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#774]
### Build number

332

### Bug description

Pedestrians stop whenever the player clicks "Interview" but whilst the player is running to the pedestrian clicks "WASD"

### Steps to reproduce the bug

1. Hover with mouse the pedestrian
2. Click "Interview"
2. During player movement to pedestrian press "W"/"A"/"S"/"D"

**Expected result:** Pedestrians proceeds his journey
**Actual result:** Pedestrian stops until user clicked anywhere/or walk to pedestrian

**Comment by David-Goru** [comment]
That's intended! So you can interview them, making it easier to click the interview button. :)

**Comment by Ampire-M** [comment]
Oh, ok. But, what about the fact that they don't proceed to walk after hover is removed?

**Comment by David-Goru** [comment]
That would be a bug, yes! I can't seem to reproduce it, though. If you find the steps to get that bug, comment them here and we'll check it!

**Comment by Ampire-M** [comment]
I finally got to my PC, and reproduced it, updated the steps.

**Comment by David-Goru** [comment]
Beta 2 removes interviews. Closing this
