### ISSUE TITLE
Invert Rotation doesn't apply to hotkeys "Q" and "E"

### ISSUE THREAD

**Issue by Ampire-M** [hovgaardgames/bigambitions#775]
### Build number

332

### Bug description

Invert Rotation doesn't apply to hotkeys "Q" and "E"

### Steps to reproduce the bug

1. Select "Invert Rotation" in game options
2. Load game/Start New game
3. Press "Q"

Expected result: Screen is mover to the **left**
Actual result: Screen is mover to the **right**

3. Press "E"

Expected result: Screen is mover to the **right**
Actual result: Screen is mover to the **left**

**Comment by David-Goru** [comment]
Fixed in build 336
