### ISSUE TITLE
Subway ride will show only small parts of the map

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#777]
### Build number

335

### Bug description

When riding the subway, only small parts of the map are shown, the rest is just grey void.

### Steps to reproduce the bug

Start a new game, walk to nearest subway, take a ride.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150580688-e756277f-ae75-4da6-9860-eab154e350e7.mp4

**Comment by jhovgaard** [comment]
Fixed in build 338
