### ISSUE TITLE
Big Ambitions monument is walkable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#778]
### Build number

335

### Bug description

It's possible to walk through the BA monument near the starting position.
The fences are not preventing the player from going there and the monument itself appears to be just a hologram.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150581651-4887cb9d-6ab3-464d-a26e-908d25cc2833.mp4

**Comment by jokoho48** [comment]
I add the Monument in Madison Square Park to that List 😄

**Comment by David-Goru** [comment]
Fixed in the past
