### ISSUE TITLE
Halo Effect around player

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#779]
### Build number

337

### Bug description

When walking past a tree there is a halo effect around the player which doesn't display the leaves on the tree

### Savegame file

[Xray.txt](https://github.com/hovgaardgames/bigambitions/files/7918087/Xray.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/44293115/150634324-5c644942-69d3-4af0-a544-2363d3c2075c.mp4

**Comment by Gerwanese** [comment]
That's not a bug but the newest feature implemented by Jonas#2. 😄 This should make it easier to follow the player especially in the park.
