### ISSUE TITLE
Mop buying task doesnt complete if purchased before task shows

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#780]
### Build number

337

### Bug description

If you buy a mop from the appliance store before the mop buying task shows then the task won't complete

**Comment by Gerwanese** [comment]
It goes away after finishing the other task (cleaning the business), but still a bug as it might lead players to buy a second mop.
[Build337-MopAwayMyTask.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918351/Build337-MopAwayMyTask.json.txt)

https://user-images.githubusercontent.com/17579552/150639437-3215d424-6457-4dbe-8fca-45438faabf5e.mp4
