### ISSUE TITLE
Newly rented building become rented by AI

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#781]
### Build number

337

### Bug description

Just rented my second retail shop opened the business then overnight the building was then rented again by an in-game business. 
The map still displays the business as mine, along with the POI marker, however, hovering over the building shows it's privately owned.

### Savegame file

[Building over rented.txt](https://github.com/hovgaardgames/bigambitions/files/7918224/Building.over.rented.txt)

### Screenshots or videos

![NVIDIA_Share_cU5HL9sv8N](https://user-images.githubusercontent.com/44293115/150636897-f7afacc0-62db-45c0-b93a-9ad6d7583465.jpg)

**Comment by Gerwanese** [comment]
After loading the savegame, the marker is gone.
This seems to be an issue that we already got reported in the community, disappearing businesses: https://community.bigambitionsgame.com/t/my-business-just-disappeared/651

**Comment by Gerwanese** [comment]
Buildings we got this with already: 
- 13 4th Ave
- 22 4th Ave
- 26 Fifth Ave

**Comment by Gerwanese** [comment]
It appears to be done by the automatic open/close updates for Market Insider:
![grafik](https://user-images.githubusercontent.com/17579552/150641869-a292d28c-4ab8-4020-ac81-10dcae2b836e.png)

**Comment by jhovgaard** [comment]
Fixed in build 338
