### ISSUE TITLE
Opening map possible while dialog is open and won't close the dialog

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#783]
### Build number

337

### Bug description

It is possible to open Voogle Maps while a dialog is open. The dialog will stay open on the map and is still usable.

### Savegame file

[Build337-MappyMapVSDuffyDialog.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918308/Build337-MappyMapVSDuffyDialog.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150638530-db5a7579-5fde-41db-a156-1af79fb6c707.mp4

**Comment by David-Goru** [comment]
Fixed in build 745
