### ISSUE TITLE
Possible to walk into drinks fridges at recruitment agency

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#784]
### Build number

337

### Bug description

At the recruitment agency it is possible to walk "into" the drinks fridges, they're not blocking.

### Savegame file

[Build337-InsideCozyFridge.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918316/Build337-InsideCozyFridge.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150638704-eff886d9-36c7-4b4a-8b83-45680e1a9c38.mp4

**Comment by David-Goru** [comment]
Fixed in build 465
