### ISSUE TITLE
Hand truck can be picked up twice, after parking one will remain inside the player

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#786]
### Build number

337

### Bug description

It is possible to pick up another hand truck while you already hold one.
Afterwards, if you park the hand truck, the second one will be stuck inside you and you'll take it for a walk.

### Savegame file

[Build337-RideMyHandtruck.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918333/Build337-RideMyHandtruck.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150639052-e166fe75-dde7-40ff-a42b-5203e75cacf1.mp4

**Comment by jokoho48** [comment]
Fixed in Build 455
