### ISSUE TITLE
Can't load savegame if saved while holding a hand truck

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#787]
### Build number

337

### Bug description

If a game is saved while holding a hand truck, it will be impossible to load it.

### Savegame file

Okay (saved before getting the hand truck):
[Build337-RideMyHandtruck.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918339/Build337-RideMyHandtruck.json.txt)

Broken (saved after getting the hand truck):
[Build337-RideMyHandtruck2.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918342/Build337-RideMyHandtruck2.json.txt)

**Comment by jhovgaard** [comment]
Fixed in build 338
