### ISSUE TITLE
Loading a game that was saved while paused will load in a very bright state

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#788]
### Build number

337

### Bug description

If you load a savegame that was saved while being paused, it will load looking very bright. Also the map is very bright as well. Once you unpause the game it will go to normal colors.

### Savegame file

[Build322-ScrollMyBizMan.json.txt](https://github.com/hovgaardgames/bigambitions/files/7918404/Build322-ScrollMyBizMan.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150640349-0f5b14e4-9144-4f91-b06d-b50ee14ba9b9.mp4

**Comment by CoolGingerGinger** [comment]
This bug seems to have changed slightly with the alpha 10 (build 488). I get a really cool abstract view that persists until unpausing. 

![loading while paused](https://user-images.githubusercontent.com/88410729/157592995-575d54f3-03b2-4fd6-9737-6e5668025572.png)

**Comment by David-Goru** [comment]
Fixed in build 870
