### ISSUE TITLE
No customer in jewelry store 

### ISSUE THREAD

**Issue by SHALEVa7x** [hovgaardgames/bigambitions#794]
### Build number

337

### Bug description

I have the same issue as error #781 but in 30 Fifth Ave, and when I start a new business at the same place so no customer comes in...

**Comment by Gerwanese** [comment]
[A7X.json.txt](https://github.com/hovgaardgames/bigambitions/files/7919121/A7X.json.txt)

**Comment by jokoho48** [comment]
Fixed in Build 339
