### ISSUE TITLE
Slider Overlaps duration of Ad campaign 

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#796]
### Build number

337

### Bug description

When organising an advertising campaign and select the 12 week duration the slider overlaps the 1 which makes it hard to read.

### Screenshots or videos

![Big_Ambitions_X0DpCRwESd](https://user-images.githubusercontent.com/44293115/150654446-42d7da19-a9a1-4b23-ad02-900de9d05c1f.png)

**Comment by Gerwanese** [comment]
[Build322-HalfLeggedHurtsTwice.json.txt](https://github.com/hovgaardgames/bigambitions/files/7919237/Build322-HalfLeggedHurtsTwice.json.txt)

**Comment by David-Goru** [comment]
Fixed in build 342
