### ISSUE TITLE
I can no longer hire employees

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#799]
### Build number

337

### Bug description

when I ask for an employee in recruitment I never have it and recruitment is endless

### Steps to reproduce the bug

no idea sory

### Savegame file

[Big Ambitions.zip](https://github.com/hovgaardgames/bigambitions/files/7923121/Big.Ambitions.zip)

**Comment by David-Goru** [comment]
Fixed in build 343

If you want a temporary solution, add a Cash register or Checkout counter to the business "Au Burger", and cancel/start again the recruitment campaign. The bug was due to the system not finding any work station at "Au Burger" and throwing a bunch of errors
