### ISSUE TITLE
Disable zooming for pedestrian cam when dialog is active

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#800]
Only the UI content should listen to mouse scroll in this scenario:
https://user-images.githubusercontent.com/1388347/150760007-f54447a1-5714-45d3-8b66-ecbbc7f88d24.mp4

**Comment by Gerwanese** [comment]
Related to #742, maybe solution of that issue can be updated to contain whole dialogs.

**Comment by David-Goru** [comment]
Fixed in build 1139
