### ISSUE TITLE
Pressing F1 then F2 Can lead to camera rotation breaking

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#802]
### Build number

339

### Bug description

Pressing F1 and then F2 while UI is hidden will lead to a error (Below) the camera will then not rotate or move until you press F2 twice more to reactivate then deactivate

"Coroutine couldn't be started because the the game object 'Screenshot' is inactive!
UnityEngine.MonoBehaviour:StartCoroutine (System.Collections.IEnumerator)
ScreenshotController:EnableFreeLookCamera ()
ScreenshotController:ToggleFreeLookCamera ()
GameManager:GlobalKeyEvents ()
GameManager:Update ()"

### Savegame file

[Camera.txt](https://github.com/hovgaardgames/bigambitions/files/7928803/Camera.txt)

**Comment by Gerwanese** [comment]
Also mouse is hidden for me in that case.

**Comment by jokoho48** [comment]
Fixed in Build 339.
