### ISSUE TITLE
Leaf Hiding not always effective while driving

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#803]
### Build number

339

### Bug description

When driving the car can sometimes still be hidden by trees 

### Savegame file

[Leaf Xray.txt](https://github.com/hovgaardgames/bigambitions/files/7928865/Leaf.Xray.txt)

### Screenshots or videos

![Big_Ambitions_oCiZUYuDKj](https://user-images.githubusercontent.com/44293115/150864893-5fff771e-91d7-4e53-9c16-5f0a14f5dcd9.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 447.
