### ISSUE TITLE
Spelling errors in MyEmployees app

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#804]
### Build number

338

### Bug description

In the MyEmployees app, there are two spelling mistakes:
- "Employees gets" should be "Employees get" (and later on "rest" instead of "rests")
- "they" should be "their"

### Savegame file

[Build337-FreeRefill.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929031/Build337-FreeRefill.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/150869682-5f85734a-1b59-4e80-9901-b0dbb5e8d151.png)

**Comment by David-Goru** [comment]
Fixed in build 342
