### ISSUE TITLE
Car can drive through Ikea's fence

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#805]
### Build number

338

### Bug description

It's possible to drive through Ikea's fence, while walking through it is impossible.

### Savegame file

[Build337-BreakingIntoIkea.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929061/Build337-BreakingIntoIkea.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/150870587-b1bf04ef-f026-4997-a5cb-57c4be136b72.png)

**Comment by jokoho48** [comment]
Fixed in Build 453.
