### ISSUE TITLE
Too many people spawning at once at Ikea

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#806]
### Build number

339

### Bug description

When entering Ikea, too many people spawn at once at the entrance. Better either reduce the number, or alternatively have several "spawn points" in the building where people spawn.

### Savegame file

[Build337-BreakingIntoIkea.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929104/Build337-BreakingIntoIkea.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150872255-25f763ce-c9dd-4f84-988e-c07e892a8e64.mp4

**Comment by jokoho48** [comment]
Fixed in Build 1014
