### ISSUE TITLE
AI fast food restaurant employees stop serving after a short while

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#809]
### Build number

339

### Bug description

When visiting a generated AI fast food restaurant, after a short while the employees stop serving. It doesn't matter whether you are queued or not.

### Savegame file

[Build337-SlowFoodRestaurant.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929278/Build337-SlowFoodRestaurant.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150876262-a5a5f65e-c63b-487b-8008-7fd3b16cb9d7.mp4

**Comment by David-Goru** [comment]
Fixed in the past
