### ISSUE TITLE
AI Fast food restaurant: Clicking the counter instead of the small cash register makes you walk to the employee side of the counter

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#810]
### Build number

339

### Bug description

When clicking the counter instead of a cash register at the fast food restaurant, you will walk around it to the employee side.
This is quite annoying as the cash register is pretty small and easy to miss (and additionally, players know from there own shops that they can click the counter as well).

### Savegame file

[Build337-SlowFoodRestaurant.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929314/Build337-SlowFoodRestaurant.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150876631-25d51737-e8a3-4e95-95b5-2b17fbfe4bec.mp4

**Comment by jokoho48** [comment]
Fixed in Beta 4
