### ISSUE TITLE
Can't consume CupOfCoffee and Croissant

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#811]
### Build number

339

### Bug description

When buying stuff at the coffee shop, you can only consume ("Eat") the SodaCan but not CupOfCoffee and Croissant.

### Savegame file

[Build337-DontDrinkCoffee.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929335/Build337-DontDrinkCoffee.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150877123-9dc208c6-6030-471b-92f2-6df6061abcab.mp4

**Comment by David-Goru** [comment]
Fixed in build 343
