### ISSUE TITLE
Clock and Time issues

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#812]
### Build number

339

### Bug description

The main clock is in the 24hour format however in the contacts app the clock is in the 12hour format

And the clock in top right displays the time as 17:08 however in the contacts app it displays as xx:09

### Savegame file

[TVA.txt](https://github.com/hovgaardgames/bigambitions/files/7929334/TVA.txt)

### Screenshots or videos

![Big_Ambitions_mGjuG0GUKX](https://user-images.githubusercontent.com/44293115/150876926-2ded6512-c86b-45e7-97b9-c096241f1115.png)

**Comment by David-Goru** [comment]
Fixed in build 447
