### ISSUE TITLE
Appliance Store: Buy 3, Pay 4!

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#813]
### Build number

339

### Bug description

If you pick up an item at the appliance store first and then (with the box in your hands) click on the hand truck, the price of the box is doubled. You can add more items to the hand truck but the total price keeps being one item too much.

### Savegame file

[Build337-Buy3Pay4.json.txt](https://github.com/hovgaardgames/bigambitions/files/7929360/Build337-Buy3Pay4.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/150877620-1ff043c3-c638-4491-b59b-96187d58195a.mp4

**Comment by jokoho48** [comment]
Fixed in Build 339
