### ISSUE TITLE
Market Insider: Click on item closes map if already open

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#817]
### Build number

340

### Bug description

In "normal" mode (map closed), if you open the MarketInsider app and click on any line, it will open the map and show the location.
However, ff the map is already opened and then you start the MarketInsider app, a click will just close the map.

### Savegame file

[Build340-MarketWrongsider.json.txt](https://github.com/hovgaardgames/bigambitions/files/7944726/Build340-MarketWrongsider.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/151233964-76d82cc2-3ad4-4093-bd71-8aa09a33f296.mp4

**Comment by jokoho48** [comment]
Fixed in Build 594.
