### ISSUE TITLE
Не поступают продукты 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#820]
### Build number

337

### Bug description

Заказываю продукты в некоторые закусочные , а они не доставляются пишет что полки полные ( полки пустые)

**Comment by adameg2305** [comment]
Could you please provide the save game, on windows its located in C:\Users\{username}\AppData\LocalLow\Hovgaard Games\Big Ambitions\alpha9

Не могли бы вы предоставить сохранение игры, в Windows оно находится в    (Google Translate)

**Comment by David-Goru** [comment]
Closed until more information available
