### ISSUE TITLE
не могу зайти в супермаркет 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#821]
### Build number

337

### Bug description

Не могу зайти в супермаркет ( который выделил) . так же стоит мой супермаркет рядом. в который тоже не заходит 

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/151586508-e3721c43-f7a7-489a-bf53-e58156d2dc52.png)

**Comment by David-Goru** [comment]
Hello! Is it possible that the supermarket was closed at that time? It could have an opening hour later than 08.40. Opening it in BizMan should show the hours.

**Comment by David-Goru** [comment]
Closed until more information available
