### ISSUE TITLE
WASD

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#823]
### Build number

337

### Bug description

взял в магазине paper . не смог его положить в кассу  и вообще проало передвижение на клавиатуре , осталось только мышь , и перестал брать предметы в руки 

### Savegame file

не могу найти сохранение.

**Comment by jhovgaard** [comment]
Hey! I tried running your description through Google Translate, but I still don't understand the issue. Is it possible you can send me an English description of the problem?

**Comment by David-Goru** [comment]
Closed until more information available
