### ISSUE TITLE
No building Value or Rent 

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#824]
### Build number

344

### Bug description

76 First Street doesnt have a market value, Deposit or Rent Value or Building Area set.

### Savegame file

[FreeBuilding.txt](https://github.com/hovgaardgames/bigambitions/files/7964081/FreeBuilding.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/151668433-e46f2f0f-8eb3-41fa-87f9-930d4f55b3d0.png)

**Comment by David-Goru** [comment]
Fixed in build 473
