### ISSUE TITLE
BizMan all empty after update

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#826]
### Build number

340

### Bug description

In build 340, BizMan shows all empty sales data. EconoView still got the old data.
(be aware that the law firm might be empty due to another previous bug, but fast food restaurant and gift shop should have data)

### Savegame file

[Build340-MarketWrongsider.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964234/Build340-MarketWrongsider.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/151671358-3d281491-64f3-4583-ac9c-784dcf08695b.png)

![grafik](https://user-images.githubusercontent.com/17579552/151671367-8ccb88dc-e22b-4d27-90d9-41709a27b8a2.png)

![grafik](https://user-images.githubusercontent.com/17579552/151671389-863a602c-ebb8-49ea-8980-b65782482aae.png)

**Comment by Gerwanese** [comment]
Before the update (saved on 339):
[Build337-Buy3Pay4.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964251/Build337-Buy3Pay4.json.txt)

**Comment by jhovgaard** [comment]
Fixed in build 341
