### ISSUE TITLE
BizMan: Only salad sold in fast food restaurant

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#827]
### Build number

340

### Bug description

The fast food restaurant doesn't sell anything but salad anymore, and customers don't like this product range.

### Savegame file

[Build340-StayHealthyWithSaladOnlyYouFool.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964250/Build340-StayHealthyWithSaladOnlyYouFool.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/151671686-36d85be9-480b-4894-9853-34203b3e3dd8.png)

![grafik](https://user-images.githubusercontent.com/17579552/151671693-eb74593f-1c61-4012-9ab3-c8f5a2d14a4a.png)

![grafik](https://user-images.githubusercontent.com/17579552/151671696-2f64cfc7-b92e-480b-bc7f-61c6c7f5932f.png)

**Comment by Gerwanese** [comment]
Before the update (saved on 339):
[Build337-Buy3Pay4.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964251/Build337-Buy3Pay4.json.txt)

**Comment by Ckeptikya** [comment]
а как обновить сборку до 340? 

> Перед обновлением (сохранено на 339): [Build337-Buy3Pay4.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964251/Build337-Buy3Pay4.json.txt)

**Comment by jokoho48** [comment]
Fixed in Build 341.
