### ISSUE TITLE
Bank not giving me 1.3 mio because limit is 1.365 mio

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#828]
### Build number

340

### Bug description

The bank isn't giving me the money even though I'm asking for less than the allowed limit.

### Savegame file

[Build340-BankersAreAllLiers.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964284/Build340-BankersAreAllLiers.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/151672404-d7bca32f-e841-4544-9984-e5d12da4076a.png)

**Comment by Gerwanese** [comment]
Maybe a hint for the reason: The $1300000 requested appears twice in my bank contact history.
After that, they completely refuse to give any further credit no matter what I ask.
![grafik](https://user-images.githubusercontent.com/17579552/151672704-9864a2ea-c265-4244-9c75-acb32786d9b8.png)

**Comment by jokoho48** [comment]
cant not reproduce but the save game was broken due to not correctly executed savegame compat fixes. so i think it is related to that
