### ISSUE TITLE
Call button missing from contacts

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#829]
### Build number

340

### Bug description

There seems to be no way anymore to call my contacts. The Call button is gone.

### Savegame file

[Build340-BankersAreAllLiers.json.txt](https://github.com/hovgaardgames/bigambitions/files/7964291/Build340-BankersAreAllLiers.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/151672495-2368d83a-36f9-4b30-b36c-39091c273237.mp4

**Comment by Gerwanese** [comment]
Additionally, all pictures are gone from the contacts. :)

**Comment by jokoho48** [comment]
Fixed in Build 342
