### ISSUE TITLE
Доставка не работает 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#830]
### Build number

337

### Bug description

у меня где то 1500 потребления товаров в день в магазине , сделал график в 3 магазина на каждый день. доставка просто не приезжает. ишет сообшение что полки полные . а полки пустые

**Comment by David-Goru** [comment]
Hello! Can you send us your savegame? (C:\Users\%USERNAME%\AppData\LocalLow\Hovgaard Games\Big Ambitions\alpha9 if you're using Windows)

**Comment by David-Goru** [comment]
Closed until more information available
