### ISSUE TITLE
Build Number

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#832]
### Build number

337

### Bug description

does the build version update itself? or do I need to do something? because I see that people have version 340 on topics , but I still have 337
![image](https://user-images.githubusercontent.com/98607052/151707941-264ee329-a179-4b67-b272-1b109c3d4912.png)

### Screenshots or videos
![Uploading image.png…]()

**Comment by adameg2305** [comment]
Yes, the game will automatically update (Unless changed via steam) Build 337 is the latest public release. There is a handful of people who help test internal builds (Before public) which is why there is a slight discrepancy between the builds.
