### ISSUE TITLE
Cant leave map view

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#833]
### Build number

345

### Bug description

Entered map view while in 17th Third Street, clicked on Jensen Capital then viewed bizman, when pressing ESC to leave the map view the animation doesn't play, however, the grey effect does go away but you are still in the ariel view. 
There is no way to leave the view, so once in there you are stuck.

### Steps to reproduce the bug

Head to 17 Third Street
Go inside
Open map
Click on Jensen Capital then right-click to open bizman
Click ESC to leave map view 

### Savegame file

[map.txt](https://github.com/hovgaardgames/bigambitions/files/7966853/map.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/44293115/151716333-3a821d35-05ca-4ad1-883d-8684bb6c7ad3.png)

**Comment by adameg2305** [comment]
[Player.log](https://github.com/hovgaardgames/bigambitions/files/7966856/Player.log)

**Comment by David-Goru** [comment]
Can't reproduce the bug

**Comment by jokoho48** [comment]
was caused by missing meshes in CBC. fixed a few days ago :D
