### ISSUE TITLE
Missing error message when clicking on fresh food without a shopping basket

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#834]
Should show notification warning "You need a shopping basket to buy this product".

**Comment by Gerwanese** [comment]
Ideally for all shop types and items that need the shopping basket.

**Comment by jhovgaard** [comment]
> Ideally for all shop types and items that need the shopping basket.

Agree!

**Comment by David-Goru** [comment]
Fixed in build 447
