### ISSUE TITLE
after upgrading from 337 to version 344, the businesses that was making a profit stopped making it

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#835]
### Build number

344

### Bug description

sales are going on, but on the business tab, the product range is always 0, although products are imported and sold . at the same time, the income of a well-established business is constantly in a negative state

I also found out that while I'm not in the store, there doesn't seem to be anyone there, as soon as I enter the store, a crowd appears there, the product range grows
### Steps to reproduce the bug

it all started after I went to bed
even starting a new game , if you go to bed , the indicators of the product range will become 0%

### Savegame file

[no cash [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/7987526/no.cash.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/152176211-efd8bffb-279d-4cbb-93fa-c4d93625164c.png)
![image](https://user-images.githubusercontent.com/98607052/152176919-c4ecc7b7-ca5b-406f-bcb0-d9888c2de2b3.png)
![image](https://user-images.githubusercontent.com/98607052/152176936-52f5b9bc-c800-4f64-bdbc-ae5c74988b3e.png)
![image](https://user-images.githubusercontent.com/98607052/152178086-ceaf8358-a37c-4f89-99d0-5345f162a3af.png)

**Comment by fenix849** [comment]
I'm also experiencing this issue.

**Comment by Ckeptikya** [comment]
> Я также испытываю эту проблему.
> 
> У меня есть скриншоты этой проблемы, но я не уверен, что их публикация здесь нарушит правила альфа-версии. Я могу предоставить их через discord или по электронной почте.

I don't think so, since there are YouTube channels that release videos on this game

**Comment by Ckeptikya** [comment]
> Я также испытываю эту проблему.
> 
> У меня есть скриншоты этой проблемы, но я не уверен, что их публикация здесь нарушит правила альфа-версии. Я могу предоставить их через discord или по электронной почте.

if you find a solution, write)

**Comment by jhovgaard** [comment]
Fixed in build 348
