### ISSUE TITLE
Не нанимается персонал

### ISSUE THREAD

**Issue by dimavin230305** [hovgaardgames/bigambitions#838]
### Build number

344

### Bug description

Я как надо нанимаю персонал оплачиваю потом мне приходит письмо а в письме пусто

**Comment by dimavin230305** [comment]
А еще не могу загрузить игру после сохранения

**Comment by David-Goru** [comment]
Hi! Could you please attach a savegame? (C:\Users%USERNAME%\AppData\LocalLow\Hovgaard Games\Big Ambitions\alpha9 if you're using Windows)

**Comment by dimavin230305** [comment]
хорошо

**Comment by dimavin230305** [comment]
https://disk.yandex.ru/d/M0QY5zbKYe_ntQ

**Comment by dimavin230305** [comment]
У меня только так получилось

**Comment by dimavin230305** [comment]
У меня там машина еще застряла

**Comment by dimavin230305** [comment]
И доход от бизнесов не поступает.

**Comment by Ckeptikya** [comment]
> И доход от бизнесов не поступает.

это походу у всех баг. что дохода нет

**Comment by dimavin230305** [comment]
Я аккаунт создал только после обновы

**Comment by Ckeptikya** [comment]
> Я аккаунт создал только после обновы

solved the problem?

**Comment by dimavin230305** [comment]
Нет

**Comment by dimavin230305** [comment]
Никто даже не ответил

**Comment by David-Goru** [comment]
Hello! I'm really sorry for the late reply.

I've tested the game, and seems like everything works now. If you get another error, don't hesitate to report it!

And please, for the next issue @dimavin230305 @Ckeptikya, translate both the title and the content to english, so we can easily track the problem and solve it faster. We currently don't have any team member that understands russian, so it's been a bit of a chaos for us :P

Also, if you have any questions on how to attach the savegame here, I can help you.
Thank you!
