### ISSUE TITLE
bug with the bed

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#840]
### Build number

344

### Bug description

I used to write about a bug with income, I uploaded a new save with an excellent income of $ 30,000 per day, went to bed for 1 hour in the afternoon, immediately writes me an income of $ 18,000, although the day has not yet passed
please solve the problem

### Steps to reproduce the bug

go to bed

### Savegame file

the save file is not attached translated to txt

**Comment by David-Goru** [comment]
Closed until more information available
