### ISSUE TITLE
Your invite token has expired. Please contact staff.

### ISSUE THREAD

**Issue by darkwolf66** [hovgaardgames/bigambitions#841]
### Build number

344

### Bug description

![image](https://user-images.githubusercontent.com/2975858/152662690-e45e1f32-7682-4f4d-8bfe-df4dd0f4d203.png)

### Steps to reproduce the bug

Trying to open the button community invite/signup

**Comment by jhovgaard** [comment]
Now fixed. Thanks for reporting!
