### ISSUE TITLE
White screen on trying to open any menu

### ISSUE THREAD

**Issue by darkwolf66** [hovgaardgames/bigambitions#842]
### Build number

344

### Bug description

I just bought and started the game and on any menu I see this:

![image](https://user-images.githubusercontent.com/2975858/152662735-9b474bf5-4c4d-4d69-89a4-bbf1df766a29.png)

**Comment by Ckeptikya** [comment]
the luggage update has passed, now we have to release alpha 10

**Comment by jhovgaard** [comment]
Hi @darkwolf66!

I'm not able to reprodue the issue on my own machine. Is it possible you can click the "Submit Feedback" in-game and enable "Include system information, savegame and screenshot to help us fix the bug.". Just write `Github 842` in the comment so I know it's you :-)

Thanks!

**Comment by darkwolf66** [comment]
Hey, I tried but got this error:
![image](https://user-images.githubusercontent.com/2975858/152717204-0987636d-20f9-4570-81d8-fa3646846c28.png)
also as is the first time i'm playing it I also see this in purple when hovering the building, I'm not sure if is part of the game:
![image](https://user-images.githubusercontent.com/2975858/152717311-dad710eb-5ba7-400b-8d20-c5560d56864f.png)

**Comment by jhovgaard** [comment]
Hi @darkwolf66,

Got it, it still went through, fortunately.

You're playing on an Intel XE Graphics GPU. It's quite new, so the issue might be driver related. First, make sure that your driver is 100% up to date. Intel has a tool to help you with that:
https://www.intel.com/content/www/us/en/support/detect.html

Please let me know if this solves the problem :-)

**Comment by darkwolf66** [comment]
I did updated the graphical drivers and still having the same issue, I think the purple is also related to the graphic card. What would be the next steps to get it fixed?

**Comment by jhovgaard** [comment]
> What would be the next steps to get it fixed?
Alright. With drivers out of the way, we might get some insight from your logfile. Try the following:

1. Start the game and go to a building that shows as purple.
2. Shut down the game right away (ALT+F4).
3. Press WIN KEY+R and paste in `%userprofile%\appdata\locallow\Hovgaard Games\Big Ambitions\`
4. Send the player.log file to me at jonas@hovgaard.com or here (it may contain private information about your Windows installation and computer).

Hopefully that can point us in the right direction.

**Comment by jhovgaard** [comment]
Closing until further info is available.
