### ISSUE TITLE
Ghost notifications in Contacts from recruitment agency

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#843]
### Build number

344

### Bug description

After waiting the necessary time for the recruitment agency to find customer service candidates to hire as part of the mission to hire your first employee, a red notification icon appears on the Contacts button/recruitment agency conversation (I'm assuming to let you know the search for candidates is complete), but only a blank screen appears and the "Call" button does nothing.

I also can't load the save file whenever this happens

### Steps to reproduce the bug

Simply follow the steps for the early mission to hire your first employee

- Complete the 10 hour basic management training course
- Visit the recruitment agency to start the process for a candidate search
- Wait until the time passes and the notifications appear on the Contacts button
- Click the Contacts button and select the recruitment agency

### Savegame file

[save one.txt](https://github.com/hovgaardgames/bigambitions/files/8009926/save.one.txt)

**Comment by dimavin230305** [comment]
У меня такая же проблема

**Comment by dimavin230305** [comment]
Возможно это пофиксят в обнове

**Comment by jhovgaard** [comment]
Fixed in build 347
