### ISSUE TITLE
illegal parking

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#845]
### Build number

348

### Bug description

illegal parking in the area

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/152751242-c5d56630-711c-4f91-b93d-47851baefb03.png)
![image](https://user-images.githubusercontent.com/98607052/152751319-695cc728-3128-499d-895e-35fdb54aa8f1.png)

**Comment by jhovgaard** [comment]
Fixed in build 484
