### ISSUE TITLE
Character stuck after exiting forklift outside of warehouse

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#850]
### Build number

350

### Bug description

Player character can't be moved with either WASD or mouse click after getting out of the forklift while in the NY Distro Inc Wholesale Store car park. Quitting the game entirely and reloading the save doesn't fix the issue. Issue also reproduced in a fresh save.

The issue isn't present when driving the forklift all the way out into the street and getting out - it appears to be an issue exclusively with the car park area.

### Steps to reproduce the bug

- Enter NY Distro Inc Wholesale Store
- Enter forklift
- Drive forklift outside of the warehouse to the car park
- Park the forklift in the car park and try to move the character

### Savegame file

Main save of issue is labelled `sameron1`

Additional save of similar issue `forklift save 2` has a different issue - the Wholesale Store car park is inaccessible when exiting the forklift just at the entrance to the car park

[forklift save 2.txt](https://github.com/hovgaardgames/bigambitions/files/8054906/forklift.save.2.txt)
[sameron1.txt](https://github.com/hovgaardgames/bigambitions/files/8054907/sameron1.txt)

**Comment by samer0n** [comment]
Correction for the second save `forklift save 2` - anything that isn't the sidewalk is inaccessible, I can't even access the street unless there is a pedestrian crossing

**Comment by jokoho48** [comment]
Fixed in Build 453. the forklift is currently not meant to exit DriveIn Buildings this is why this currently breaks. we for now just block that the forklift can exit a DriveIn Building
