### ISSUE TITLE
Handicap spaces are marked as legal parking

### ISSUE THREAD

**Issue by Slickdrac** [hovgaardgames/bigambitions#851]
### Build number

350

### Bug description

More of a suggestion than strictly a bug.
Stopping the car on top of handicap spaces is labeled as "Legal" parking. It'd be really nice if it could be treated as illegal as the character does not have any medical issues that would permit parking there.

Thank you for your consideration :)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/10053421/153756974-1cf56d98-b324-4dbe-ac81-b364da1b1e9d.png)

**Comment by jokoho48** [comment]
Fixed in Build 467
