### ISSUE TITLE
Jewelry Store products not included in customer capacity calcuation

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#853]
### Build number

350

### Bug description

In my Jewelry Store, my product types (Cheap Jewelry and Expensive Jewelry) are not being included in the calculation for hourly customer capacity in BizMan.

I have 2x Points of Sale, 1x Shopping Baskets, 2x Counters with Cheap Jewelry and 2x Counters with Expensive Jewelry. Only the 2x Points of Sale and 1x Shopping Baskets are being included in the calculation. This behaviour is unlike my other stores:

- In my Gift Shop, 1x CheapGift and 1x ExpensiveGift is included in the calculation
- In my Fast Food Restaurant, my variety of food types (Burger, Salad, FrenchFries etc) is included in the calculation

The Gift Shop example is directly comparable to the Jewelry Store with respective cheap and expensive versions of the product, it seems like the behaviour in the hourly calculation is intended to be the same.

**Minor grammatical changes in the Customer Capacity box**

Chucking these in here as well (highlighted in attachment) as it felt like overkill to raise a separate bug, but let me know if you prefer these raised separately:

- Erroneous space in the word "many" in the Customer Capacity explanation copy
- The plural of "point of sale" is "points of sale" - not "point of sales"

### Savegame file

[sameron2.txt](https://github.com/hovgaardgames/bigambitions/files/8056908/sameron2.txt)

### Screenshots or videos

![Customer Capacity copy](https://user-images.githubusercontent.com/99119499/153780291-af9bca8b-d305-4769-8887-bc42baf8c16a.jpg)
![JewelryStore BizMan](https://user-images.githubusercontent.com/99119499/153780292-d52105f3-d25f-4a48-b013-bc44c378d95c.jpg)
![GiftShop BizMan](https://user-images.githubusercontent.com/99119499/153780293-5662ea95-6fd0-493e-b5c2-980f3b3caaf5.jpg)
![FastFoodRestaurant BizMan](https://user-images.githubusercontent.com/99119499/153780296-4240ad17-5cfd-4828-b0e4-016448be7689.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 453.
