### ISSUE TITLE
Calling contacts after midnight (before open) works

### ISSUE THREAD

**Issue by Slickdrac** [hovgaardgames/bigambitions#854]
### Build number

350

### Bug description

Trying to call the callable contacts (Bank, wholesale, etc) after their closed hours fails as expected.

If you call them anytime after midnight, before they are open, they answer and you can do your business with them, which shouldn't work.

You can also call the recruiter on the weekend, when they are closed all day, but they appear as if they have hours from 8-16 and do go closed and nonresponsive after 1600 when you try and call them, but then are open again post midnight when it ticks over to Sunday with the same 8-16 hours

### Steps to reproduce the bug

Sleep or wait until after midnight, wake up and call one of them. Going through scenery change (in/out of buildings) no change, still can call them. Visiting the office and seeing it closed, no change. Saving and reloading, no change. Reloading entire game, no change. They're just effectively open from midnight-closing time

### Screenshots or videos

![image](https://user-images.githubusercontent.com/10053421/153818377-0b0b80ec-d2f0-4fc0-b75e-1090982047be.png)
![image](https://user-images.githubusercontent.com/10053421/153819312-c6686a7d-25e3-4c28-b699-874b01bfd03c.png)
![image](https://user-images.githubusercontent.com/10053421/153819754-d3815d34-d5ca-429b-b5a3-49e03ecbce63.png)
![image](https://user-images.githubusercontent.com/10053421/153820014-7066f1a5-a507-4c63-b756-e9e4cdaf46e7.png)

**Comment by jokoho48** [comment]
Fixed in Build 453.
