### ISSUE TITLE
Not IKEA: NPC standing on wall

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#856]
### Build number

350

### Bug description

NPCs occasionally appear standing on top of this corner wall in the Not IKEA building.

### Steps to reproduce the bug

It's intermittent, so you might need to leave and re-enter a couple of times to reproduce. Seems to occur when loads of NPCs spawn in the store at once.

### Savegame file

[sameron2.txt](https://github.com/hovgaardgames/bigambitions/files/8060029/sameron2.txt)

### Screenshots or videos

![20220214184617_1](https://user-images.githubusercontent.com/99119499/153850121-9c5544b9-1090-4828-bff2-d238fd3a7641.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 863.
