### ISSUE TITLE
Marketing Agency: dialogue box labeled Recruitment Agent

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#857]
### Build number

350

### Bug description

In the Marketing Agency building, the NPC you interact with to start a marketing campaign has a dialogue box labelled "Recruitment Agent".

### Savegame file

[sameron2.txt](https://github.com/hovgaardgames/bigambitions/files/8060051/sameron2.txt)

### Screenshots or videos

<img width="813" alt="marketingagency" src="https://user-images.githubusercontent.com/99119499/153850722-0f4ffbf1-161a-4e0c-991d-6dda0af5e37e.png">

**Comment by David-Goru** [comment]
Fixed in build 468
