### ISSUE TITLE
Auto-spawned clothing racks can't be removed from liquor store

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#859]
### Build number

350

### Bug description

I can't close the business
there was a liquor store, and then there were items of clothing in the liquor store. I have removed the shelves with cigars and wine, but I cannot remove the cabinets with clothes, if I start moving clothes (which appeared by itself in the store), any action with items will stop working for me. If I leave the store while moving, then I won't go anywhere else.

### Savegame file

[голд9 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8072524/9.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/154094502-faf2eee4-2bc6-4e07-8b55-9217dccf6fdc.png)

**Comment by David-Goru** [comment]
Fixed in build 479
