### ISSUE TITLE
Stuck in bench with hand truck

### ISSUE THREAD

**Issue by aurios05** [hovgaardgames/bigambitions#862]
### Build number

alpha 9 build 350

### Bug description

I got Stuck on a time bench with a hand truck full of merchandise, and could not get free no matter what I did,

### Steps to reproduce the bug

 I was coming out of the appliance store took a left, and got sucked onto the bench, and could not get free no matter what I did,

**Comment by aurios05** [comment]
I saved the five and exited to the main menu and when I got back into the game and I was free!

**Comment by jokoho48** [comment]
Fixed in Build 470
