### ISSUE TITLE
Save game overwrite confirmation dialog appearing when saving with new name

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#864]
### Build number

469

### Bug description

The overwrite confirmation dialog box appears 100% of the time, even when using a new save name. Appears to be the same as bug #609

### Steps to reproduce the bug

- Save the game with any save name that hasn't already been used

### Savegame file

[sameronalpha10.txt](https://github.com/hovgaardgames/bigambitions/files/8140287/sameronalpha10.txt)

### Screenshots or videos

![20220225230413_1](https://user-images.githubusercontent.com/99119499/155696980-0f33b698-9df9-4a8b-8890-c2b8f73fb734.jpg)

**Comment by David-Goru** [comment]
Fixed in build 476
