### ISSUE TITLE
Bug: Paperbag turns into Closed Cardboard

### ISSUE THREAD

**Issue by Cut3st** [hovgaardgames/bigambitions#865]
### Build number

350

### Bug description

Paperbag turns into Closed Cardboard

I also somehow duplicated the closed cardboard box before but not shown in the saved game as I load up a previous save to replicate the paper bag bug.

### Steps to reproduce the bug

When I empty my cash register paper bags and press pack, gives me closed cardboard box

### Savegame file

[Paperbag Bug.txt](https://github.com/hovgaardgames/bigambitions/files/8140409/Paperbag.Bug.txt)

**Comment by jhovgaard** [comment]
Dev info: Pack button should only be visible if it's not already a cardboard box.

**Comment by jokoho48** [comment]
Fixed in Build 484.
