### ISSUE TITLE
Most NPCs can't be interviewed

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#866]
### Build number

469

### Bug description

Most NPCs in the street don't have the dialog box with their age etc when you hover over them, which means they can't be interviewed. I've found that I can find one or two people are interviewable immediately after loading the save, but after that they all have no dialog box and aren't selectable, and I have to reload the save again

Appears to be the same to #284 

### Steps to reproduce the bug

Try to interview some NPCs :)

### Savegame file

[sameronalpha10.txt](https://github.com/hovgaardgames/bigambitions/files/8140552/sameronalpha10.txt)

### Screenshots or videos

Couldn't get the video file under 10MB but it's [here](https://drive.google.com/file/d/103jwOt0isdmQhgiyMgM6H45S1NEeTGNh/view?usp=sharing) if you want it

**Comment by Gerwanese** [comment]
https://user-images.githubusercontent.com/17579552/155806703-353e11dd-2ee2-470f-baa9-aa5e312597d5.mp4

**Comment by jhovgaard** [comment]
Fixed in build 471
