### ISSUE TITLE
able to enter blocked off areas (internal testing)

### ISSUE THREAD

**Issue by rsdworker** [hovgaardgames/bigambitions#867]
### Build number

469

### Bug description

the bug is very easy to reproduce - go to any edges where empty map - example this is l;ocated at 4th avenue

what i was expected - the junctions would block on one side preventing to enter vacant areas

### Steps to reproduce the bug

go to any road that is bordering the vacant areas (example western end of 4th avenue 
you see no blockers at junctions and you freely walk around beyond that

### Screenshots or videos

![image](https://user-images.githubusercontent.com/6688223/155708087-9a3e82c2-7a90-4c55-ae37-1cf6140dd318.png)

**Comment by David-Goru** [comment]
Fixed in build 478
