### ISSUE TITLE
Voogle Maps: labels missing on selected building in map filter

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#868]
### Build number

469

### Bug description

Buildings toggled in the map filter no longer show the circular label above them in map view like previous builds, making it particularly difficult to identify buildings that share a similar highlight colour when selected in the filter

### Steps to reproduce the bug

- Open Voogle Maps
- Select any building types in the map filter (particularly retail buildings for rent and fast food restaurants)

### Savegame file

[sameronalpha10.txt](https://github.com/hovgaardgames/bigambitions/files/8140782/sameronalpha10.txt)

### Screenshots or videos

![20220226002255_1](https://user-images.githubusercontent.com/99119499/155708493-7b8623d0-350a-4646-bdfa-9c78e5fe378e.jpg)

**Comment by rsdworker** [comment]
i had same issue

**Comment by jokoho48** [comment]
Fixed in Build 470.
