### ISSUE TITLE
cargo showning wrong postions

### ISSUE THREAD

**Issue by rsdworker** [hovgaardgames/bigambitions#870]
### Build number

469

### Bug description

when you load on forklift inside the warehouse you will find cargo isnt on pallet on forklift the cargo shows on different location but forklift cargo still carried

### Screenshots or videos

![image](https://user-images.githubusercontent.com/6688223/155739333-d57cabe0-eae8-4c51-9388-1ffc66c6f258.png)

**Comment by jokoho48** [comment]
I can't reproduce and due to a missing SaveGame, I can't test that, but I suspect a broken SaveGame
