### ISSUE TITLE
if you get off here, then later you won't get in the car and enter the building

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#872]
### Build number

469

### Bug description

if you get off here, then later you won't get in the car and enter the building. You need to expand the entrance area to the building. This is because the character comes out on the right

### Savegame file

[Uploading New Ckeptikya Save Game [MConverter.eu].txt…]()

### Screenshots or videos

![fda2ab51-18d1-4e18-9754-0fa0dcb757d7](https://user-images.githubusercontent.com/98607052/155786704-e4dedd13-aacd-4ac7-a2a3-e787c5df42d8.png)
![83d2ed4e-a341-482d-a689-a731ab9c3aa9](https://user-images.githubusercontent.com/98607052/155786722-4b79081d-70c1-4e2b-8498-6c9fbc018ad3.png)
![image](https://user-images.githubusercontent.com/98607052/155787035-d31a8c94-f6f0-49d6-8717-970f4499f1ba.png)

**Comment by jokoho48** [comment]
Fixed in Build 485.
