### ISSUE TITLE
F5 and F6 working when phone app is open

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#874]
### Build number

469

### Bug description

When a phone app is open, you can still press F1 to hide controls (leaving just the blurry background) and F2 to free the camera (also you can't really move away from your sport, just move it on the spot).
Both should be deactivated while phone apps are open.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155805744-cc0469dd-f535-4798-abba-efc48cf95a58.mp4

**Comment by David-Goru** [comment]
Fixed in build 482
