### ISSUE TITLE
Phone apps show "HELP [F1]" while F1 toggles display of control elements

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#875]
### Build number

469

### Bug description

Inside the phone apps at the bottom left, there's a label "HELP [F1]". F1 however still just toggles the display of control elements, the planned change of key bindings obviously hasn't happened yet.

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/155805972-9f51a64a-474a-4e63-98f4-faa07c9fce93.png)

**Comment by David-Goru** [comment]
Fixed in build 476
