### ISSUE TITLE
No feedback when saving with CTRL+S, but player moving and flickering

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#877]
### Build number

469

### Bug description

When using CTRL+S for saving, I don't get any feedback that the game was saved and with which name. This should pop up (ideally just like the red "no employee at cash register" messages, at the top right).
Additionally, CTRL+S causes the player to move (just like pressing S without CTRL), and for a short moment the view flickers.

### Savegame file

[New Don Calzone Save Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145179/New.Don.Calzone.Save.Game.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155811185-2427d530-48ac-43a1-80d0-e802d9f4d879.mp4

**Comment by David-Goru** [comment]
Fixed in build 482
