### ISSUE TITLE
Recruitment Agency: Dragging to reduce days to deliver almost impossible

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#878]
### Build number

469

### Bug description

When trying to reduce "days to deliver", it's almost impossible to do so through dragging, as it drags the dialog up/down instead.
The bug only occurs with the preselected 5 days. If I click to set it to another day, dragging will work fine. If I set it back to 5, the bug occurs again.

As a side note, the "days to deliver" chooser is slightly shorter than the "amount of candidates" chooser.

### Savegame file

[B469-DragQueen.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145248/B469-DragQueen.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155812652-d31d43db-812d-4d35-a0da-903a7ea8ded0.mp4

**Comment by David-Goru** [comment]
Fixed in build 479

**Comment by Gerwanese** [comment]
Not fixed in build 488 unfortunately, still the same issue.

**Comment by David-Goru** [comment]
Fixed in build 490
