### ISSUE TITLE
Bank at 6 2nd Avenue + Harbor import businesses available for rent

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#879]
### Build number

469

### Bug description

The Vantander Bank at 6 2nd Avenue shows "Available for rent" and I can get it for a cheap $448 / day.
Also both harbor import businesses are available for rent, although for a much higher price.

### Savegame file

[B469-RentABank.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145286/B469-RentABank.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/155813782-40cc3b32-0f30-43ff-8922-86db97ed7188.png)

![grafik](https://user-images.githubusercontent.com/17579552/155814573-09cc0bb2-0d0f-42e9-9c91-85cb39faede2.png)

![grafik](https://user-images.githubusercontent.com/17579552/155814600-cf7dceeb-017b-441a-8280-cfe541ce3e50.png)

**Comment by samer0n** [comment]
@Gerwanese It's also possible to rent the El Gato Foods building in build 475
![20220301223720_1](https://user-images.githubusercontent.com/99119499/156144055-ee712973-02e3-45d4-adb8-5c93d3a3da4d.jpg)

**Comment by David-Goru** [comment]
Fixed in build 476

Save games started before build 476 will still have those businesses for rent
