### ISSUE TITLE
Building info overlay position gets inverted on Voogle Maps when moving far away

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#880]
### Build number

469

### Bug description

Usually, when dragging Voogle Maps with a building overlay showing, once the building is outside the view the overlay will stay yat the position closest to the building.
If you move far away however (in my case into Hell's Kitchen for the truck dealer), suddenly this is inverted and the overlay will find the position furthest away from the building.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155814292-e20c5710-58fb-436b-b2e0-e7224131d060.mp4

**Comment by jokoho48** [comment]
Fixed in Build 475
