### ISSUE TITLE
Logo designer: Selected icon lost after save/reload

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#881]
### Build number

469

### Bug description

If you select a logo for your business, then save and reload the game, the choosen icon will be reset to "?". Colors however are kept.

### Savegame file

[B469-GiftysLogo.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145320/B469-GiftysLogo.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155815022-a098df7f-fda5-451e-b0e8-9ea8c02d83bc.mp4

**Comment by jokoho48** [comment]
Fixed in build 473.
