### ISSUE TITLE
Customize Logo: "Select from disk" not working

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#882]
### Build number

469

### Bug description

In BizMan settings, clicking on "Select from disk" in the "Customize Logo" section doesn't do anything.

### Savegame file

[B469-GiftysLogo.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145334/B469-GiftysLogo.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/155815275-980745b8-a6f5-4806-9464-9d31dce7a09b.png)

**Comment by jokoho48** [comment]
Fixed in Build 470
