### ISSUE TITLE
Supermarket in your contacts with "Call" button after you didn't show up for work

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#883]
### Build number

469

### Bug description

If you didn't show up for work, the supermarket will appear in your "Contacts" app, having a "Call" button. 
Clicking the button outside the business hours shows the usual message, but clicking during business hours shows a message "Calling Supermarket is not yet implemented."
Instead, the "Call" button should not show up at all in this case (it's weird anyways that you only get the contact after not showing up, but not after taking the job already).

### Savegame file

[B469-BetterCallJose.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145360/B469-BetterCallJose.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/155815566-4b3a1b4d-c8bc-4059-bb41-4da764871fbe.png)

**Comment by David-Goru** [comment]
Fixed in build 479
