### ISSUE TITLE
Car sound doesn't update inside drive-in wholesales

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#884]
### Build number

469

### Bug description

When entering the drive-in wholesales by car, the sound will not change. Instead you permanently hear the noise of the engine as it was right before entering.

### Savegame file

[B469-QuietCar.json.txt](https://github.com/hovgaardgames/bigambitions/files/8145411/B469-QuietCar.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155817199-854ddc89-5490-4d85-b2b6-f3a22890b04e.mp4

**Comment by jhovgaard** [comment]
Fixed in Build 603
