### ISSUE TITLE
Handtruck falls on the ground when taken out of vehicle

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#885]
### Build number

470

### Bug description

When taking a handtruck out of a vehicle it spawns fallen over on the ground in front of the player as opposed to in the player's hands

### Steps to reproduce the bug

- Store a handtruck in a vehicle
- While on foot click Manage Cargo on that vehicle
- Click the handtruck

### Savegame file

[Uploading sameronalpha10.txt…]()

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155827145-35de6730-7a83-4725-992a-589b1ab4779e.mp4

**Comment by jhovgaard** [comment]
Fixed in build 473
