### ISSUE TITLE
Incorrect error message when attempting to pick up a box with hands full

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#886]
### Build number

470

### Bug description

In the wholesale store, when the player's hands are full and they attempt to pick up another box of items, an error message saying "you need a shopping baskets to grab this product" is displayed. It should be a "Your hands are full" or "You need a hand truck to pick up this product" error

### Steps to reproduce the bug

- Go to NY Distro Inc wholesale store
- Pick up a box of any item so your hands are now full
- Attempt to pick up another box of any item

### Savegame file

[Uploading sameronalpha10.txt…]()

### Screenshots or videos

![20220226164257_1](https://user-images.githubusercontent.com/99119499/155827744-a942db62-d0ea-4d06-a501-f28d7ec44a93.jpg)

**Comment by samer0n** [comment]
This might have been build 471, it was 470 when I started playing but changed to 471 at some point without me noticing 😂

**Comment by jhovgaard** [comment]
Fixed in build 473
