### ISSUE TITLE
Cleaning: Dirt is invisible and mop has no effect on cleanliness bar

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#888]
### Build number

471

### Bug description

Cleaning seems to be broken, all my businesses have cleaners assigned but the cleanliness bar has steadily gone down in all of them. Visiting a business, there appears to be no visible dirt on the floor and using the mop to clean random pieces of the floor where dirt would normally appear has no effect on the cleanliness bar

### Savegame file

[Uploading sameronalpha10.txt…]()

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155830380-90d01017-5b90-473e-ab04-7a2c62242b79.mp4

**Comment by samer0n** [comment]
Started a fresh save and confirmed it is impossible to progress past the mop/cleaning goal
![20220226222451_1](https://user-images.githubusercontent.com/99119499/155837857-2a2b839a-dc7d-46a9-a507-48a365ae6d6d.jpg)

**Comment by jhovgaard** [comment]
Fixed in build 473
