### ISSUE TITLE
Warehouse at 76 FirstStreet has IKEA interior

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#889]
### Build number

471

### Bug description

If you rent and enter the warehouse building at 76 FirstStreet it has the interior of the IKEA building

It's also free to rent and has no building data as noted in #824 

### Steps to reproduce the bug

- Rent the warehouse building at 76 FirstStreet
- Enter the warehouse

### Savegame file

[sameronalpha1076firststreet.txt](https://github.com/hovgaardgames/bigambitions/files/8146008/sameronalpha1076firststreet.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155831504-d705d322-1986-409a-8811-3b532df109e8.mp4

**Comment by jhovgaard** [comment]
Changed to A2 office building.

Fixed in build 473

**Comment by samer0n** [comment]
@jhovgaard are you sure A2 is an office building type? I just went and had a look and it looks the same as one of the retail building types e.g. 31 ThirdStreet is also A2, but it's a retail building
![20220228180554_1](https://user-images.githubusercontent.com/99119499/155927208-e5c2cd8a-800b-4d7c-940e-19ebe89e4a82.jpg)
