### ISSUE TITLE
dirty and needs to be cleaned

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#892]
### Build number

471

### Bug description

"XIII Fast" dirty and needs to be cleaned . I clean the floor, it's still 0% clean

### Savegame file

[Uploading 7 [MConverter.eu].txt…]()

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155834781-3f32028e-ef3f-431c-8cd3-106b369920e0.png)

**Comment by jhovgaard** [comment]
Fixed in build 473
