### ISSUE TITLE
the car flies up after exiting

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#893]
### Build number

471

### Bug description

the car jumps after leaving the warehouse . The truck will get stuck there, between two pillars. It is necessary to remove the parking at the entrance to the warehouses

### Steps to reproduce the bug

go in reverse

### Savegame file

[7 [MConverter.eu] (1).txt](https://github.com/hovgaardgames/bigambitions/files/8146145/7.MConverter.eu.1.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155835141-7535cdf5-0865-4d78-9c40-c320c7ac62f0.png)
![image](https://user-images.githubusercontent.com/98607052/155836006-3efb2569-4b81-4c87-b406-d511a7739cd0.png)

**Comment by jhovgaard** [comment]
Fixed in build 475
