### ISSUE TITLE
I can't leave the warehouse

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#894]
### Build number

471

### Bug description

1 save : I can't leave the warehouse without my truck - I end up in textures
2 save : I can't go through the door if the truck is there.

### Steps to reproduce the bug

if you leave the truck and try to get out, you will end up in textures

### Savegame file

[9 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8146174/9.MConverter.eu.txt)
[10 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8146470/10.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155835852-54d93a29-214c-47f7-82f4-bfd50c115901.png)
![Uploading image.png…]()

**Comment by jhovgaard** [comment]
Fixed in build 472
