### ISSUE TITLE
No staff visible in MyEmployees

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#895]
### Build number

471

### Bug description

All my staff have vanished from the MyEmployees list. They were there before and I'm unsure what I was doing at the time they vanished as I don't look at that screen very often. Saving + reloading the game doesn't bring them back.

BizMan appears unaffected, employees are still there associated with their roles/shifts etc.

### Savegame file

[sameronalpha10lostmyemployees.txt](https://github.com/hovgaardgames/bigambitions/files/8146271/sameronalpha10lostmyemployees.txt)

### Screenshots or videos

![20220226215823_1](https://user-images.githubusercontent.com/99119499/155837240-ed25ed57-f5c0-4357-a1cb-06b2f06a4ec8.jpg)
![20220226215832_1](https://user-images.githubusercontent.com/99119499/155837242-4ee4bc57-66be-495c-9272-2922c249d6e5.jpg)

**Comment by jhovgaard** [comment]
Fixed in build 471
