### ISSUE TITLE
MyEmployees: Cleaners showing 0 working hours

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#896]
### Build number

471

### Bug description

Cleaners remain on 0 hours/week in MyEmployee even when assigned to cleaning roles in a business

### Steps to reproduce the bug

- Hire and assign a cleaner to any mop role in a business

### Savegame file

[sameronalpha10V2 0hourcleaner.txt](https://github.com/hovgaardgames/bigambitions/files/8146338/sameronalpha10V2.0hourcleaner.txt)

### Screenshots or videos

![20220226224807_1](https://user-images.githubusercontent.com/99119499/155838615-a2174c55-6915-4ab0-90a3-3b39a910bf4f.jpg)
![20220226224816_1](https://user-images.githubusercontent.com/99119499/155838618-6526395e-1a21-44d8-b5a8-4c3ab9f98e62.jpg)

**Comment by jhovgaard** [comment]
Fixed in build 472
