### ISSUE TITLE
Logo Customizer: Selecting logo icon for one business applies it to all businesses

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#898]
### Build number

471

### Bug description

In the Logo Customizer in BizMan, selecting an icon as your logo for a business applies that icon to all your businesses, overwriting their previously saved logos.

Fonts/colours appear to be retained, it just affects the icon

### Steps to reproduce the bug

- Have more than 1 business
- Access BizMan
- Click any business and go to the Logo Customizer in the Settings tab
- Pick any Logo Shape from the options
- Go back to BizMan and choose **another** business and go to its Logo Customizer, where the icon you just chose will appear

### Savegame file

[sameronalpha10V2 logosavebug.txt](https://github.com/hovgaardgames/bigambitions/files/8146415/sameronalpha10V2.logosavebug.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155840335-52876ae0-6b3b-43cf-8d1e-ca30cf135022.mp4

**Comment by jhovgaard** [comment]
Fixed in build 473
