### ISSUE TITLE
Delivery to the wrong place

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#899]
### Build number

472

### Bug description

Warehouse truck delivers pizza, salads and more to the gift store and vice versa to the fast food store

### Savegame file

[14 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8146715/14.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155845403-cfebf090-c182-4aa8-ac0c-a780b2856fb4.png)

**Comment by David-Goru** [comment]
Fixed in build 476

Will require you to remove and add again the destinations of the LogisticsManagers to fix it in your save
