### ISSUE TITLE
no expensive jewelry in the delivery contract (at the port)

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#900]
### Build number

472

### Bug description

 Why is there no expensive jewelry in the delivery contract (at the port)? and the logistics managers have it?

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155846219-54b766a3-d9bb-41ca-aa2b-2ce3d4be5c27.png)
![image](https://user-images.githubusercontent.com/98607052/155846224-a5f8c642-c041-4c4c-9690-5c3d02751589.png)

**Comment by jhovgaard** [comment]
Fixed in build 473
