### ISSUE TITLE
Opening map while driving (and pressing arrow key) will result in not zooming out

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#901]
### Build number

473

### Bug description

If you press M to open the map while holding an arrow key down (because you're driving), the map controls and street name overlays will open, but the camera will not zoom out for the map view.

### Savegame file

[B473-YouDriveMeMap.json.txt](https://github.com/hovgaardgames/bigambitions/files/8147268/B473-YouDriveMeMap.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/155855390-ab8d42f3-fb44-444e-aec4-c23b42c0435d.mp4

**Comment by jokoho48** [comment]
Fixed in some Earlier Build
