### ISSUE TITLE
Interior Designer: Wall/floor choices apply to unrented buildings of the same type

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#902]
### Build number

473

### Bug description

Applying wall or floor designs in Interior Designer applies those designs to all other **not-yet-rented** buildings of the same type (e.g. C2 as shown in video below). Already rented buildings of the same type are not affected by interior design changes in other buildings.

### Steps to reproduce the bug

- Rent a building and use interior designer to make any change to the walls or floor
- Rent **another building of the same type** and you'll find the same wall/floor changes already applied

### Savegame file

[sameron_473_interior_designer_bug.txt](https://github.com/hovgaardgames/bigambitions/files/8147994/sameron_473_interior_designer_bug.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155867455-d287b530-7c6d-420c-a02d-7e2c5604fb6b.mp4

**Comment by jokoho48** [comment]
Fixed in build 476
