### ISSUE TITLE
Possible to sleep in vehicle while inside wholesale store

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#903]
### Build number

473

### Bug description

It's possible to sleep in your vehicle after driving into the wholesale store. You can skip time to when the store is closed and still be inside and complete purchases.

### Steps to reproduce the bug

- Drive into NY Distro Inc wholesale store and sleep

### Savegame file

[sameron_473_sleep_in_store.txt](https://github.com/hovgaardgames/bigambitions/files/8148017/sameron_473_sleep_in_store.txt)

### Screenshots or videos

![20220227170158_1](https://user-images.githubusercontent.com/99119499/155867780-023c73e1-6721-4735-a47b-7f9eb6cd9afd.jpg)

**Comment by jhovgaard** [comment]
Let's fix this by simply showing a notification error saying "You can only sleep in your car when not inside of a building"
