### ISSUE TITLE
Warehouses require Cash Register/Checkout Counter and StackOfShoppingBaskets

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#906]
### Build number

473

### Bug description

In BizMan, "Cash Register or Checkout Counter" and "StackOfShoppingBaskets" are listed as requirements for warehouse buildings.

### Savegame file

[sameron_473_warehouse_requirements.txt](https://github.com/hovgaardgames/bigambitions/files/8148135/sameron_473_warehouse_requirements.txt)

### Screenshots or videos

![20220227185947_1](https://user-images.githubusercontent.com/99119499/155870386-73febcf2-e3f5-4057-93f7-53dfe5f9fcc4.jpg)

**Comment by jokoho48** [comment]
Fixed in Build 475. (Savegame will stay broken in this case)
