### ISSUE TITLE
Possible to configure Logistics Manager without being assigned to desk

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#907]
### Build number

473

### Bug description

If you have a Logistics Manager and Purchasing Agent assigned to a Headquarters, but not seated at a workstation, it is possible to configure the Logistics Manager's settings in BizMan, but not the Purchasing Agent's. The Purchasing Agent's settings only become available once they're seated at a workstation, but the Logistics Manager's settings are available whether they're seated or not.

### Steps to reproduce the bug

- Rent a Headquarters
- Hire a Logistics Manager and Purchasing Agent, assigning both to that Headquarters but **not** assigning them to a desk
- Access Logistics Managers tab to access settings

### Savegame file

[sameron_473_HQ_staff_settings_bug.txt](https://github.com/hovgaardgames/bigambitions/files/8148147/sameron_473_HQ_staff_settings_bug.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155870695-60ddb4ce-0033-41a1-8933-0023cd6fbb31.mp4

**Comment by David-Goru** [comment]
Fixed in buld 476
