### ISSUE TITLE
Logistics Managers: Open In BizMan button broken

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#908]
### Build number

473

### Bug description

The "Open In BizMan" button that can be found in the Logistics Managers tab in a Headquarters building is broken.

It looks like the intention is to take the player to the warehouse the logistics manager is responsible for in BizMan, because the address in the top left-hand corner changes, but nothing else happens.

### Steps to reproduce the bug

- Have a headquarters and warehouse with a Logistics Manager assigned
- Access your headquarters in BizMan
- Click the Logistics Managers tab
- Click your Logistics Manager
- Click Open In BizMan button

### Savegame file

[sameron_473_bizman_button.txt](https://github.com/hovgaardgames/bigambitions/files/8148327/sameron_473_bizman_button.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155874588-4c1cb291-2181-4556-8df3-8d9c7ffb3a80.mp4

**Comment by jhovgaard** [comment]
Fixed in build 474
