### ISSUE TITLE
Traffic jam at 1st Street / 3rd Avenue

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#909]
### Build number

473

### Bug description

On this street and at this intersection there is a constant traffic jam, cars crash into each other and can not pass each other, most often because of the trucks

### Savegame file

[16 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148413/16.MConverter.eu.txt)

### Screenshots or videos
![Безымянный](https://user-images.githubusercontent.com/98607052/155876809-03b99943-46c9-4b3f-b9b0-8cf091e026b7.png)
![image](https://user-images.githubusercontent.com/98607052/155876699-927049ce-0b97-4e20-8c56-8e8dafd18c5b.png)
![image](https://user-images.githubusercontent.com/98607052/155876702-6781a5f1-ec2d-456c-8c58-678b9d4d3075.png)
![image](https://user-images.githubusercontent.com/98607052/155876714-e48b8bf9-1ca8-4632-860a-c521b725c0c9.png)

**Comment by jhovgaard** [comment]
Improved a bit in 473, but still needs more work.

**Comment by jhovgaard** [comment]
Should be good now.

Fixed in build 482
