### ISSUE TITLE
Tree in building / Tree doesnt hide with building

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#910]
### Build number

473

### Bug description

At 34 Second Street, there is a tree in the front of the building, either it's not supposed to be there or if it is, the tree should hide along with the building when you walk past.

### Savegame file

[Tree.txt](https://github.com/hovgaardgames/bigambitions/files/8148549/Tree.txt)

### Screenshots or videos

![Big_Ambitions_HDMliIcMqH](https://user-images.githubusercontent.com/44293115/155880409-2a47016a-8aff-4a26-8a6a-f3b9763287c5.jpg)

**Comment by jhovgaard** [comment]
Fixed in build 473
