### ISSUE TITLE
Harbor entrance next to the subway station / 1st Street blocked

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#911]
### Build number

473

### Bug description

The character hits an invisible wall , in all passages of this wall

### Steps to reproduce the bug

go straight 

### Savegame file

[Uploading 17 [MConverter.eu].txt…]()

### Screenshots or videos

![Безымянный](https://user-images.githubusercontent.com/98607052/155882407-42a668d6-e4ce-43c0-a47a-95cd8be7fe97.png)
![Безымянный](https://user-images.githubusercontent.com/98607052/155882718-74f0a97a-ea38-4bfe-a78a-08f86f56ab6b.png)

**Comment by jhovgaard** [comment]
Fixed in build 475
