### ISSUE TITLE
Traffic jam for left turn from 6th Ave to 1st Street

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#912]
### Build number

473

### Bug description

cars go only in the left lane, the other lanes are rebuilt or just stand still, forming a traffic jam, cars that are standing soon disappear

### Savegame file

[18 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148681/18.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/155883694-beefc099-3fbe-4e77-b80e-b7fde072a874.png)

**Comment by jhovgaard** [comment]
Temporarily added despawn zone. 3D will work on better despawning experience (tunnel or similar).

**Comment by jhovgaard** [comment]
Fixed in Build 598
