### ISSUE TITLE
Walking path blocked at many points in front of 1st Broadway Street

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#913]
### Build number

473

### Bug description

1: There is no passage at these places.
2: There is sometimes a traffic jam at the intersection and cars cannot separate

### Savegame file

[19 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148725/19.MConverter.eu.txt)

### Screenshots or videos
![Безымянный](https://user-images.githubusercontent.com/98607052/155884667-0b0e369c-3517-4cd1-9777-a433414a1b03.png)

![image](https://user-images.githubusercontent.com/98607052/155884531-fee0945b-113e-4687-8343-61ffb393aa45.png)

**Comment by jhovgaard** [comment]
Fixed in build 475
