### ISSUE TITLE
Wrong time displayed on day change while sleeping in car

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#914]
### Build number

473

### Bug description

I was asleep in the car and noticed the time was wrong.

### Steps to reproduce the bug

fall asleep in the car

### Savegame file

[20 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148804/20.MConverter.eu.txt)

### Screenshots or videos
![Безымянный](https://user-images.githubusercontent.com/98607052/155886587-2c66230a-42dc-4fc4-b12d-74f62b279b70.png)

**Comment by David-Goru** [comment]
Fixed in build 476
