### ISSUE TITLE
Traffic jam at 2ND AVENUE  / 6TH Street

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#915]
### Build number

473

### Bug description

Cars get stuck under the bridge at this intersection. There is no traffic light, and cars do not understand who should go first, there is constant traffic jam, cars crash into each other 

### Savegame file

[22 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148874/22.MConverter.eu.txt)

### Screenshots or videos

![2](https://user-images.githubusercontent.com/98607052/155888170-5e9ed0d6-7c91-48a5-80e8-c1ad376e806c.png)
![3](https://user-images.githubusercontent.com/98607052/155888172-e4db6232-a65b-4d99-b4b1-edd193e254c8.png)
![Безымянный](https://user-images.githubusercontent.com/98607052/155888174-d3953f68-d87a-44e6-baff-c1699df71706.png)
![1](https://user-images.githubusercontent.com/98607052/155888177-723c4b7d-0755-488b-8acb-62e2626d0114.png)
![5](https://user-images.githubusercontent.com/98607052/155888194-71eaba42-7398-4f81-9941-e204ae356584.png)
![9](https://user-images.githubusercontent.com/98607052/155888223-9971c40b-66c4-4ab0-983e-24b6453ce6af.png)

![image](https://user-images.githubusercontent.com/98607052/155888455-34c78073-d55e-4b66-aae7-936b386ff7f2.png)

**Comment by Ckeptikya** [comment]
I also found a car stuck under the second bridge
![2](https://user-images.githubusercontent.com/98607052/156218133-fff30ebc-6408-4039-a085-267050e42a16.png)
![3](https://user-images.githubusercontent.com/98607052/156218438-9dfafdaf-cc3d-4936-9d0d-fe171c456608.png)

**Comment by jhovgaard** [comment]
This should now have been fixed.
