### ISSUE TITLE
Turning on the sidewalk at 2ND AVENUE / 6TH Street 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#916]
### Build number

473

### Bug description

Cars turn onto the sidewalk 

### Screenshots or videos

![9](https://user-images.githubusercontent.com/98607052/155888330-92c9c216-a14f-4748-9a39-2f570f612159.png)
![4](https://user-images.githubusercontent.com/98607052/155888353-6bb18067-ddfa-40b0-8d74-c011561b294d.png)
![8](https://user-images.githubusercontent.com/98607052/155888375-3e00c125-631d-4252-9bd8-6d2320ca7548.png)

**Comment by jhovgaard** [comment]
Awaiting implementation of Midtown neighborhood.

**Comment by jhovgaard** [comment]
Fixed in build 730
