### ISSUE TITLE
Unblocked First Avenue Street

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#917]
### Build number

473

### Bug description

I was able to get into the closed area because of the lack of a fence on First Avenue.

### Savegame file

[23 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8148985/23.MConverter.eu.txt)

### Screenshots or videos

![Безымянный](https://user-images.githubusercontent.com/98607052/155890077-db2a48cf-169f-41a8-852e-be3c4aa90636.png)
![2](https://user-images.githubusercontent.com/98607052/155890080-c67969e2-d73d-48bc-843f-3ebc0f9f32d5.png)
![image](https://user-images.githubusercontent.com/98607052/155890093-562c95b1-fe24-401c-9c1d-54261a9f07cf.png)
![image](https://user-images.githubusercontent.com/98607052/155890177-80fd6ae9-c4e5-41c4-8426-d9a0cfd2c846.png)

**Comment by jokoho48** [comment]
Fixed in build 476
