### ISSUE TITLE
Logistics Managers delivering without routes setup

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#919]
### Build number

474

### Bug description

The delivery menu at the logistics manager does not open,
Even if I don't have the logistics manager menu, it still delivers items to the store without it being set up, and I have no problems with empty shelves in the store. 

### Savegame file
[25 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8149171/25.MConverter.eu.txt)

### Screenshots or videos
![Безымянный](https://user-images.githubusercontent.com/98607052/155894275-313ae26b-587b-4f07-82e4-ba5c2084d159.png)

**Comment by Ckeptikya** [comment]
Even though I don't have a logistics manager menu, it delivered items to the store without setting it up.

**Comment by David-Goru** [comment]
Fixed in build 476
