### ISSUE TITLE
Can't terminate warehouse rental contract

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#920]
### Build number

474

### Bug description

I can not terminate the contract with the warehouse rental, the button "terminate contract" does not respond 

### Savegame file

[27 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8149200/27.MConverter.eu.txt)

### Screenshots or videos

![Безымянный](https://user-images.githubusercontent.com/98607052/155894695-df48d4f7-6825-4901-b6c1-3dac647e28b8.png)

**Comment by jhovgaard** [comment]
Fixed in build 476
