### ISSUE TITLE
no exit from the park

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#921]
### Build number

474

### Bug description

there is no exit from the park at these places

### Screenshots or videos

![Безымянный](https://user-images.githubusercontent.com/98607052/155895171-d454c557-5aab-4ce6-ac01-101d9a5ae9c1.png)
![Безымянный](https://user-images.githubusercontent.com/98607052/155895220-3a833c0d-a7ab-451d-9881-35f527a8447e.png)
![Безымянный](https://user-images.githubusercontent.com/98607052/155895241-9944fb8e-e690-4fca-8029-e2c25f25cca6.png)

**Comment by jhovgaard** [comment]
https://user-images.githubusercontent.com/1388347/156131021-0418218a-28c2-484e-a340-1c89fafd9ed7.mp4

@Ckeptikya I wasn't able to reproduce. Were you driving a vehicle?

**Comment by Ckeptikya** [comment]
No, I was on foot. After updating, I can't reproduce the problem either. @jhovgaard
