### ISSUE TITLE
Successful import delivery dialog refers to "weekly" shipment regardless of chosen delivery frequency

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#923]
### Build number

474

### Bug description

The dialog box that appears on screen when an import is successfully received by a warehouse reads "Your **weekly** shipment has arrived" regardless of the player's chosen delivery frequency (e.g. one-off order, every day, etc).

### Steps to reproduce the bug

- Have a headquarters and warehouse with a Logistics Manager assigned, and a partnership with an import business
- Place a one-off order for any amount of items with your Logistics Manager
- Advance time to the scheduled delivery time

### Savegame file

[sameron_473_import_deliver_dialog.txt](https://github.com/hovgaardgames/bigambitions/files/8150656/sameron_473_import_deliver_dialog.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155925432-d5cc81fc-06e9-4f0a-b582-f63a2260f1a9.mp4

**Comment by David-Goru** [comment]
Fixed in build 476
