### ISSUE TITLE
MyEmployees: DeliveryDriver has "no task"

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#924]
### Build number

474

### Bug description

DeliveryDrivers get a red "No task" label in the Task column in MyEmployees, even if they are assigned to a vehicle associated with a warehouse

### Savegame file

[sameron_474_driver_no_task.txt](https://github.com/hovgaardgames/bigambitions/files/8150702/sameron_474_driver_no_task.txt)

### Screenshots or videos

![20220228175248_1](https://user-images.githubusercontent.com/99119499/155926358-e3c3a334-ebc2-4aa0-b65b-74df2c115a30.jpg)
![20220228175257_1](https://user-images.githubusercontent.com/99119499/155926365-cb054d6c-fb0a-4d8c-8784-3fbd06f4ef74.jpg)

**Comment by David-Goru** [comment]
Fixed in build 476
