### ISSUE TITLE
Sign appearance editor available on buildings with no signs

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#925]
### Build number

474

### Bug description

There are some non-residential buildings that don't have a sign (where the business name appears), but the sign appearance editor is still available to use

The ones I found were mostly office buildings but I also found a couple of retail buildings, so there may be more out there

76 FirstStreet
58 SecondStreet
7 FifthAvenue
74 ThirdStreet
19 Fifth Avenue
9 FirstStreet
4 ThirdStreet
1 FirstAvenue
2 ThirdStreet

### Savegame file

[sameron_474_sign_editor.txt](https://github.com/hovgaardgames/bigambitions/files/8150828/sameron_474_sign_editor.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/155929826-3a9224cf-a083-4bb4-a528-657e3d6a5897.mp4

**Comment by jhovgaard** [comment]
Dev hint: We should only show the "Change Sign Appearance" if the BuildingType is Retail.

**Comment by jokoho48** [comment]
Fixed in Build 476.
