### ISSUE TITLE
Sleeping inside building doesnt show daily overview at midnight.

### ISSUE THREAD

**Issue by adameg2305** [hovgaardgames/bigambitions#927]
### Build number

474

### Bug description

While sleeping inside the truck inside NY Distro Inc, once midnight rolls around the profit overview doesn't play.

### Steps to reproduce the bug

Buy a truck
Go to NY Distro Inc
Sleep past midnight

**Comment by jokoho48** [comment]
with build 475 you cant sleep inside buildings you don't own 😄

**Comment by adameg2305** [comment]
> 

Push the build then Joko 😂

**Comment by jhovgaard** [comment]
Let's make sure it shows when sleeping inside of owned warehouses.

**Comment by jokoho48** [comment]
Fixed in Build 476.
