### ISSUE TITLE
Possible to walk through pallets in NY Distro Inc wholesale store

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#928]
### Build number

474

### Bug description

It's possible to walk through all the stacked pallets inside the NY Distro Inc wholesale store, including while holding a hand truck

It's not possible to drive through them with the forklift however

### Savegame file

[sameron_474_pallet_collision.txt](https://github.com/hovgaardgames/bigambitions/files/8158794/sameron_474_pallet_collision.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/156106732-a1fd772a-d146-4d10-921d-15bc2587a4c2.mp4

**Comment by jokoho48** [comment]
Fixed in build 476
