### ISSUE TITLE
Pizza oven next to industrial fryer placement

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#931]
### Build number

475

### Bug description

You can't place the pizza oven directly next to an industrial fryer, but if you place the pizza oven followed by the industrial fryer in the exact same tiles, it works fine

### Savegame file

[sameron_475_pizza_oven_fryer.txt](https://github.com/hovgaardgames/bigambitions/files/8160385/sameron_475_pizza_oven_fryer.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/156141951-f75ab13e-2e8d-40ab-858b-0eac62b237df.mp4

**Comment by jokoho48** [comment]
Fixed in build 476
