### ISSUE TITLE
I can't sit on the benches

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#932]
### Build number

476

### Bug description

I can't sit on the benches, I click on them to sit down, and the character runs away from them to the other side. Some benches he doesn't respond to at all.
### Steps to reproduce the bug

Try sitting on a park bench

### Savegame file

[28 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8162517/28.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156193961-4dbd779a-f87a-4427-8ede-986ef9c56edc.png)

**Comment by LPDMinecraft** [comment]
On my view its very random when he sits. Sometime I press nothing and he sit downs anyways and the I cant stand up...

**Comment by Gerwanese** [comment]
Fixed in build 478
