### ISSUE TITLE
18 1st Street - There should be a store here.

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#933]
### Build number

476

### Bug description

I rented an apartment, and I walk in and there's room for a store

### Savegame file

[30 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8162824/30.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156200133-f6b3b57e-fd85-43c0-be30-cacf6ada3eb0.png)
![image](https://user-images.githubusercontent.com/98607052/156200179-674ae70c-4e3b-47ba-b545-6921a652ba68.png)

**Comment by jhovgaard** [comment]
Fixed in build 482
