### ISSUE TITLE
Can't enter the building  10 Firstavenue 

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#934]
### Build number

476

### Bug description

It is impossible to enter the building. The character freezes at the entrance , then I press ESC and he enters the building , after that I could not reproduce this problem anymore 

### Savegame file

[31 [MConverter.eu].txt](https://github.com/hovgaardgames/bigambitions/files/8163105/31.MConverter.eu.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156205857-38b6aa04-7357-4dc2-b337-c1509fd7b88b.png)

**Comment by David-Goru** [comment]
Fixed in build 479
