### ISSUE TITLE
Traffic jam at 2ND STREET / FIRST AVENUE

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#935]
### Build number

476

### Bug description

accidents happen at this intersection

### Savegame file

[Uploading 31 [MConverter.eu].txt…]()

### Screenshots or videos

![Безымянный](https://user-images.githubusercontent.com/98607052/156211549-cd69c938-e387-47be-8d4a-6d6d54cd67d6.png)
![2](https://user-images.githubusercontent.com/98607052/156211614-9dca355c-dfeb-4a25-a0c6-eb44e9b3e615.png)

**Comment by jhovgaard** [comment]
Should work now.
Fixed in build 482
