### ISSUE TITLE
New messages do not scroll down automatically

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#936]
### Build number

476

### Bug description

During business hours, when I call NY Distro Inc, I get the message "Call from Wholesale Warehouse not yet implemented," but scrolling does not move the screen down to the last message

### Steps to reproduce the bug

Call NY Distro Inc and see where the last message was 

### Savegame file

[Uploading 31 [MConverter.eu].txt…]()

### Screenshots or videos

https://user-images.githubusercontent.com/98607052/156212326-a2313380-09be-4999-9e62-1b267865ccee.mp4

**Comment by Gerwanese** [comment]
Might be related to #801

**Comment by David-Goru** [comment]
Fixed in build 479
