### ISSUE TITLE
Stores don't work

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#939]
### Build number

476

### Bug description

No cashiers anywhere, can't take the goods or a handcart, no carts at IKA

### Savegame file

[Uploading 34 [MConverter.eu] (1).txt…]()

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156234420-151bf255-9184-454b-91e8-dae25dc01e5e.png)
![image](https://user-images.githubusercontent.com/98607052/156234521-3340218d-d3cf-497f-9288-ad4025013bb9.png)
![image](https://user-images.githubusercontent.com/98607052/156234625-b8aa9cac-1b52-4c8d-995e-90f607f38e72.png)

**Comment by jhovgaard** [comment]
Fixed in build 478
