### ISSUE TITLE
Can't enter bank after entering another shop

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#942]
### Build number

478

### Bug description

After starting a new game or loading an existing savegame, if you first enter any AI store (appliance store, supermarket) and then go to the bank, you can't enter it.
If you enter the bank right away, then everything is fine.
Also if you enter the bank first, then another store and then the bank again, everything is fine.
Saving and reloading fixes the issue.

[Player.log](https://github.com/hovgaardgames/bigambitions/files/8165282/Player.log)

### Steps to reproduce the bug

1. Load savegame
2. Walk into and out of supermarket
3. Try to enter the bank

### Savegame file

[B478-BankJob.json.txt](https://github.com/hovgaardgames/bigambitions/files/8165271/B478-BankJob.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/156262794-7785f89b-f440-41c3-8b0f-06a8fb611018.mp4

**Comment by DillanWhite** [comment]
Happened to me also at my first Gift Shop, Recruiter and some other buildings, after hitting CTRL + S, it instantly enters the building.

**Comment by David-Goru** [comment]
Fixed in build 479
