### ISSUE TITLE
Camera doesn´t follow car and gamesave is broken

### ISSUE THREAD

**Issue by DillanWhite** [hovgaardgames/bigambitions#943]
### Build number

478

### Bug description

- I got into my car and started driving, car moved, camera didnt. 
- I get out of my car: Character gets out, camera jumps to character but character is unable to move, Car UI is still there.
- I get back in the car : Character stays outside, car moveable.

- I started typing a feedback-report via ingame feature, started thinking of trying something else, closed the feedbackreport: Game UI gone, Car UI still there.

- I save the game and try to reload it: keeps loading (with spinning BA Logo, could be normal but didnt see this before as it barely takes time to load normally)

**Gamesave is bricked**

### Steps to reproduce the bug

I dont know, got into the car many times before without issues 

### Savegame file

[1. employee.txt](https://github.com/hovgaardgames/bigambitions/files/8165853/1.employee.txt)

### Screenshots or videos

Since the gamesave seems bricked i can only provide the low res thumbnail from the Gamesave Folder 
![1  employee](https://user-images.githubusercontent.com/100739136/156277451-f8452248-7722-4d59-b1ac-ca0a69ca749d.jpg)

**Comment by jokoho48** [comment]
Fixed in build 479
