### ISSUE TITLE
Voogle Maps: Uncle Fred objective icon not visible while indoors

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#944]
### Build number

478

### Bug description

The circular icon denoting the player's next objective from Uncle Fred (not the player-set waypoint) in Voogle Maps is only visible when the player is outdoors. If the player accesses Voogle Maps from inside a building, the objective bubble is not there

### Savegame file

[sameron_478_objective_icon.txt](https://github.com/hovgaardgames/bigambitions/files/8168469/sameron_478_objective_icon.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/156336671-15000c37-17c5-4e31-a270-fe2ad835f0cf.mp4

**Comment by jokoho48** [comment]
Fixed in Build 592.
