### ISSUE TITLE
Hologram trees

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#945]
### Build number

478

### Bug description

Similar to #928, the player character and NPCs can walk through the trees that are planted along the edge of some of the smaller streets (e.g. 3rd Street) 

### Savegame file

[sameron_478_hologram_trees.txt](https://github.com/hovgaardgames/bigambitions/files/8168592/sameron_478_hologram_trees.txt)

### Screenshots or videos

![20220302230048_1](https://user-images.githubusercontent.com/99119499/156339883-ca567ca7-9e83-4f90-a375-2398153d45c7.jpg)

https://user-images.githubusercontent.com/99119499/156340055-39515cb5-b963-4ea9-841c-4f3a02654d75.mp4

**Comment by jokoho48** [comment]
Fixed in build 479
