### ISSUE TITLE
Vehicle brake lights triggered when not braking

### ISSUE THREAD

**Issue by samer0n** [hovgaardgames/bigambitions#946]
### Build number

478

### Bug description

When driving with WASD, if you tap the brake just once while driving, your vehicle's brake lights come on and won't go off until you hit the accelerator again. Brake lights should only engage when the player is actively braking

### Steps to reproduce the bug

- Drive a vehicle (I spotted this in the cheap saloon), preferably in a shaded street during the day (it's easier to see)
- Build up speed, tap S once to brake and press no other buttons, your brake lights will stay on until you accelerate again

### Savegame file

[sameron_478_brake_lights.txt](https://github.com/hovgaardgames/bigambitions/files/8168645/sameron_478_brake_lights.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/99119499/156341357-ba481073-fc06-434e-9b22-993bfad40e47.mp4

**Comment by jhovgaard** [comment]
Devs: Shouldn't be fixed, as we'll switch to new car controller in Beta 1.

**Comment by jhovgaard** [comment]
Fixed in Build 603
