### ISSUE TITLE
Glitchy counter in metro wholesale

### ISSUE THREAD

**Issue by jhovgaard** [hovgaardgames/bigambitions#948]
### Build number

480

### Bug description

...

### Savegame file

[glitchy-counter.json.txt](https://github.com/hovgaardgames/bigambitions/files/8170136/glitchy-counter.json.txt)

### Screenshots or videos

![image](https://user-images.githubusercontent.com/1388347/156379835-18c917dc-693d-46cb-a9af-8627512ac799.png)

**Comment by jokoho48** [comment]
Can't Reproduce.
