### ISSUE TITLE
Something is blocking the passage

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#950]
### Build number

479

### Bug description

ran into an invisible wall, nothing seems to interfere, but I can not pass forward, in the end somehow passed.

### Steps to reproduce the bug

you need to rent a warehouse and drive the truck into the left lane

### Savegame file

[7 [MConverter.eu] (2).txt](https://github.com/hovgaardgames/bigambitions/files/8171173/7.MConverter.eu.2.txt)

### Screenshots or videos

https://www.youtube.com/watch?v=Q33_C_39K54

**Comment by jokoho48** [comment]
Fixed in Build 485
