### ISSUE TITLE
Can't terminate the contract with the building

### ISSUE THREAD

**Issue by Ckeptikya** [hovgaardgames/bigambitions#952]
### Build number

479

### Bug description

Can't terminate the contract with the building

### Savegame file

[Uploading 9 [MConverter.eu] (1).txt…]()

### Screenshots or videos

![image](https://user-images.githubusercontent.com/98607052/156598934-bf54d248-f423-4ab2-9280-6270aa8670a7.png)

**Comment by jhovgaard** [comment]
Did you ensure the building is empty? Both of items but also vehicles.

**Comment by Ckeptikya** [comment]
yes @jhovgaard

**Comment by Ckeptikya** [comment]
![image](https://user-images.githubusercontent.com/98607052/156734596-289f96ef-1530-4b3b-b367-e08b297862b0.png)

**Comment by Gerwanese** [comment]
Another savegame with the same issue:

[New Bojan Save Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8217803/New.Bojan.Save.Game.json.txt)

**Comment by jokoho48** [comment]
Fixed in Build 490. To Fix Savegames you need to Open the Console and Type in `TerminateContractFix` and than Confirm that you want to remove all the Items from the Store
