### ISSUE TITLE
Can't grab item again when cancelling discard

### ISSUE THREAD

**Issue by MarioMarietto** [hovgaardgames/bigambitions#954]
### Build number

482

### Bug description

After cancelling discard the item falls on the ground and I can't pick it up again

### Steps to reproduce the bug

Right click on an item
Click on Discard
Click on Cancel

### Savegame file

[CantGrabItem.txt](https://github.com/hovgaardgames/bigambitions/files/8179672/CantGrabItem.txt)

### Screenshots or videos

https://www.youtube.com/watch?v=KOPl8sBcVSc

**Comment by jokoho48** [comment]
Fixed in Build 484.
