### ISSUE TITLE
Typo in contacts app: "Hung up" instead of "Hang up"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#956]
### Build number

486

### Bug description

In the contact app, the button to end a call is labelled "Hung up", while "Hang up" would be correct.

### Savegame file

[B473-YouDriveMeMap.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193095/B473-YouDriveMeMap.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/156933965-3ee88120-5fee-47f1-89b6-29a311ee480c.png)

**Comment by David-Goru** [comment]
Fixed in build 490
