### ISSUE TITLE
Phone apps have white background for some users

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#957]
### Build number

486

### Bug description

Some users report white background in phone app:
https://community.bigambitionsgame.com/t/bizman-menu-ui/833

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/156934053-c0acf242-dd69-4a78-909e-a78ab6480659.png)

**Comment by Gerwanese** [comment]
Seems to be related to Intel GPUs

**Comment by jokoho48** [comment]
this probably needs direct Unity Support

**Comment by CodingLover69** [comment]
Any updates on this? My game is basically unplayable from this issue.

**Comment by David-Goru** [comment]
The error is related to Intel GPUs. We've added an option to toggle a static background for phone apps in the options (main menu). Fixed in build 732
