### ISSUE TITLE
Graphics issue when entering car while zoomed in

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#958]
### Build number

486

### Bug description

When entering the car while zoomed in (any zoom level that's not fully zoomed out), part of the screen will just be grey depending on how much you zoomed in before.

See also: https://community.bigambitionsgame.com/t/extreme-fog-while-driving/817

### Savegame file

[B473-YouDriveMeMap.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193107/B473-YouDriveMeMap.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/156934218-1de70a4d-5c1b-4069-9a8f-d44b53518d29.mp4

**Comment by jokoho48** [comment]
Fixed in Build 590. You cant Interact with items anymore when the game is paused
