### ISSUE TITLE
Customer capacity building limit too high for law firm

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#959]
### Build number

486

### Bug description

K1 building (10 Second Ave, 660m²) has a customer capacity of 660. While this might be correct for a supermarket, it's pretty misleading for a law firm (only companies possible in there are currently law firm and headquarters).

It would probably be a good idea to make the customer capacity not just depending on building size but also on business type.

See https://community.bigambitionsgame.com/t/incorrect-building-limit-for-office-business/832

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/156934854-13e45d30-00f6-4158-b240-873a2138a3e1.png)

**Comment by David-Goru** [comment]
Fixed in build 594
