### ISSUE TITLE
Second Avenue buildings with number >=10 got line wrap in BizMan

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#961]
### Build number

486

### Bug description

All buildings on Second Avenue with a number >= 10 got a line wrap in BizMan.

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/156935123-2751d791-79ce-4df2-9e26-0735673256e2.png)

**Comment by David-Goru** [comment]
Fixed in build 490
