### ISSUE TITLE
Can't grab fridge with items in it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#962]
### Build number

486

### Bug description

It's not possible to grab a fridge with items in it, but also not possible to empty the fridge. This makes moving to another apartment very difficult.

### Savegame file

[B486-MoveMyFridge.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193185/B486-MoveMyFridge.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/156935427-bb2760c0-c60d-4172-9f4d-94fcdedd1ef1.mp4

**Comment by jokoho48** [comment]
Fixed in Build 603
