### ISSUE TITLE
Closing business fulfills "$100 profit per business" objective

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#964]
### Build number

486

### Bug description

The objective to generate $100 daily revenue with all businesses can easily be fulfilled by just shutting down the new business and terminating its contract.

### Savegame file

[B486-CloseBusinessesToReachGoal.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193255/B486-CloseBusinessesToReachGoal.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/156936626-683dfd42-f424-45c8-8f6d-33dcadf639be.mp4

**Comment by David-Goru** [comment]
Fixed in build 490
