### ISSUE TITLE
Flipped cars are lost

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#966]
### Build number

486

### Bug description

We recently get frequent reports about flipped cars. They can't be moved back onto their wheels, so they're lost (savegame manipulation needed to fix them).

Couldn't reproduce it though.

As long as we don't have some kind of "towing business" to fix it, we need a solution for this.

### Savegame file

[New BigBIG Save Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193309/New.BigBIG.Save.Game.json.txt)

**Comment by jokoho48** [comment]
this should have been fixed with the new Car Controller @jhovgaard?

**Comment by jhovgaard** [comment]
Fixed in Build 603
