### ISSUE TITLE
WASD keys stuck after clicking "set destination" for El Gato job

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#967]
### Build number

486

### Bug description

After clicking "Set destination" for your own job, WASD controls are stuck. Some of the keys can still be used normally while others wouldn't work or just for a very short distance before being stuck again. Every time it's different which keys work and which don't.
Moving through clicking once fixes it.

Similar issue once already occurred when driving (arrow keys didn't work anymore), but for that I can't tell what triggered it.

### Savegame file

[Build486-Don'tYaMove!.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193318/Build486-Don.tYaMove.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/156938461-4d954473-bf49-4232-9d42-2e9de89fa5b8.mp4

**Comment by David-Goru** [comment]
Fixed in build 1142
