### ISSUE TITLE
Wrong numbers in warehouse inventory

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#968]
### Build number

486

### Bug description

Just let the game run for 7 days.
Deliveries of cheap gifts went from 1,080,000 to 1,440,000 - that’s plus 360,000.
The consumption of 5,185 doesn’t fit as well. The two gift shops just sold a bit more than 1,500 during the last 7 days.

See also https://community.bigambitionsgame.com/t/incorrect-stock-count-build-482/815/5

### Savegame file

[New Ampire Save Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193397/New.Ampire.Save.Game.json.txt)

### Screenshots or videos

At start;
![grafik](https://user-images.githubusercontent.com/17579552/156940089-d6fc7282-3151-407e-ba61-2d0bd21bb7a7.png)

After 7 days:
![grafik](https://user-images.githubusercontent.com/17579552/156940101-08358b79-4016-43b4-b88a-b350ea7ab30c.png)

**Comment by David-Goru** [comment]
Fixed in build 490
