### ISSUE TITLE
Can't load vehicles with forklift

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#969]
### Build number

486

### Bug description

Vehicles can't be loaded with forklifts.
Manual loading of single boxes works.

This doesn't just affect trucks, the van has the same issue.

### Savegame file

[B486-Truckload.json.txt](https://github.com/hovgaardgames/bigambitions/files/8193446/B486-Truckload.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/156940967-493494a8-ed1c-406a-960e-98d900938728.png)

**Comment by jokoho48** [comment]
Fixed in Build 488.
