### ISSUE TITLE
BizMan delivery on/off toggle without effect

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#971]
### Build number

488

### Bug description

In BizMan's "Deliveries" tab there's a toggle for each delivery to disable or enable it.
Delivery however will always be done, even if it is disabled.

### Savegame file

[Uploading New.Ampire.Save.Game.json.txt…]()

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/157526298-85129628-cf07-4f69-86e0-481517d1588b.mp4

**Comment by David-Goru** [comment]
Fixed in build 490
