### ISSUE TITLE
BizMan: Line wrap in Inventory & Pricing with big numbers

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#972]
### Build number

488

### Bug description

In the BizMan's Inventory & Pricing tab, the line showing gross profit margin for the "last period" will wrap if the number is too big.

### Savegame file

[New.Ampire.Save.Game.json.txt](https://github.com/hovgaardgames/bigambitions/files/8217854/New.Ampire.Save.Game.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/157527087-5566dc1f-0f41-414f-970b-8a62d9728f37.png)

**Comment by David-Goru** [comment]
Fixed in build 490
