### ISSUE TITLE
Main menu: When pressing a button, most of the savegame thumbnails will disappear

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#973]
### Build number

488

### Bug description

When you press a button in the main menu (like "start new game" or "exit game"), most of the savegame thumbnails will disappear.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/157528148-5c2d65e9-9b51-4cb7-a058-3de83945c2c9.mp4

**Comment by David-Goru** [comment]
Fixed in build 590
