### ISSUE TITLE
Illegally parked Merc in front of 22 Fourth Street blocking the road

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#974]
### Build number

488

### Bug description

In front of 22 Fourth Street there's a Merc parked on the road, facing the opposite traffic and blocking all cars going in the direction of Ika Bohag.

### Savegame file

[B488-Showdown.json.txt](https://github.com/hovgaardgames/bigambitions/files/8218383/B488-Showdown.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/157541706-2ef79abb-3bf2-49cb-b73a-9bd499d2f3d1.png)

**Comment by jokoho48** [comment]
Fixed in Build 591.
