### ISSUE TITLE
"Buy a box of soda cans" Objective not checked if fulfilled prematurely

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#975]
### Build number

490

### Bug description

If you buy soda cans already before the objective shows up, it will not be recognized as fulfilled.

How it should be: Automatically check it if any of your stores already has a drinks fridge with soda cans (for the last objective "Fill up the drinks fridge with soda cans", this already works correctly).

### Savegame file

[Build490-CanISodaPlease.json.txt](https://github.com/hovgaardgames/bigambitions/files/8237726/Build490-CanISodaPlease.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/158021132-f934311b-36b9-45f4-a6bd-91e7918b5094.png)

**Comment by David-Goru** [comment]
Fixed in build 589
