### ISSUE TITLE
Wrong hand truck spawning position in C2 (and probably other) buildings

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#976]
### Build number

490

### Bug description

In C2 buildings, the hand truck spawning position is inside the customer area of the shop. It should be inside the storage room (maybe just behind the door).
Please also check other building types, probably there are more with the same issue.

### Savegame file

[Build490-InsideSpawn.json.txt](https://github.com/hovgaardgames/bigambitions/files/8237739/Build490-InsideSpawn.json.txt)

**Comment by David-Goru** [comment]
Fixed in build 587
