### ISSUE TITLE
Hand truck spawns "inside" other item if placed on the spawning point

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#977]
### Build number

490

### Bug description

If you place any item right on the spawning point of a shop's hand truck, the hand truck will spawn "inside" this item. It's still possible to pick it up though.

This bug is related to #976, however even inside the storage room, the hand truck shouldn't spawn "inside" another item (for example a metal shelf).

Simple solution: If spawning point is blocked, find any other free spot in the shop.
More convenient solution: Let players move the spawning position to any free spot, which will then be "occupied" so you can't place anything else on it.

### Savegame file

[Build490-InsideSpawn.json.txt](https://github.com/hovgaardgames/bigambitions/files/8237743/Build490-InsideSpawn.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/158021453-4de98435-bcd1-45d8-ab10-11a49620578e.mp4

**Comment by David-Goru** [comment]
Fixed in beta 8
