### ISSUE TITLE
Wrong info when shutting down business

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#979]
### Build number

491

### Bug description

In the business settings, a text advises that shutting down the business would automatically sell existing inventory, although it's not done.

How it should be (accepted solution by Jonas):
- Remove the text, keep the current behaviour (nothing is sold when shutting down)
- Auto-sell all inventory when terminating the building contract, so people don't have to move everything out manually.

### Savegame file

[Build490-InsideSpawn.json.txt](https://github.com/hovgaardgames/bigambitions/files/8264867/Build490-InsideSpawn.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/158630116-3a526ea2-bd88-43d1-9721-20077bd4a1b6.png)

**Comment by David-Goru** [comment]
Fixed in build 587
