### ISSUE TITLE
Player keeps running into building wall after dragging over it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#98]
Build 49

When dragging over a building wall (holding down left mouse key, starting a bit in front of the building and releasing "behind" it) the player will keep running into the wall.
Happens more often in normal speed than in double speed, probably because the right timing is harder to match in double speed. I could create the effect in both speed settings though.

https://user-images.githubusercontent.com/17579552/120248174-6583d480-c276-11eb-9d0b-b3649073e7ee.mp4

**Comment by Gerwanese** [comment]
Build 51

Click at any point right in front of a building wall. Once the player gets there he will turn towards the building and endlessly run into it.
This might or might not be the same issue as the original report which requires dragging over a building, The original dragging issue could in theory be triggered by the point right in front of the building being the last "valid" position and then causing the same issue as this comment describes. I thus don't open a separate bug.


https://user-images.githubusercontent.com/17579552/120860401-eba95f00-c585-11eb-863f-6fd793ef1cb0.mp4

**Comment by David-Goru** [comment]
Fixed in the past
