### ISSUE TITLE
Car's cargo dialog stays open when moving using WASD

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#980]
### Build number

491

### Bug description

After opening the car's cargo dialog, you can move away and even enter a business without closing the dialog.
When clicking to move, it will immediately close.

How it should be:
When getting too far away from the car, the cargo dialog should automatically close.

### Savegame file

[Build490-InsideSpawn.json.txt](https://github.com/hovgaardgames/bigambitions/files/8264920/Build490-InsideSpawn.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/158631799-6960c1bd-9f0f-45b7-ab70-e1eacc22c9e1.mp4

**Comment by jokoho48** [comment]
Fixed in Build 591.
