### ISSUE TITLE
Camera sometimes off when leaving apartment

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#981]
### Build number

588

### Bug description

When leaving your apartment, sometimes the camera starts way off. In the video it happens at the end, the last time leaving the building.

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/158868833-e48a7ac2-e00c-4305-9062-80417a0f23b2.mp4

**Comment by jokoho48** [comment]
Fixed in Build 591.
