### ISSUE TITLE
Recruitement Agency via app can't Cancel or Confirm

### ISSUE THREAD

**Issue by Decimes** [hovgaardgames/bigambitions#983]
### Build number

492

### Bug description

When using my phone/app to recruit staff I call the Agency, during opening hours, they answer and ask the type of employee I want to hire. I check my Business, check the Skill, set the age groups I want, number of Candidates and Days to deliver. Then at the bottom are the options to either Cancel or Confirm but neither of these buttons work.

Tried every combination to no avail.

### Steps to reproduce the bug

No idea. Has not worked at all.

### Savegame file

[DMV-5.txt](https://github.com/hovgaardgames/bigambitions/files/8356193/DMV-5.txt)

**Comment by jhovgaard** [comment]
Fixed in build 493

**Comment by Decimes** [comment]
Thanks! And just to confirm, indeed it is working now.
