### ISSUE TITLE
Handcart in Main area not in Storageroom.

### ISSUE THREAD

**Issue by Decimes** [hovgaardgames/bigambitions#984]
### Build number

493

### Bug description

Minor 'bug', more just placement of handcart. I rented 10 Fourthavenue and the handcart is not in the storageroom but in the topleftcorner of the main area. I don't know for sure if this is on purpose, but thought the handcart is supposed to be in the storageroom.

### Steps to reproduce the bug

Think just rent it and it will be topleftcorner of the main area for everyone. If need be I can still attach savegame file, just let me know then.

**Comment by David-Goru** [comment]
Fixed in the past (will be available in Beta 1)
