### ISSUE TITLE
my character walk all the time

### ISSUE THREAD

**Issue by lucasPicault** [hovgaardgames/bigambitions#985]
### Build number

493

### Bug description

My character moves forward on its own, I can regain control of the direction only when I press the button to sprint.
When I alt tab the character stops.
otherwise it runs all the time even when I restart the game

### Steps to reproduce the bug

I just started a game and the character advances on its own

### Savegame file

[Save.txt](https://github.com/hovgaardgames/bigambitions/files/8362596/Save.txt)

### Screenshots or videos

[https://youtu.be/_tKiahDGunM](url)

**Comment by jhovgaard** [comment]
Hi @lucasPicault,

Do you have a controller connected? If yes, try plug it out.

**Comment by jokoho48** [comment]
Fixed in the Meanwhile
