### ISSUE TITLE
Options: Elements extend too far to the right

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#986]
### Build number

602

### Bug description

In the main menu's options, the "Graphics" comboboxes as well as the "Audio" volume slider extend too far towards the right side.

The centered "Full Screen" toggle also looks weird, maybe make toggles aligned to the left instead. But that's just my personal opinion.

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/160664930-a075ad41-c234-4488-95f6-4e903eafd1e6.png)

![grafik](https://user-images.githubusercontent.com/17579552/160664955-b3facd97-4e00-4db6-b290-7cc88c299d91.png)

**Comment by David-Goru** [comment]
Fixed in build 604
