### ISSUE TITLE
Jensen Capital only allowing initial loan of $40

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#987]
### Build number

603

### Bug description

When going to the bank at the start of the game, I can only get a loan of $40 instead of $15,000.
(Later on, when the objective shows, it is still the same, at that time they offered $105)

### Savegame file

[ThisDoesntLoan.json.txt](https://github.com/hovgaardgames/bigambitions/files/8373747/ThisDoesntLoan.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/160671133-b2c3e2e0-39ac-422b-8a76-967cb1ee3abd.png)

**Comment by David-Goru** [comment]
Fixed in build 604
