### ISSUE TITLE
clicking "interview" on people on the street just fast forwards through the conversation

### ISSUE THREAD

**Issue by psychedeliqueee** [hovgaardgames/bigambitions#991]
### Build number

493

### Bug description

clicking "interview" on people on the street just fast forwards through the conversation

### Steps to reproduce the bug

just click "interview"

### Savegame file

[New Vlad Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8375253/New.Vlad.Save.Game.txt)

### Screenshots or videos

https://www.youtube.com/watch?v=dbYXbGPB8zk

**Comment by Gerwanese** [comment]
That's not a bug but currently the intended behaviour. You can see the resulting statistics in the "Interview Lite" app. :)
