### ISSUE TITLE
Selecting an employee in MyEmployees will remove red color for "No task" and "Unassigned"

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#992]
### Build number

603

### Bug description

If you select any employee in the MyEmployees app, the red color for "No task" and "Unassigned" will be removed from all rows.
Changing the business assignment of the selected employee will bring back the colors (and deselect the row).

### Savegame file

[Employeeeeeeeeeeeehaaaaaa.json.txt](https://github.com/hovgaardgames/bigambitions/files/8375437/Employeeeeeeeeeeeehaaaaaa.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/160719017-ecb96ebd-6c0f-479e-ac38-8dcd0d3e756a.mp4

**Comment by David-Goru** [comment]
Partly fixed. The row still gets deselected, but that requires new functionality. Letting this open

**Comment by David-Goru** [comment]
Fixed in build 709
