### ISSUE TITLE
Warehouse Inventory: "Balance" unreadable

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#993]
### Build number

603

### Bug description

The green numbers for "Balance" are unreadable on the grey background.

### Savegame file

[GreenGreyGross.json.txt](https://github.com/hovgaardgames/bigambitions/files/8375467/GreenGreyGross.json.txt)

### Screenshots or videos

![grafik](https://user-images.githubusercontent.com/17579552/160719815-e190fac8-56fb-4c99-94b7-5fbd3f347a1b.png)

**Comment by David-Goru** [comment]
Fixed in build 733
