### ISSUE TITLE
Mop can be placed in void area, effectively losing it

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#995]
### Build number

606

### Bug description

If you pick up the mop and the buttons Place, Discard, Pack are in an area outside of the building, you can place the mop in that area. Afterwards the mop is lost.
If the buttons show up somewhere inside the shop area it doesn't happen because you can't move the mop with your mouse from inside to outside.

### Savegame file

[FillMeUpPlease.json.txt](https://github.com/hovgaardgames/bigambitions/files/8384504/FillMeUpPlease.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/160940499-f2703229-5ca1-43ce-a876-9a3efac4b356.mp4

**Comment by David-Goru** [comment]
Fixed in build 745
