### ISSUE TITLE
Can not enter office anymore.

### ISSUE THREAD

**Issue by Decimes** [hovgaardgames/bigambitions#996]
### Build number

606

### Bug description

Wanted to put some more items in my office. But no matter when or how I try, I can not get inside anymore. Location is office at 13 Thirdavenue, Tried to get in at different times but nothing works. Also after trying and failing to get in, when I save the game the saved file will not load anymore.

Some added info, after trying to get into the office my character walks instead of runs and can not cross a road, character goes to nearest crosswalk instead of just walking across the road where i I try to cross. Seems to be a problem with offices up north.

### Steps to reproduce the bug

Not sure, had no problem getting in the (game) day before.
Added save files, save5 I am near the office, save2 I saved just after trying to get in.

### Savegame file

[DMV-2.txt](https://github.com/hovgaardgames/bigambitions/files/8388260/DMV-2.txt)
[DMV-5.txt](https://github.com/hovgaardgames/bigambitions/files/8388262/DMV-5.txt)

**Comment by David-Goru** [comment]
Fixed in build 709
