### ISSUE TITLE
Boxes on pallet shelf show up at the original forklift parking position

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#997]
### Build number

607

### Bug description

My Warehous is at 3 Fifth Avenue.
If I take the forklift and load the pallet from one of my shelves, the boxes will not show up on the pallet but instead at the original parking position of the forklift.

### Savegame file

[Tycoon.json.txt](https://github.com/hovgaardgames/bigambitions/files/8389740/Tycoon.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161064629-197bd820-97e7-47be-a0d3-61829a63af32.mp4

**Comment by jokoho48** [comment]
Fixed in the meanwhile.
