### ISSUE TITLE
Cargo window doesn't close when forklift drives away from pallet shelf

### ISSUE THREAD

**Issue by Gerwanese** [hovgaardgames/bigambitions#998]
### Build number

607

### Bug description

When driving the forklift to a pallet shelf, the cargo window for that shelf will show up.
When driving the forklift away however, the cargo window will not close but stay open.

### Savegame file

[Tycoon.json.txt](https://github.com/hovgaardgames/bigambitions/files/8389740/Tycoon.json.txt)

### Screenshots or videos

https://user-images.githubusercontent.com/17579552/161064629-197bd820-97e7-47be-a0d3-61829a63af32.mp4

**Comment by David-Goru** [comment]
Fixed in build 731
