### ISSUE TITLE
Cant pick up Pallet

### ISSUE THREAD

**Issue by Amir1460** [hovgaardgames/bigambitions#999]
### Build number

606

### Bug description

Tried buying bottle of wine in the Warehouse Shop and loaded it on the forklift, bought the bottles and dropped the pallet. Now its not interactable.

### Steps to reproduce the bug

Go to warehouse
Drive forklift
Go to bottle of wine
Put bottle of wine in forklift
Buy bottle of wine
Drop pallet

### Savegame file

[New Amir Save Game.txt](https://github.com/hovgaardgames/bigambitions/files/8389882/New.Amir.Save.Game.txt)

### Screenshots or videos

https://www.youtube.com/watch?v=Q5J-OTJKejI

**Comment by jokoho48** [comment]
Fixed in Build 724. the pallet should not be able to be dropped.
